/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminClientsUpdateClient } from "../../funcs/adminClientsUpdateClient.js";
import { UpdateClientRequest$zodSchema } from "../../models/updateclientop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateClientRequest$zodSchema,
};

export const tool$adminClientsUpdateClient: ToolDefinition<typeof args> = {
  name: "admin-clients-update-client",
  description: `Update a client

Updates a client by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await adminClientsUpdateClient(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
