/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminClientsListClients } from "../../funcs/adminClientsListClients.js";
import { ListClientsRequest$zodSchema } from "../../models/listclientsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
	request: ListClientsRequest$zodSchema.optional(),
};

export const tool$adminClientsListClients: ToolDefinition<typeof args> = {
	name: "admin-clients-list-clients",
	description: `List clients

Returns a list of clients.`,
	args,
	tool: async (client, args, ctx) => {
		const [result, apiCall] = await adminClientsListClients(
			client,
			args.request,
			{ fetchOptions: { signal: ctx.signal } },
		).$inspect();

		if (!result.ok) {
			return {
				content: [{ type: "text", text: result.error.message }],
				isError: true,
			};
		}

		const value = result.value;

		const formattedResult = await formatResult(value, apiCall);

		return formattedResult;
	},
};
