/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { adminUsersUpdateAccountantUser } from "../../funcs/adminUsersUpdateAccountantUser.js";
import { UpdateAccountantUserRequest$zodSchema } from "../../models/updateaccountantuserop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateAccountantUserRequest$zodSchema,
};

export const tool$adminUsersUpdateAccountantUser: ToolDefinition<typeof args> =
  {
    name: "admin-users-update-accountant-user",
    description: `Update an accountant user

Updates an accountant user by ID.`,
    annotations: {
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await adminUsersUpdateAccountantUser(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
