/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { authGetV1Me } from "../../funcs/authGetV1Me.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$authGetV1Me: ToolDefinition = {
  name: "auth-get-v1-me",
  description: `Me`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await authGetV1Me(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
