/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectSessionsSubmitCollectBulk } from "../../funcs/collectSessionsSubmitCollectBulk.js";
import { SubmitCollectBulkRequest$zodSchema } from "../../models/submitcollectbulkop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SubmitCollectBulkRequest$zodSchema,
};

export const tool$collectSessionsSubmitCollectBulk: ToolDefinition<
  typeof args
> = {
  name: "collect-sessions-submit-collect-bulk",
  description: `Bulk upload files to a BULK_MATCH group

Uploads multiple files for a BULK_MATCH group. Files are stored without item assignment — server-side matching happens asynchronously.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectSessionsSubmitCollectBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
