/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectSessionsGetcollectSessionByToken } from "../../funcs/collectSessionsGetcollectSessionByToken.js";
import { GetcollectSessionByTokenRequest$zodSchema } from "../../models/getcollectsessionbytokenop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetcollectSessionByTokenRequest$zodSchema,
};

export const tool$collectSessionsGetcollectSessionByToken: ToolDefinition<
  typeof args
> = {
  name: "collect-sessions-getcollect-session-by-token",
  description: `Get collect session by token

Validates the token and returns the Collect-UI session payload if valid.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectSessionsGetcollectSessionByToken(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
