/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectSessionsSubmitCollectFile } from "../../funcs/collectSessionsSubmitCollectFile.js";
import { SubmitCollectFileRequest$zodSchema } from "../../models/submitcollectfileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SubmitCollectFileRequest$zodSchema,
};

export const tool$collectSessionsSubmitCollectFile: ToolDefinition<
  typeof args
> = {
  name: "collect-sessions-submit-collect-file",
  description: `Submit a file to a collect session

Uploads a file submission for a collect item via a public token.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectSessionsSubmitCollectFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
