/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { collectSessionsSubmitCollectFormData } from "../../funcs/collectSessionsSubmitCollectFormData.js";
import { SubmitCollectFormDataRequest$zodSchema } from "../../models/submitcollectformdataop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SubmitCollectFormDataRequest$zodSchema,
};

export const tool$collectSessionsSubmitCollectFormData: ToolDefinition<
  typeof args
> = {
  name: "collect-sessions-submit-collect-form-data",
  description: `Submit form data to a collect session

Submits a form field value for a collect item via a public token.`,
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await collectSessionsSubmitCollectFormData(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
