/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesGetFile } from "../../funcs/filesGetFile.js";
import { GetFileRequest$zodSchema } from "../../models/getfileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetFileRequest$zodSchema,
};

export const tool$filesGetFile: ToolDefinition<typeof args> = {
  name: "files-get-file",
  description: `Get a file

Returns a single file by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesGetFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
