/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesDeleteFile } from "../../funcs/filesDeleteFile.js";
import { DeleteFileRequest$zodSchema } from "../../models/deletefileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteFileRequest$zodSchema,
};

export const tool$filesDeleteFile: ToolDefinition<typeof args> = {
  name: "files-delete-file",
  description: `Delete a file

Deletes a file by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesDeleteFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
