/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesCreateFile } from "../../funcs/filesCreateFile.js";
import { CreateFileRequest$zodSchema } from "../../models/createfileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateFileRequest$zodSchema,
};

export const tool$filesCreateFile: ToolDefinition<typeof args> = {
  name: "files-create-file",
  description: `Upload a file

Uploads a new file. Maximum file size is 500MB.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesCreateFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
