/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { filesUpdateFile } from "../../funcs/filesUpdateFile.js";
import { UpdateFileRequest$zodSchema } from "../../models/updatefileop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateFileRequest$zodSchema,
};

export const tool$filesUpdateFile: ToolDefinition<typeof args> = {
  name: "files-update-file",
  description: `Update a file

Updates a file by ID.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await filesUpdateFile(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
