/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { healthCheckGetV1Ping } from "../../funcs/healthCheckGetV1Ping.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$healthCheckGetV1Ping: ToolDefinition = {
  name: "health-check-get-v1-ping",
  description: `Ping`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await healthCheckGetV1Ping(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
