/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksListTasks } from "../../funcs/tasksListTasks.js";
import { ListTasksRequest$zodSchema } from "../../models/listtasksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListTasksRequest$zodSchema,
};

export const tool$tasksListTasks: ToolDefinition<typeof args> = {
  name: "tasks-list-tasks",
  description: `List tasks

Returns a paginated list of tasks with optional client and workspace filters.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksListTasks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
