/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksGetTask } from "../../funcs/tasksGetTask.js";
import { GetTaskRequest$zodSchema } from "../../models/gettaskop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTaskRequest$zodSchema,
};

export const tool$tasksGetTask: ToolDefinition<typeof args> = {
  name: "tasks-get-task",
  description: `Get a task

Returns a single task object by ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksGetTask(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
