/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksUpdateTask } from "../../funcs/tasksUpdateTask.js";
import { UpdateTaskRequest$zodSchema } from "../../models/updatetaskop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTaskRequest$zodSchema,
};

export const tool$tasksUpdateTask: ToolDefinition<typeof args> = {
  name: "tasks-update-task",
  description: `Update a task

Updates an existing task object.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksUpdateTask(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
