/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tasksCreateTask } from "../../funcs/tasksCreateTask.js";
import { CreateTaskRequest$zodSchema } from "../../models/createtaskop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateTaskRequest$zodSchema,
};

export const tool$tasksCreateTask: ToolDefinition<typeof args> = {
  name: "tasks-create-task",
  description: `Create a task

Creates a new task and returns the created task object.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tasksCreateTask(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
