/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersListUsers } from "../../funcs/usersListUsers.js";
import { ListUsersRequest$zodSchema } from "../../models/listusersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListUsersRequest$zodSchema,
};

export const tool$usersListUsers: ToolDefinition<typeof args> = {
  name: "users-list-users",
  description: `List users

Returns a paginated list of client users.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersListUsers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
