/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { workspaceMembersListWorkspaceMembers } from "../../funcs/workspaceMembersListWorkspaceMembers.js";
import { ListWorkspaceMembersRequest$zodSchema } from "../../models/listworkspacemembersop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListWorkspaceMembersRequest$zodSchema,
};

export const tool$workspaceMembersListWorkspaceMembers: ToolDefinition<
  typeof args
> = {
  name: "workspace-members-list-workspace-members",
  description: `List workspace members

Returns workspace members for a workspace.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await workspaceMembersListWorkspaceMembers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
