/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SteuerboardCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  SubmitCollectFormDataRequest,
  SubmitCollectFormDataRequest$zodSchema,
  SubmitCollectFormDataResponse,
  SubmitCollectFormDataResponse$zodSchema,
} from "../models/submitcollectformdataop.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Submit form data to a collect session
 *
 * @remarks
 * Submits a form field value for a collect item via a public token.
 */
export function collectSessionsSubmitCollectFormData(
  client$: SteuerboardCore,
  request: SubmitCollectFormDataRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    SubmitCollectFormDataResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: SteuerboardCore,
  request: SubmitCollectFormDataRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      SubmitCollectFormDataResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => SubmitCollectFormDataRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = encodeJSON("body", payload$.CollectFormDataSubmit, {
    explode: true,
  });

  const pathParams$ = {
    token: encodeSimple("token", payload$.token, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/collect/sessions/{token}/submit/form-data")(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "submitCollectFormData",
    oAuth2Scopes: null,
    resolvedSecurity: null,
    securitySource: null,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    SubmitCollectFormDataResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(201, SubmitCollectFormDataResponse$zodSchema, {
      key: "CollectFormDataSubmission",
    }),
    M.json(404, SubmitCollectFormDataResponse$zodSchema, { key: "object" }),
    M.json(410, SubmitCollectFormDataResponse$zodSchema, {
      key: "bad_request",
    }),
    M.json(422, SubmitCollectFormDataResponse$zodSchema, { key: "oneOf" }),
    M.json(429, SubmitCollectFormDataResponse$zodSchema, { key: "rate_limit" }),
    M.json(500, SubmitCollectFormDataResponse$zodSchema, {
      key: "internal_error",
    }),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
