/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { SteuerboardCore } from "../core.js";
import { appendForm, encodeSimple, normalizeBlob } from "../lib/encodings.js";
import {
  bytesToBlob,
  getContentTypeFromFileName,
  readableStreamToArrayBuffer,
} from "../lib/files.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { pathToFunc } from "../lib/url.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import {
  SubmitCollectBulkRequest,
  SubmitCollectBulkRequest$zodSchema,
  SubmitCollectBulkResponse,
  SubmitCollectBulkResponse$zodSchema,
} from "../models/submitcollectbulkop.js";
import { APICall, APIPromise } from "../types/async.js";
import { isBlobLike } from "../types/blobs.js";
import { Result } from "../types/fp.js";
import { isReadableStream } from "../types/streams.js";

/**
 * Bulk upload files to a BULK_MATCH group
 *
 * @remarks
 * Uploads multiple files for a BULK_MATCH group. Files are stored without item assignment — server-side matching happens asynchronously.
 */
export function collectSessionsSubmitCollectBulk(
  client$: SteuerboardCore,
  request: SubmitCollectBulkRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    SubmitCollectBulkResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client$,
    request,
    options,
  ));
}

async function $do(
  client$: SteuerboardCore,
  request: SubmitCollectBulkRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      SubmitCollectBulkResponse,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed$ = safeParse(
    request,
    (value$) => SubmitCollectBulkRequest$zodSchema.parse(value$),
    "Input validation failed",
  );
  if (!parsed$.ok) {
    return [parsed$, { status: "invalid" }];
  }
  const payload$ = parsed$.value;
  const body$ = new FormData();
  for (const fileItem of payload$.CollectBulkSubmitForm.files ?? []) {
    if (isBlobLike(fileItem)) {
      const file = fileItem;
      const blob = await normalizeBlob(file);
      const name = "name" in file ? (file.name as string) : undefined;
      appendForm(body$, "files[]", blob, name);
    } else if (isReadableStream(fileItem.content)) {
      const buffer = await readableStreamToArrayBuffer(fileItem.content);
      const contentType = getContentTypeFromFileName(fileItem.fileName)
        || "application/octet-stream";
      appendForm(
        body$,
        "files[]",
        bytesToBlob(buffer, contentType),
        fileItem.fileName,
      );
    } else {
      const contentType = getContentTypeFromFileName(fileItem.fileName)
        || "application/octet-stream";
      appendForm(
        body$,
        "files[]",
        bytesToBlob(fileItem.content, contentType),
        fileItem.fileName,
      );
    }
  }
  appendForm(body$, "groupId", payload$.CollectBulkSubmitForm.groupId);

  const pathParams$ = {
    token: encodeSimple("token", payload$.token, {
      explode: false,
      charEncoding: "percent",
    }),
  };
  const path$ = pathToFunc("/collect/sessions/{token}/submit/bulk")(
    pathParams$,
  );

  const headers$ = new Headers(compactMap({
    Accept: "application/json",
  }));

  const context = {
    options: client$._options,
    baseURL: options?.serverURL ?? client$._baseURL ?? "",
    operationID: "submitCollectBulk",
    oAuth2Scopes: null,
    resolvedSecurity: null,
    securitySource: null,
    retryConfig: options?.retries
      || client$._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || [
      "429",
      "500",
      "502",
      "503",
      "504",
    ],
  };

  const requestRes = client$._createRequest(context, {
    method: "POST",
    baseURL: options?.serverURL,
    path: path$,
    headers: headers$,
    body: body$,
    userAgent: client$._options.userAgent,
    timeoutMs: options?.timeoutMs || client$._options.timeoutMs
      || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req$ = requestRes.value;

  const doResult = await client$._do(req$, {
    context,
    errorCodes: [],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req$ }];
  }
  const response = doResult.value;
  const responseFields$ = {
    HttpMeta: { Response: response, Request: req$ },
  };

  const [result$] = await M.match<
    SubmitCollectBulkResponse,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(201, SubmitCollectBulkResponse$zodSchema, {
      key: "CollectBulkSubmission",
    }),
    M.json(404, SubmitCollectBulkResponse$zodSchema, {
      key: "fourHundredAndFourApplicationJsonObject",
    }),
    M.json(410, SubmitCollectBulkResponse$zodSchema, { key: "bad_request" }),
    M.json(413, SubmitCollectBulkResponse$zodSchema, {
      key: "fourHundredAndThirteenApplicationJsonObject",
    }),
    M.json(422, SubmitCollectBulkResponse$zodSchema, {
      key: "fourHundredAndTwentyTwoApplicationJsonOneOf",
    }),
    M.json(429, SubmitCollectBulkResponse$zodSchema, { key: "rate_limit" }),
    M.nil(500, SubmitCollectBulkResponse$zodSchema),
  )(response, req$, { extraFields: responseFields$ });

  return [result$, { status: "complete", request: req$, response }];
}
