/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { SteuerboardCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import {
  createRegisterTool,
  MCPToolAnnotationFilter,
  registerDynamicTools,
} from "./tools.js";
import { tool$adminClientsCreateClient } from "./tools/adminClientsCreateClient.js";
import { tool$adminClientsGetClient } from "./tools/adminClientsGetClient.js";
import { tool$adminClientsListClients } from "./tools/adminClientsListClients.js";
import { tool$adminClientsUpdateClient } from "./tools/adminClientsUpdateClient.js";
import { tool$adminUsersDeleteAccountantUser } from "./tools/adminUsersDeleteAccountantUser.js";
import { tool$adminUsersGetAccountantUser } from "./tools/adminUsersGetAccountantUser.js";
import { tool$adminUsersInviteAccountantUser } from "./tools/adminUsersInviteAccountantUser.js";
import { tool$adminUsersListAccountantUsers } from "./tools/adminUsersListAccountantUsers.js";
import { tool$adminUsersUpdateAccountantUser } from "./tools/adminUsersUpdateAccountantUser.js";
import { tool$authMe } from "./tools/authMe.js";
import { tool$collectSessionsCompleteCollectSession } from "./tools/collectSessionsCompleteCollectSession.js";
import { tool$collectSessionsDeleteCollectSubmission } from "./tools/collectSessionsDeleteCollectSubmission.js";
import { tool$collectSessionsGetcollectSessionByToken } from "./tools/collectSessionsGetcollectSessionByToken.js";
import { tool$collectSessionsPingCollectSession } from "./tools/collectSessionsPingCollectSession.js";
import { tool$collectSessionsRequestLinkCollectToken } from "./tools/collectSessionsRequestLinkCollectToken.js";
import { tool$collectSessionsSubmitCollectBulk } from "./tools/collectSessionsSubmitCollectBulk.js";
import { tool$collectSessionsSubmitCollectFile } from "./tools/collectSessionsSubmitCollectFile.js";
import { tool$collectSessionsSubmitCollectFormData } from "./tools/collectSessionsSubmitCollectFormData.js";
import { tool$filesCreateFile } from "./tools/filesCreateFile.js";
import { tool$filesDeleteFile } from "./tools/filesDeleteFile.js";
import { tool$filesDownloadFileContent } from "./tools/filesDownloadFileContent.js";
import { tool$filesGetFile } from "./tools/filesGetFile.js";
import { tool$filesListFiles } from "./tools/filesListFiles.js";
import { tool$filesUpdateFile } from "./tools/filesUpdateFile.js";
import { tool$healthHealth } from "./tools/healthHealth.js";
import { tool$healthIndex } from "./tools/healthIndex.js";
import { tool$healthPing } from "./tools/healthPing.js";
import { tool$tasksCreateTask } from "./tools/tasksCreateTask.js";
import { tool$tasksDeleteTask } from "./tools/tasksDeleteTask.js";
import { tool$tasksGetTask } from "./tools/tasksGetTask.js";
import { tool$tasksListTasks } from "./tools/tasksListTasks.js";
import { tool$tasksUpdateTask } from "./tools/tasksUpdateTask.js";
import { tool$usersDeleteUser } from "./tools/usersDeleteUser.js";
import { tool$usersGetUser } from "./tools/usersGetUser.js";
import { tool$usersInviteUser } from "./tools/usersInviteUser.js";
import { tool$usersListUsers } from "./tools/usersListUsers.js";
import { tool$usersUpdateUser } from "./tools/usersUpdateUser.js";
import { tool$workspaceMembersCreateWorkspaceMember } from "./tools/workspaceMembersCreateWorkspaceMember.js";
import { tool$workspaceMembersListWorkspaceMembers } from "./tools/workspaceMembersListWorkspaceMembers.js";
import { tool$workspaceMembersRemoveWorkspaceMember } from "./tools/workspaceMembersRemoveWorkspaceMember.js";
import { tool$workspacesCreateWorkspace } from "./tools/workspacesCreateWorkspace.js";
import { tool$workspacesGetWorkspace } from "./tools/workspacesGetWorkspace.js";
import { tool$workspacesListWorkspaces } from "./tools/workspacesListWorkspaces.js";
import { tool$workspacesUpdateWorkspace } from "./tools/workspacesUpdateWorkspace.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  annotationFilter?: MCPToolAnnotationFilter | undefined;
  getSDK?: () => SteuerboardCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Steuerboard",
    version: "0.4.1",
  });

  const getClient = deps.getSDK || (() =>
    new SteuerboardCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
    deps.annotationFilter,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$healthIndex);
  tool(tool$healthHealth);
  tool(tool$healthPing);
  tool(tool$authMe);
  tool(tool$adminClientsListClients);
  tool(tool$adminClientsCreateClient);
  tool(tool$adminClientsGetClient);
  tool(tool$adminClientsUpdateClient);
  tool(tool$adminUsersListAccountantUsers);
  tool(tool$adminUsersInviteAccountantUser);
  tool(tool$adminUsersGetAccountantUser);
  tool(tool$adminUsersDeleteAccountantUser);
  tool(tool$adminUsersUpdateAccountantUser);
  tool(tool$collectSessionsGetcollectSessionByToken);
  tool(tool$collectSessionsPingCollectSession);
  tool(tool$collectSessionsCompleteCollectSession);
  tool(tool$collectSessionsRequestLinkCollectToken);
  tool(tool$collectSessionsSubmitCollectFile);
  tool(tool$collectSessionsSubmitCollectFormData);
  tool(tool$collectSessionsSubmitCollectBulk);
  tool(tool$collectSessionsDeleteCollectSubmission);
  tool(tool$workspacesListWorkspaces);
  tool(tool$workspacesCreateWorkspace);
  tool(tool$workspacesGetWorkspace);
  tool(tool$workspacesUpdateWorkspace);
  tool(tool$workspaceMembersListWorkspaceMembers);
  tool(tool$workspaceMembersCreateWorkspaceMember);
  tool(tool$workspaceMembersRemoveWorkspaceMember);
  tool(tool$filesListFiles);
  tool(tool$filesCreateFile);
  tool(tool$filesGetFile);
  tool(tool$filesDeleteFile);
  tool(tool$filesUpdateFile);
  tool(tool$filesDownloadFileContent);
  tool(tool$tasksListTasks);
  tool(tool$tasksCreateTask);
  tool(tool$tasksGetTask);
  tool(tool$tasksDeleteTask);
  tool(tool$tasksUpdateTask);
  tool(tool$usersListUsers);
  tool(tool$usersInviteUser);
  tool(tool$usersGetUser);
  tool(tool$usersDeleteUser);
  tool(tool$usersUpdateUser);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
