/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AccountantUserRole,
  AccountantUserRole$zodSchema,
} from "./accountantuserrole.js";

export type AccountantUser = {
  id: string;
  createdAt: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  roles: Array<AccountantUserRole>;
};

export const AccountantUser$zodSchema: z.ZodType<AccountantUser> = z.object({
  createdAt: z.iso.datetime({ offset: true }).describe(
    "ISO 8601 timestamp when the accountant user record was created.",
  ),
  email: z.string().describe("Email address of the accountant user."),
  firstName: z.string().nullable().describe(
    "First name of the accountant user, if provided.",
  ),
  id: z.string().describe("Identifier of the accountant user."),
  lastName: z.string().nullable().describe(
    "Last name of the accountant user, if provided.",
  ),
  roles: z.array(AccountantUserRole$zodSchema).describe(
    "Roles assigned to the accountant user.",
  ),
});
