/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AccountantUserRole = {
  id: string;
  name: string | null;
  customName: string | null;
};

export const AccountantUserRole$zodSchema: z.ZodType<AccountantUserRole> = z
  .object({
    customName: z.string().nullable().describe(
      "Custom label for the role, if defined.",
    ),
    id: z.string().describe(
      "Identifier of the role assigned to the accountant user.",
    ),
    name: z.string().nullable().describe(
      "Internal identifier of the role. Null when the role is custom only.",
    ),
  });
