/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const BadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type BadRequestType = z.infer<typeof BadRequestType$zodSchema>;

export const BadRequestCode$zodSchema = z.enum([
  "missing_client_id",
]);

export type BadRequestCode = z.infer<typeof BadRequestCode$zodSchema>;

export type BadRequest = {
  status_code: number;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

export const BadRequest$zodSchema: z.ZodType<
  BadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: BadRequestCode$zodSchema,
  message: z.string(),
  status_code: z.number(),
  type: BadRequestType$zodSchema,
});
