/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const BadRequestStatusCode$zodSchema = z.literal(400);

export type BadRequestStatusCode = z.infer<
  typeof BadRequestStatusCode$zodSchema
>;

export const BadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type BadRequestType = z.infer<typeof BadRequestType$zodSchema>;

export const BadRequestCode$zodSchema = z.enum([
  "missing_client_id",
]);

export type BadRequestCode = z.infer<typeof BadRequestCode$zodSchema>;

export type BadRequest = {
  status_code: BadRequestStatusCode;
  type: BadRequestType;
  code: BadRequestCode;
  message: string;
};

export const BadRequest$zodSchema: z.ZodType<
  BadRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: BadRequestCode$zodSchema,
  message: z.string(),
  status_code: BadRequestStatusCode$zodSchema,
  type: BadRequestType$zodSchema,
});
