/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Role to assign to the invited user. Can be 'admin', 'user'.
 */
export const ClientUserUpdateUserRole$zodSchema = z.enum([
  "admin",
  "user",
]).describe("Role to assign to the invited user. Can be 'admin', 'user'.");

export type ClientUserUpdateUserRole = z.infer<
  typeof ClientUserUpdateUserRole$zodSchema
>;

export type ClientUserUpdate = { role: ClientUserUpdateUserRole };

export const ClientUserUpdate$zodSchema: z.ZodType<
  ClientUserUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: ClientUserUpdateUserRole$zodSchema,
});
