/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Role to assign to the invited user. Can be 'admin', 'user'.
 */
export const ClientUserInviteUserRole$zodSchema = z.enum([
  "admin",
  "user",
]).describe("Role to assign to the invited user. Can be 'admin', 'user'.");

export type ClientUserInviteUserRole = z.infer<
  typeof ClientUserInviteUserRole$zodSchema
>;

export type ClientUserInvite = {
  email: string;
  role: ClientUserInviteUserRole;
  workspaceIds?: Array<string> | undefined;
};

export const ClientUserInvite$zodSchema: z.ZodType<
  ClientUserInvite,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  role: ClientUserInviteUserRole$zodSchema,
  workspaceIds: z.array(z.string()).optional(),
});
