/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ClientUser = {
  id: string;
  createdAt: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  roles: Array<string>;
};

export const ClientUser$zodSchema: z.ZodType<
  ClientUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  createdAt: z.string().datetime({ offset: true }),
  email: z.string(),
  firstName: z.string().nullable(),
  id: z.string(),
  lastName: z.string().nullable(),
  roles: z.array(z.string()),
});
