/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ClientUser = {
  id: string;
  createdAt: string;
  email: string;
  firstName: string | null;
  lastName: string | null;
  roles: Array<string>;
};

export const ClientUser$zodSchema: z.ZodType<ClientUser> = z.object({
  createdAt: z.iso.datetime({ offset: true }).describe(
    "The date and time when the client user record was created. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  email: z.string().describe("Email address of the client user."),
  firstName: z.string().nullable().describe(
    "First name of the client user, if provided.",
  ),
  id: z.string().describe("Identifier of the client user."),
  lastName: z.string().nullable().describe(
    "Last name of the client user, if provided.",
  ),
  roles: z.array(z.string()).describe(
    "List of role names assigned to the user.",
  ),
});
