/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * Role to assign to the invited user. Can be 'admin', 'user'.
 */
export const ClientUserInviteUserRole = {
  Admin: "admin",
  User: "user",
} as const;
/**
 * Role to assign to the invited user. Can be 'admin', 'user'.
 */
export type ClientUserInviteUserRole = ClosedEnum<
  typeof ClientUserInviteUserRole
>;

export const ClientUserInviteUserRole$zodSchema = z.enum([
  "admin",
  "user",
]).describe("Role to assign to the invited user. Can be 'admin', 'user'.");

export type ClientUserInvite = {
  email: string;
  role: ClientUserInviteUserRole;
  workspaceIds?: Array<string> | undefined;
};

export const ClientUserInvite$zodSchema: z.ZodType<ClientUserInvite> = z.object(
  {
    email: z.string().describe(
      "Email address that should receive the invitation.",
    ),
    role: ClientUserInviteUserRole$zodSchema.describe(
      "Role to assign to the invited user. Can be 'admin', 'user'.",
    ),
    workspaceIds: z.array(z.string()).optional().describe(
      "Optional list of workspace IDs the user should join immediately.",
    ),
  },
);
