/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Role that should replace the user's current role.
 */
export const ClientUserUpdateRole$zodSchema = z.enum([
  "client_admin",
  "client_user",
]).describe("Role that should replace the user's current role.");

export type ClientUserUpdateRole = z.infer<
  typeof ClientUserUpdateRole$zodSchema
>;

export type ClientUserUpdate = { role: ClientUserUpdateRole };

export const ClientUserUpdate$zodSchema: z.ZodType<
  ClientUserUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  role: ClientUserUpdateRole$zodSchema,
});
