/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Role to assign to the invited user.
 */
export const ClientUserInviteRole$zodSchema = z.enum([
  "client_admin",
  "client_user",
]).describe("Role to assign to the invited user.");

export type ClientUserInviteRole = z.infer<
  typeof ClientUserInviteRole$zodSchema
>;

export type ClientUserInvite = {
  email: string;
  role: ClientUserInviteRole;
  workspaceIds?: Array<string> | undefined;
};

export const ClientUserInvite$zodSchema: z.ZodType<
  ClientUserInvite,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  role: ClientUserInviteRole$zodSchema,
  workspaceIds: z.array(z.string()).optional(),
});
