/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectFormDataSubmission = {
  id: string;
  status: string;
  value: string | null;
  collectItemId: string;
  createdAt: string;
};

export const CollectFormDataSubmission$zodSchema: z.ZodType<
  CollectFormDataSubmission,
  z.ZodTypeDef,
  unknown
> = z.object({
  collectItemId: z.string(),
  createdAt: z.string().datetime({ offset: true }),
  id: z.string(),
  status: z.string(),
  value: z.string().nullable(),
});
