/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectFormDataSubmit = { collectItemId: string; value: string };

export const CollectFormDataSubmit$zodSchema: z.ZodType<CollectFormDataSubmit> =
  z.object({
    collectItemId: z.string().describe(
      "The ID of the collect item to submit against",
    ),
    value: z.string().describe("The form field value"),
  });
