/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectFileSubmission = {
  id: string;
  status: string;
  fileName: string | null;
  fileSize: number | null;
  fileMimeType: string | null;
  collectItemId: string;
  createdAt: string;
};

export const CollectFileSubmission$zodSchema: z.ZodType<CollectFileSubmission> =
  z.object({
    collectItemId: z.string().describe("The ID of the collect item"),
    createdAt: z.iso.datetime({ offset: true }).describe(
      "The date and time the submission was created",
    ),
    fileMimeType: z.string().nullable().describe(
      "The MIME type of the uploaded file",
    ),
    fileName: z.string().nullable().describe("The name of the uploaded file"),
    fileSize: z.number().nullable().describe(
      "The size of the uploaded file in bytes",
    ),
    id: z.string().describe("The ID of the submission"),
    status: z.string().describe("The status of the submission"),
  });
