/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectFileSubmitFormFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const CollectFileSubmitFormFile$zodSchema: z.ZodType<
  CollectFileSubmitFormFile,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string().base64(),
  fileName: z.string(),
});

export type CollectFileSubmitForm = {
  file: CollectFileSubmitFormFile | Blob;
  collectItemId: string;
};

export const CollectFileSubmitForm$zodSchema: z.ZodType<
  CollectFileSubmitForm,
  z.ZodTypeDef,
  unknown
> = z.object({
  collectItemId: z.string(),
  file: z.lazy(() => CollectFileSubmitFormFile$zodSchema),
});
