/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectFormDataSubmit = { collectItemId: string; value: string };

export const CollectFormDataSubmit$zodSchema: z.ZodType<
  CollectFormDataSubmit,
  z.ZodTypeDef,
  unknown
> = z.object({
  collectItemId: z.string(),
  value: z.string(),
});
