/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectBulkSubmitFormFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const CollectBulkSubmitFormFile$zodSchema: z.ZodType<
  CollectBulkSubmitFormFile,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string().base64(),
  fileName: z.string(),
});

export type CollectBulkSubmitForm = {
  files: Array<CollectBulkSubmitFormFile>;
  groupId: string;
};

export const CollectBulkSubmitForm$zodSchema: z.ZodType<
  CollectBulkSubmitForm,
  z.ZodTypeDef,
  unknown
> = z.object({
  files: z.array(z.lazy(() => CollectBulkSubmitFormFile$zodSchema)),
  groupId: z.string(),
});
