/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectFileSubmission = {
  id: string;
  status: string;
  fileName: string | null;
  fileSize: number | null;
  fileMimeType: string | null;
  collectItemId: string;
  createdAt: string;
};

export const CollectFileSubmission$zodSchema: z.ZodType<
  CollectFileSubmission,
  z.ZodTypeDef,
  unknown
> = z.object({
  collectItemId: z.string(),
  createdAt: z.string().datetime({ offset: true }),
  fileMimeType: z.string().nullable(),
  fileName: z.string().nullable(),
  fileSize: z.number().nullable(),
  id: z.string(),
  status: z.string(),
});
