/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CollectBulkSubmissionSubmission = {
  id: string;
  status: string;
  fileName: string | null;
  fileSize: number | null;
  fileMimeType: string | null;
  createdAt: string;
};

export const CollectBulkSubmissionSubmission$zodSchema: z.ZodType<
  CollectBulkSubmissionSubmission
> = z.object({
  createdAt: z.iso.datetime({ offset: true }),
  fileMimeType: z.string().nullable(),
  fileName: z.string().nullable(),
  fileSize: z.number().nullable(),
  id: z.string(),
  status: z.string(),
});

export type CollectBulkSubmission = {
  submissions: Array<CollectBulkSubmissionSubmission>;
};

export const CollectBulkSubmission$zodSchema: z.ZodType<CollectBulkSubmission> =
  z.object({
    submissions: z.array(
      z.lazy(() => CollectBulkSubmissionSubmission$zodSchema),
    ),
  });
