/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../lib/base64.js";

export type CollectBulkSubmitFormFile = {
  fileName: string;
  content: Uint8Array | string;
};

export const CollectBulkSubmitFormFile$zodSchema: z.ZodType<
  CollectBulkSubmitFormFile
> = z.object({
  content: z.string().describe("Base64-encoded binary content").transform(
    b64$.bytesFromBase64,
  ),
  fileName: z.string(),
});

export type CollectBulkSubmitForm = {
  files: Array<CollectBulkSubmitFormFile>;
  groupId: string;
};

export const CollectBulkSubmitForm$zodSchema: z.ZodType<CollectBulkSubmitForm> =
  z.object({
    files: z.array(z.lazy(() => CollectBulkSubmitFormFile$zodSchema)).describe(
      "The files to upload",
    ),
    groupId: z.string().describe(
      "The ID of the BULK_MATCH group to submit against",
    ),
  });
