/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Explicit completion outcome picked by the client: 'complete' (everything provided), 'incomplete' (will provide the rest later), 'incomplete_finished' (cannot provide the rest; clientNote explains).
 */
export const Outcome$zodSchema = z.enum([
  "complete",
  "incomplete",
  "incomplete_finished",
]).describe(
  "Explicit completion outcome picked by the client: 'complete' (everything provided), 'incomplete' (will provide the rest later), 'incomplete_finished' (cannot provide the rest; clientNote explains).",
);

export type Outcome = z.infer<typeof Outcome$zodSchema>;

export type CompleteSessionBody = {
  clientNote?: string | undefined;
  outcome?: Outcome | undefined;
};

export const CompleteSessionBody$zodSchema: z.ZodType<
  CompleteSessionBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  clientNote: z.string().optional(),
  outcome: Outcome$zodSchema.optional(),
});
