/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  CompleteSessionBody,
  CompleteSessionBody$zodSchema,
} from "./completesessionbody.js";
import {
  CompleteSessionResponse,
  CompleteSessionResponse$zodSchema,
} from "./completesessionresponse.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type CompleteCollectSessionRequest = {
  token: string;
  CompleteSessionBody?: CompleteSessionBody | undefined;
};

export const CompleteCollectSessionRequest$zodSchema: z.ZodType<
  CompleteCollectSessionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  CompleteSessionBody: CompleteSessionBody$zodSchema.optional(),
  token: z.string(),
});

export const CompleteCollectSessionStatusCode$zodSchema = z.literal(404);

export type CompleteCollectSessionStatusCode = z.infer<
  typeof CompleteCollectSessionStatusCode$zodSchema
>;

export const CompleteCollectSessionType$zodSchema = z.enum([
  "not_found",
]);

export type CompleteCollectSessionType = z.infer<
  typeof CompleteCollectSessionType$zodSchema
>;

export const CompleteCollectSessionCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

export type CompleteCollectSessionCode = z.infer<
  typeof CompleteCollectSessionCode$zodSchema
>;

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type CompleteCollectSessionResponseBody = {
  status_code: CompleteCollectSessionStatusCode;
  type: CompleteCollectSessionType;
  code: CompleteCollectSessionCode;
  message: string;
};

export const CompleteCollectSessionResponseBody$zodSchema: z.ZodType<
  CompleteCollectSessionResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CompleteCollectSessionCode$zodSchema,
  message: z.string(),
  status_code: CompleteCollectSessionStatusCode$zodSchema,
  type: CompleteCollectSessionType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

export type CompleteCollectSessionResponse =
  | CompleteCollectSessionResponseBody
  | BadRequest
  | RateLimit
  | CompleteSessionResponse;

export const CompleteCollectSessionResponse$zodSchema: z.ZodType<
  CompleteCollectSessionResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => CompleteCollectSessionResponseBody$zodSchema),
  BadRequest$zodSchema,
  RateLimit$zodSchema,
  CompleteSessionResponse$zodSchema,
]);
