/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ConflictStatusCode$zodSchema = z.literal(409);

export type ConflictStatusCode = z.infer<typeof ConflictStatusCode$zodSchema>;

export const ConflictType$zodSchema = z.enum([
  "conflict",
]);

export type ConflictType = z.infer<typeof ConflictType$zodSchema>;

export const ConflictCode$zodSchema = z.enum([
  "conflict",
]);

export type ConflictCode = z.infer<typeof ConflictCode$zodSchema>;

export type Conflict = {
  status_code: ConflictStatusCode;
  type: ConflictType;
  code: ConflictCode;
  message: string;
};

export const Conflict$zodSchema: z.ZodType<Conflict, z.ZodTypeDef, unknown> = z
  .object({
    code: ConflictCode$zodSchema,
    message: z.string(),
    status_code: ConflictStatusCode$zodSchema,
    type: ConflictType$zodSchema,
  });
