/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ConflictStatusCode = {
  FourHundredAndNine: 409,
} as const;
export type ConflictStatusCode = ClosedEnum<typeof ConflictStatusCode>;

export const ConflictStatusCode$zodSchema = z.literal(409);

export const ConflictType = {
  Conflict: "conflict",
} as const;
export type ConflictType = ClosedEnum<typeof ConflictType>;

export const ConflictType$zodSchema = z.enum([
  "conflict",
]);

export const ConflictCode = {
  Conflict: "conflict",
} as const;
export type ConflictCode = ClosedEnum<typeof ConflictCode>;

export const ConflictCode$zodSchema = z.enum([
  "conflict",
]);

export type Conflict = {
  status_code: ConflictStatusCode;
  type: ConflictType;
  code: ConflictCode;
  message: string;
};

export const Conflict$zodSchema: z.ZodType<Conflict> = z.object({
  code: ConflictCode$zodSchema,
  message: z.string(),
  status_code: ConflictStatusCode$zodSchema,
  type: ConflictType$zodSchema,
});
