/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Task, Task$zodSchema } from "./task.js";
import { TaskCreate, TaskCreate$zodSchema } from "./taskcreate.js";

export type CreateTaskRequest = { xClientId: string; TaskCreate: TaskCreate };

export const CreateTaskRequest$zodSchema: z.ZodType<
  CreateTaskRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  TaskCreate: TaskCreate$zodSchema,
  xClientId: z.string(),
});

export type CreateTaskPath = string | number;

export const CreateTaskPath$zodSchema: z.ZodType<
  CreateTaskPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type CreateTaskIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateTaskIssue$zodSchema: z.ZodType<
  CreateTaskIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type CreateTaskError = { issues: Array<CreateTaskIssue>; name: string };

export const CreateTaskError$zodSchema: z.ZodType<
  CreateTaskError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => CreateTaskIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type CreateTaskUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateTaskError;
};

export const CreateTaskUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  CreateTaskUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => CreateTaskError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const CreateTaskForbiddenStatusCode$zodSchema = z.literal(403);

export type CreateTaskForbiddenStatusCode = z.infer<
  typeof CreateTaskForbiddenStatusCode$zodSchema
>;

export const CreateTaskForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type CreateTaskForbiddenType = z.infer<
  typeof CreateTaskForbiddenType$zodSchema
>;

export const CreateTaskForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type CreateTaskForbiddenCode = z.infer<
  typeof CreateTaskForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type CreateTaskForbiddenResponseBody = {
  status_code: CreateTaskForbiddenStatusCode;
  type: CreateTaskForbiddenType;
  code: CreateTaskForbiddenCode;
  message: string;
};

export const CreateTaskForbiddenResponseBody$zodSchema: z.ZodType<
  CreateTaskForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateTaskForbiddenCode$zodSchema,
  message: z.string(),
  status_code: CreateTaskForbiddenStatusCode$zodSchema,
  type: CreateTaskForbiddenType$zodSchema,
}).describe("Missing scope");

export const CreateTaskStatusCode400$zodSchema = z.literal(400);

export type CreateTaskStatusCode400 = z.infer<
  typeof CreateTaskStatusCode400$zodSchema
>;

export const CreateTaskBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type CreateTaskBadRequestType = z.infer<
  typeof CreateTaskBadRequestType$zodSchema
>;

export const CreateTaskCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type CreateTaskCodeMissingClientID = z.infer<
  typeof CreateTaskCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type CreateTaskBadRequestResponseBody = {
  status_code: CreateTaskStatusCode400;
  type: CreateTaskBadRequestType;
  code: CreateTaskCodeMissingClientID;
  message: string;
};

export const CreateTaskBadRequestResponseBody$zodSchema: z.ZodType<
  CreateTaskBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateTaskCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: CreateTaskStatusCode400$zodSchema,
  type: CreateTaskBadRequestType$zodSchema,
}).describe("Missing client ID");

export type CreateTaskResponse =
  | Task
  | CreateTaskBadRequestResponseBody
  | AuthError
  | CreateTaskForbiddenResponseBody
  | RateLimit
  | CreateTaskUnprocessableEntityResponseBody;

export const CreateTaskResponse$zodSchema: z.ZodType<
  CreateTaskResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Task$zodSchema,
  z.lazy(() => CreateTaskBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => CreateTaskForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => CreateTaskUnprocessableEntityResponseBody$zodSchema),
]);
