/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Workspace, Workspace$zodSchema } from "./workspace.js";
import {
  WorkspaceCreate,
  WorkspaceCreate$zodSchema,
} from "./workspacecreate.js";

export const CreateWorkspaceForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type CreateWorkspaceForbiddenStatusCode = ClosedEnum<
  typeof CreateWorkspaceForbiddenStatusCode
>;

export const CreateWorkspaceForbiddenStatusCode$zodSchema = z.literal(403);

export const CreateWorkspaceForbiddenType = {
  AuthError: "auth_error",
} as const;
export type CreateWorkspaceForbiddenType = ClosedEnum<
  typeof CreateWorkspaceForbiddenType
>;

export const CreateWorkspaceForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const CreateWorkspaceForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type CreateWorkspaceForbiddenCode = ClosedEnum<
  typeof CreateWorkspaceForbiddenCode
>;

export const CreateWorkspaceForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export const CreateWorkspaceStatusCode400 = {
  FourHundred: 400,
} as const;
export type CreateWorkspaceStatusCode400 = ClosedEnum<
  typeof CreateWorkspaceStatusCode400
>;

export const CreateWorkspaceStatusCode400$zodSchema = z.literal(400);

export const CreateWorkspaceBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type CreateWorkspaceBadRequestType = ClosedEnum<
  typeof CreateWorkspaceBadRequestType
>;

export const CreateWorkspaceBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const CreateWorkspaceCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type CreateWorkspaceCodeMissingClientID = ClosedEnum<
  typeof CreateWorkspaceCodeMissingClientID
>;

export const CreateWorkspaceCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type CreateWorkspaceRequest = {
  xClientId: string;
  WorkspaceCreate: WorkspaceCreate;
};

export const CreateWorkspaceRequest$zodSchema: z.ZodType<
  CreateWorkspaceRequest
> = z.object({
  WorkspaceCreate: WorkspaceCreate$zodSchema.describe("Workspace create"),
  xClientId: z.string(),
});

export type CreateWorkspacePath = string | number;

export const CreateWorkspacePath$zodSchema: z.ZodType<CreateWorkspacePath> = z
  .union([
    z.string(),
    z.number(),
  ]);

export type CreateWorkspaceIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateWorkspaceIssue$zodSchema: z.ZodType<CreateWorkspaceIssue> = z
  .object({
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  });

export type CreateWorkspaceError = {
  issues: Array<CreateWorkspaceIssue>;
  name: string;
};

export const CreateWorkspaceError$zodSchema: z.ZodType<CreateWorkspaceError> = z
  .object({
    issues: z.array(z.lazy(() => CreateWorkspaceIssue$zodSchema)),
    name: z.string(),
  });

/**
 * The validation error(s)
 */
export type CreateWorkspaceUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateWorkspaceError;
};

export const CreateWorkspaceUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<CreateWorkspaceUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() => CreateWorkspaceError$zodSchema),
    success: z.boolean(),
  }).describe("The validation error(s)");

/**
 * Missing scope
 */
export type CreateWorkspaceForbiddenResponseBody = {
  status_code: CreateWorkspaceForbiddenStatusCode;
  type: CreateWorkspaceForbiddenType;
  code: CreateWorkspaceForbiddenCode;
  message: string;
};

export const CreateWorkspaceForbiddenResponseBody$zodSchema: z.ZodType<
  CreateWorkspaceForbiddenResponseBody
> = z.object({
  code: CreateWorkspaceForbiddenCode$zodSchema,
  message: z.string(),
  status_code: CreateWorkspaceForbiddenStatusCode$zodSchema,
  type: CreateWorkspaceForbiddenType$zodSchema,
}).describe("Missing scope");

/**
 * Missing client ID
 */
export type CreateWorkspaceBadRequestResponseBody = {
  status_code: CreateWorkspaceStatusCode400;
  type: CreateWorkspaceBadRequestType;
  code: CreateWorkspaceCodeMissingClientID;
  message: string;
};

export const CreateWorkspaceBadRequestResponseBody$zodSchema: z.ZodType<
  CreateWorkspaceBadRequestResponseBody
> = z.object({
  code: CreateWorkspaceCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: CreateWorkspaceStatusCode400$zodSchema,
  type: CreateWorkspaceBadRequestType$zodSchema,
}).describe("Missing client ID");

export type CreateWorkspaceResponse =
  | Workspace
  | CreateWorkspaceBadRequestResponseBody
  | AuthError
  | CreateWorkspaceForbiddenResponseBody
  | RateLimit
  | CreateWorkspaceUnprocessableEntityResponseBody;

export const CreateWorkspaceResponse$zodSchema: z.ZodType<
  CreateWorkspaceResponse
> = z.union([
  Workspace$zodSchema,
  z.lazy(() => CreateWorkspaceBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => CreateWorkspaceForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => CreateWorkspaceUnprocessableEntityResponseBody$zodSchema),
]);
