/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import {
  WorkspaceMember,
  WorkspaceMember$zodSchema,
} from "./workspacemember.js";
import {
  WorkspaceMemberCreate,
  WorkspaceMemberCreate$zodSchema,
} from "./workspacemembercreate.js";

export type CreateWorkspaceMemberRequest = {
  id: string;
  xClientId: string;
  WorkspaceMemberCreate: WorkspaceMemberCreate;
};

export const CreateWorkspaceMemberRequest$zodSchema: z.ZodType<
  CreateWorkspaceMemberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  WorkspaceMemberCreate: WorkspaceMemberCreate$zodSchema,
  id: z.string(),
  xClientId: z.string(),
});

export type CreateWorkspaceMemberPath = string | number;

export const CreateWorkspaceMemberPath$zodSchema: z.ZodType<
  CreateWorkspaceMemberPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type CreateWorkspaceMemberIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateWorkspaceMemberIssue$zodSchema: z.ZodType<
  CreateWorkspaceMemberIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type CreateWorkspaceMemberError = {
  issues: Array<CreateWorkspaceMemberIssue>;
  name: string;
};

export const CreateWorkspaceMemberError$zodSchema: z.ZodType<
  CreateWorkspaceMemberError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => CreateWorkspaceMemberIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type CreateWorkspaceMemberUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateWorkspaceMemberError;
};

export const CreateWorkspaceMemberUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<
    CreateWorkspaceMemberUnprocessableEntityResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.lazy(() => CreateWorkspaceMemberError$zodSchema),
    success: z.boolean(),
  }).describe("The validation error(s)");

export const CreateWorkspaceMemberForbiddenStatusCode$zodSchema = z.literal(
  403,
);

export type CreateWorkspaceMemberForbiddenStatusCode = z.infer<
  typeof CreateWorkspaceMemberForbiddenStatusCode$zodSchema
>;

export const CreateWorkspaceMemberForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type CreateWorkspaceMemberForbiddenType = z.infer<
  typeof CreateWorkspaceMemberForbiddenType$zodSchema
>;

export const CreateWorkspaceMemberForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type CreateWorkspaceMemberForbiddenCode = z.infer<
  typeof CreateWorkspaceMemberForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type CreateWorkspaceMemberForbiddenResponseBody = {
  status_code: CreateWorkspaceMemberForbiddenStatusCode;
  type: CreateWorkspaceMemberForbiddenType;
  code: CreateWorkspaceMemberForbiddenCode;
  message: string;
};

export const CreateWorkspaceMemberForbiddenResponseBody$zodSchema: z.ZodType<
  CreateWorkspaceMemberForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateWorkspaceMemberForbiddenCode$zodSchema,
  message: z.string(),
  status_code: CreateWorkspaceMemberForbiddenStatusCode$zodSchema,
  type: CreateWorkspaceMemberForbiddenType$zodSchema,
}).describe("Missing scope");

export const CreateWorkspaceMemberStatusCode400$zodSchema = z.literal(400);

export type CreateWorkspaceMemberStatusCode400 = z.infer<
  typeof CreateWorkspaceMemberStatusCode400$zodSchema
>;

export const CreateWorkspaceMemberBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type CreateWorkspaceMemberBadRequestType = z.infer<
  typeof CreateWorkspaceMemberBadRequestType$zodSchema
>;

export const CreateWorkspaceMemberCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type CreateWorkspaceMemberCodeMissingClientID = z.infer<
  typeof CreateWorkspaceMemberCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type CreateWorkspaceMemberBadRequestResponseBody = {
  status_code: CreateWorkspaceMemberStatusCode400;
  type: CreateWorkspaceMemberBadRequestType;
  code: CreateWorkspaceMemberCodeMissingClientID;
  message: string;
};

export const CreateWorkspaceMemberBadRequestResponseBody$zodSchema: z.ZodType<
  CreateWorkspaceMemberBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateWorkspaceMemberCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: CreateWorkspaceMemberStatusCode400$zodSchema,
  type: CreateWorkspaceMemberBadRequestType$zodSchema,
}).describe("Missing client ID");

export type CreateWorkspaceMemberResponse =
  | WorkspaceMember
  | CreateWorkspaceMemberBadRequestResponseBody
  | AuthError
  | CreateWorkspaceMemberForbiddenResponseBody
  | RateLimit
  | CreateWorkspaceMemberUnprocessableEntityResponseBody;

export const CreateWorkspaceMemberResponse$zodSchema: z.ZodType<
  CreateWorkspaceMemberResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  WorkspaceMember$zodSchema,
  z.lazy(() => CreateWorkspaceMemberBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => CreateWorkspaceMemberForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => CreateWorkspaceMemberUnprocessableEntityResponseBody$zodSchema),
]);
