/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Task, Task$zodSchema } from "./task.js";
import { TaskCreate, TaskCreate$zodSchema } from "./taskcreate.js";

export const CreateTaskForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type CreateTaskForbiddenStatusCode = ClosedEnum<
  typeof CreateTaskForbiddenStatusCode
>;

export const CreateTaskForbiddenStatusCode$zodSchema = z.literal(403);

export const CreateTaskForbiddenType = {
  AuthError: "auth_error",
} as const;
export type CreateTaskForbiddenType = ClosedEnum<
  typeof CreateTaskForbiddenType
>;

export const CreateTaskForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const CreateTaskForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type CreateTaskForbiddenCode = ClosedEnum<
  typeof CreateTaskForbiddenCode
>;

export const CreateTaskForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export const CreateTaskStatusCode400 = {
  FourHundred: 400,
} as const;
export type CreateTaskStatusCode400 = ClosedEnum<
  typeof CreateTaskStatusCode400
>;

export const CreateTaskStatusCode400$zodSchema = z.literal(400);

export const CreateTaskBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type CreateTaskBadRequestType = ClosedEnum<
  typeof CreateTaskBadRequestType
>;

export const CreateTaskBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const CreateTaskCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type CreateTaskCodeMissingClientID = ClosedEnum<
  typeof CreateTaskCodeMissingClientID
>;

export const CreateTaskCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type CreateTaskRequest = { xClientId: string; TaskCreate: TaskCreate };

export const CreateTaskRequest$zodSchema: z.ZodType<CreateTaskRequest> = z
  .object({
    TaskCreate: TaskCreate$zodSchema.describe("Task create"),
    xClientId: z.string(),
  });

export type CreateTaskPath = string | number;

export const CreateTaskPath$zodSchema: z.ZodType<CreateTaskPath> = z.union([
  z.string(),
  z.number(),
]);

export type CreateTaskIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateTaskIssue$zodSchema: z.ZodType<CreateTaskIssue> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type CreateTaskError = { issues: Array<CreateTaskIssue>; name: string };

export const CreateTaskError$zodSchema: z.ZodType<CreateTaskError> = z.object({
  issues: z.array(z.lazy(() => CreateTaskIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type CreateTaskUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateTaskError;
};

export const CreateTaskUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  CreateTaskUnprocessableEntityResponseBody
> = z.object({
  error: z.lazy(() => CreateTaskError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

/**
 * Missing scope
 */
export type CreateTaskForbiddenResponseBody = {
  status_code: CreateTaskForbiddenStatusCode;
  type: CreateTaskForbiddenType;
  code: CreateTaskForbiddenCode;
  message: string;
};

export const CreateTaskForbiddenResponseBody$zodSchema: z.ZodType<
  CreateTaskForbiddenResponseBody
> = z.object({
  code: CreateTaskForbiddenCode$zodSchema,
  message: z.string(),
  status_code: CreateTaskForbiddenStatusCode$zodSchema,
  type: CreateTaskForbiddenType$zodSchema,
}).describe("Missing scope");

/**
 * Missing client ID
 */
export type CreateTaskBadRequestResponseBody = {
  status_code: CreateTaskStatusCode400;
  type: CreateTaskBadRequestType;
  code: CreateTaskCodeMissingClientID;
  message: string;
};

export const CreateTaskBadRequestResponseBody$zodSchema: z.ZodType<
  CreateTaskBadRequestResponseBody
> = z.object({
  code: CreateTaskCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: CreateTaskStatusCode400$zodSchema,
  type: CreateTaskBadRequestType$zodSchema,
}).describe("Missing client ID");

export type CreateTaskResponse =
  | Task
  | CreateTaskBadRequestResponseBody
  | AuthError
  | CreateTaskForbiddenResponseBody
  | RateLimit
  | CreateTaskUnprocessableEntityResponseBody;

export const CreateTaskResponse$zodSchema: z.ZodType<CreateTaskResponse> = z
  .union([
    Task$zodSchema,
    z.lazy(() => CreateTaskBadRequestResponseBody$zodSchema),
    AuthError$zodSchema,
    z.lazy(() => CreateTaskForbiddenResponseBody$zodSchema),
    RateLimit$zodSchema,
    z.lazy(() => CreateTaskUnprocessableEntityResponseBody$zodSchema),
  ]);
