/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Client, Client$zodSchema } from "./client.js";

/**
 * Rate limit exceeded. Slow down requests or retry after the time specified in the rate limit response headers
 */
export type CreateClientTooManyRequestsResponseBody = { message: string };

export const CreateClientTooManyRequestsResponseBody$zodSchema: z.ZodType<
  CreateClientTooManyRequestsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe(
  "Rate limit exceeded. Slow down requests or retry after the time specified in the rate limit response headers",
);

export type CreateClientPath = string | number;

export const CreateClientPath$zodSchema: z.ZodType<
  CreateClientPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type CreateClientIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateClientIssue$zodSchema: z.ZodType<
  CreateClientIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type CreateClientError = {
  issues: Array<CreateClientIssue>;
  name: string;
};

export const CreateClientError$zodSchema: z.ZodType<
  CreateClientError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => CreateClientIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type CreateClientUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateClientError;
};

export const CreateClientUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  CreateClientUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => CreateClientError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export type CreateClientResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Client?: Client | undefined;
  fourHundredAndTwentyTwoApplicationJsonObject?:
    | CreateClientUnprocessableEntityResponseBody
    | undefined;
  fourHundredAndTwentyNineApplicationJsonObject?:
    | CreateClientTooManyRequestsResponseBody
    | undefined;
};

export const CreateClientResponse$zodSchema: z.ZodType<
  CreateClientResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  Client: Client$zodSchema.optional(),
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  fourHundredAndTwentyNineApplicationJsonObject: z.lazy(() =>
    CreateClientTooManyRequestsResponseBody$zodSchema
  ).optional(),
  fourHundredAndTwentyTwoApplicationJsonObject: z.lazy(() =>
    CreateClientUnprocessableEntityResponseBody$zodSchema
  ).optional(),
});
