/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { FileT, FileT$zodSchema } from "./file.js";
import { FileCreate, FileCreate$zodSchema } from "./filecreate.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type CreateFileRequest = { xClientId: string; FileCreate: FileCreate };

export const CreateFileRequest$zodSchema: z.ZodType<
  CreateFileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  FileCreate: FileCreate$zodSchema,
  xClientId: z.string(),
});

export type CreateFilePath = string | number;

export const CreateFilePath$zodSchema: z.ZodType<
  CreateFilePath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type CreateFileIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateFileIssue$zodSchema: z.ZodType<
  CreateFileIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type CreateFileError = { issues: Array<CreateFileIssue>; name: string };

export const CreateFileError$zodSchema: z.ZodType<
  CreateFileError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => CreateFileIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type CreateFileUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateFileError;
};

export const CreateFileUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  CreateFileUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => CreateFileError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const CreateFileRequestEntityTooLargeStatusCode$zodSchema = z.literal(
  413,
);

export type CreateFileRequestEntityTooLargeStatusCode = z.infer<
  typeof CreateFileRequestEntityTooLargeStatusCode$zodSchema
>;

export const CreateFileRequestEntityTooLargeType$zodSchema = z.enum([
  "bad_request",
]);

export type CreateFileRequestEntityTooLargeType = z.infer<
  typeof CreateFileRequestEntityTooLargeType$zodSchema
>;

export const CreateFileRequestEntityTooLargeCode$zodSchema = z.enum([
  "payload_too_large",
]);

export type CreateFileRequestEntityTooLargeCode = z.infer<
  typeof CreateFileRequestEntityTooLargeCode$zodSchema
>;

/**
 * Payload too large
 */
export type CreateFileRequestEntityTooLargeResponseBody = {
  status_code: CreateFileRequestEntityTooLargeStatusCode;
  type: CreateFileRequestEntityTooLargeType;
  code: CreateFileRequestEntityTooLargeCode;
  message: string;
};

export const CreateFileRequestEntityTooLargeResponseBody$zodSchema: z.ZodType<
  CreateFileRequestEntityTooLargeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateFileRequestEntityTooLargeCode$zodSchema,
  message: z.string(),
  status_code: CreateFileRequestEntityTooLargeStatusCode$zodSchema,
  type: CreateFileRequestEntityTooLargeType$zodSchema,
}).describe("Payload too large");

export const CreateFileForbiddenStatusCode$zodSchema = z.literal(403);

export type CreateFileForbiddenStatusCode = z.infer<
  typeof CreateFileForbiddenStatusCode$zodSchema
>;

export const CreateFileForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type CreateFileForbiddenType = z.infer<
  typeof CreateFileForbiddenType$zodSchema
>;

export const CreateFileForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type CreateFileForbiddenCode = z.infer<
  typeof CreateFileForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type CreateFileForbiddenResponseBody = {
  status_code: CreateFileForbiddenStatusCode;
  type: CreateFileForbiddenType;
  code: CreateFileForbiddenCode;
  message: string;
};

export const CreateFileForbiddenResponseBody$zodSchema: z.ZodType<
  CreateFileForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateFileForbiddenCode$zodSchema,
  message: z.string(),
  status_code: CreateFileForbiddenStatusCode$zodSchema,
  type: CreateFileForbiddenType$zodSchema,
}).describe("Missing scope");

export const CreateFileStatusCode400$zodSchema = z.literal(400);

export type CreateFileStatusCode400 = z.infer<
  typeof CreateFileStatusCode400$zodSchema
>;

export const CreateFileBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type CreateFileBadRequestType = z.infer<
  typeof CreateFileBadRequestType$zodSchema
>;

export const CreateFileCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type CreateFileCodeMissingClientID = z.infer<
  typeof CreateFileCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type CreateFileResponseBodyMissingClientID = {
  status_code: CreateFileStatusCode400;
  type: CreateFileBadRequestType;
  code: CreateFileCodeMissingClientID;
  message: string;
};

export const CreateFileResponseBodyMissingClientID$zodSchema: z.ZodType<
  CreateFileResponseBodyMissingClientID,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateFileCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: CreateFileStatusCode400$zodSchema,
  type: CreateFileBadRequestType$zodSchema,
}).describe("Missing client ID");

export type CreateFileResponse =
  | FileT
  | CreateFileResponseBodyMissingClientID
  | AuthError
  | CreateFileForbiddenResponseBody
  | CreateFileRequestEntityTooLargeResponseBody
  | RateLimit
  | CreateFileUnprocessableEntityResponseBody;

export const CreateFileResponse$zodSchema: z.ZodType<
  CreateFileResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  FileT$zodSchema,
  z.lazy(() => CreateFileResponseBodyMissingClientID$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => CreateFileForbiddenResponseBody$zodSchema),
  z.lazy(() => CreateFileRequestEntityTooLargeResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => CreateFileUnprocessableEntityResponseBody$zodSchema),
]);
