/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Workspace, Workspace$zodSchema } from "./workspace.js";
import {
  WorkspaceCreate,
  WorkspaceCreate$zodSchema,
} from "./workspacecreate.js";

export type CreateWorkspaceRequest = {
  xClientId: string;
  WorkspaceCreate: WorkspaceCreate;
};

export const CreateWorkspaceRequest$zodSchema: z.ZodType<
  CreateWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  WorkspaceCreate: WorkspaceCreate$zodSchema,
  xClientId: z.string(),
});

export type CreateWorkspacePath = string | number;

export const CreateWorkspacePath$zodSchema: z.ZodType<
  CreateWorkspacePath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type CreateWorkspaceIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const CreateWorkspaceIssue$zodSchema: z.ZodType<
  CreateWorkspaceIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type CreateWorkspaceError = {
  issues: Array<CreateWorkspaceIssue>;
  name: string;
};

export const CreateWorkspaceError$zodSchema: z.ZodType<
  CreateWorkspaceError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => CreateWorkspaceIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type CreateWorkspaceUnprocessableEntityResponseBody = {
  success: boolean;
  error: CreateWorkspaceError;
};

export const CreateWorkspaceUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<
    CreateWorkspaceUnprocessableEntityResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.lazy(() => CreateWorkspaceError$zodSchema),
    success: z.boolean(),
  }).describe("The validation error(s)");

export const CreateWorkspaceForbiddenStatusCode$zodSchema = z.literal(403);

export type CreateWorkspaceForbiddenStatusCode = z.infer<
  typeof CreateWorkspaceForbiddenStatusCode$zodSchema
>;

export const CreateWorkspaceForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type CreateWorkspaceForbiddenType = z.infer<
  typeof CreateWorkspaceForbiddenType$zodSchema
>;

export const CreateWorkspaceForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type CreateWorkspaceForbiddenCode = z.infer<
  typeof CreateWorkspaceForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type CreateWorkspaceForbiddenResponseBody = {
  status_code: CreateWorkspaceForbiddenStatusCode;
  type: CreateWorkspaceForbiddenType;
  code: CreateWorkspaceForbiddenCode;
  message: string;
};

export const CreateWorkspaceForbiddenResponseBody$zodSchema: z.ZodType<
  CreateWorkspaceForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateWorkspaceForbiddenCode$zodSchema,
  message: z.string(),
  status_code: CreateWorkspaceForbiddenStatusCode$zodSchema,
  type: CreateWorkspaceForbiddenType$zodSchema,
}).describe("Missing scope");

export const CreateWorkspaceStatusCode400$zodSchema = z.literal(400);

export type CreateWorkspaceStatusCode400 = z.infer<
  typeof CreateWorkspaceStatusCode400$zodSchema
>;

export const CreateWorkspaceBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type CreateWorkspaceBadRequestType = z.infer<
  typeof CreateWorkspaceBadRequestType$zodSchema
>;

export const CreateWorkspaceCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type CreateWorkspaceCodeMissingClientID = z.infer<
  typeof CreateWorkspaceCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type CreateWorkspaceBadRequestResponseBody = {
  status_code: CreateWorkspaceStatusCode400;
  type: CreateWorkspaceBadRequestType;
  code: CreateWorkspaceCodeMissingClientID;
  message: string;
};

export const CreateWorkspaceBadRequestResponseBody$zodSchema: z.ZodType<
  CreateWorkspaceBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: CreateWorkspaceCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: CreateWorkspaceStatusCode400$zodSchema,
  type: CreateWorkspaceBadRequestType$zodSchema,
}).describe("Missing client ID");

export type CreateWorkspaceResponse =
  | Workspace
  | CreateWorkspaceBadRequestResponseBody
  | AuthError
  | CreateWorkspaceForbiddenResponseBody
  | RateLimit
  | CreateWorkspaceUnprocessableEntityResponseBody;

export const CreateWorkspaceResponse$zodSchema: z.ZodType<
  CreateWorkspaceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Workspace$zodSchema,
  z.lazy(() => CreateWorkspaceBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => CreateWorkspaceForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => CreateWorkspaceUnprocessableEntityResponseBody$zodSchema),
]);
