/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Task, Task$zodSchema } from "./task.js";

export type DeleteTaskRequest = { id: string; xClientId: string };

export const DeleteTaskRequest$zodSchema: z.ZodType<
  DeleteTaskRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  xClientId: z.string(),
});

export type DeleteTaskPath = string | number;

export const DeleteTaskPath$zodSchema: z.ZodType<
  DeleteTaskPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type DeleteTaskIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const DeleteTaskIssue$zodSchema: z.ZodType<
  DeleteTaskIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type DeleteTaskError = { issues: Array<DeleteTaskIssue>; name: string };

export const DeleteTaskError$zodSchema: z.ZodType<
  DeleteTaskError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => DeleteTaskIssue$zodSchema)),
  name: z.string(),
});

/**
 * Invalid id error
 */
export type DeleteTaskUnprocessableEntityResponseBody = {
  success: boolean;
  error: DeleteTaskError;
};

export const DeleteTaskUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  DeleteTaskUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => DeleteTaskError$zodSchema),
  success: z.boolean(),
}).describe("Invalid id error");

export const DeleteTaskForbiddenStatusCode$zodSchema = z.literal(403);

export type DeleteTaskForbiddenStatusCode = z.infer<
  typeof DeleteTaskForbiddenStatusCode$zodSchema
>;

export const DeleteTaskForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type DeleteTaskForbiddenType = z.infer<
  typeof DeleteTaskForbiddenType$zodSchema
>;

export const DeleteTaskForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type DeleteTaskForbiddenCode = z.infer<
  typeof DeleteTaskForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type DeleteTaskForbiddenResponseBody = {
  status_code: DeleteTaskForbiddenStatusCode;
  type: DeleteTaskForbiddenType;
  code: DeleteTaskForbiddenCode;
  message: string;
};

export const DeleteTaskForbiddenResponseBody$zodSchema: z.ZodType<
  DeleteTaskForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: DeleteTaskForbiddenCode$zodSchema,
  message: z.string(),
  status_code: DeleteTaskForbiddenStatusCode$zodSchema,
  type: DeleteTaskForbiddenType$zodSchema,
}).describe("Missing scope");

export const DeleteTaskStatusCode400$zodSchema = z.literal(400);

export type DeleteTaskStatusCode400 = z.infer<
  typeof DeleteTaskStatusCode400$zodSchema
>;

export const DeleteTaskBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type DeleteTaskBadRequestType = z.infer<
  typeof DeleteTaskBadRequestType$zodSchema
>;

export const DeleteTaskCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type DeleteTaskCodeMissingClientID = z.infer<
  typeof DeleteTaskCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type DeleteTaskBadRequestResponseBody = {
  status_code: DeleteTaskStatusCode400;
  type: DeleteTaskBadRequestType;
  code: DeleteTaskCodeMissingClientID;
  message: string;
};

export const DeleteTaskBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteTaskBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: DeleteTaskCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: DeleteTaskStatusCode400$zodSchema,
  type: DeleteTaskBadRequestType$zodSchema,
}).describe("Missing client ID");

export type DeleteTaskResponse =
  | Task
  | DeleteTaskBadRequestResponseBody
  | AuthError
  | DeleteTaskForbiddenResponseBody
  | NotFound
  | RateLimit
  | DeleteTaskUnprocessableEntityResponseBody;

export const DeleteTaskResponse$zodSchema: z.ZodType<
  DeleteTaskResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Task$zodSchema,
  z.lazy(() => DeleteTaskBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => DeleteTaskForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  RateLimit$zodSchema,
  z.lazy(() => DeleteTaskUnprocessableEntityResponseBody$zodSchema),
]);
