/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteCollectSubmissionResponse = { deleted: boolean };

export const DeleteCollectSubmissionResponse$zodSchema: z.ZodType<
  DeleteCollectSubmissionResponse
> = z.object({
  deleted: z.boolean().describe("Whether the submission was deleted"),
});
