/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  DeleteCollectSubmissionResponse,
  DeleteCollectSubmissionResponse$zodSchema,
} from "./deletecollectsubmissionresponse.js";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const DeleteCollectSubmissionNotFoundStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type DeleteCollectSubmissionNotFoundStatusCode = ClosedEnum<
  typeof DeleteCollectSubmissionNotFoundStatusCode
>;

export const DeleteCollectSubmissionNotFoundStatusCode$zodSchema = z.literal(
  404,
);

export const DeleteCollectSubmissionNotFoundType = {
  NotFound: "not_found",
} as const;
export type DeleteCollectSubmissionNotFoundType = ClosedEnum<
  typeof DeleteCollectSubmissionNotFoundType
>;

export const DeleteCollectSubmissionNotFoundType$zodSchema = z.enum([
  "not_found",
]);

export const DeleteCollectSubmissionNotFoundCode = {
  CollectTokenNotFound: "collect_token_not_found",
} as const;
export type DeleteCollectSubmissionNotFoundCode = ClosedEnum<
  typeof DeleteCollectSubmissionNotFoundCode
>;

export const DeleteCollectSubmissionNotFoundCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

export const DeleteCollectSubmissionStatusCode400 = {
  FourHundred: 400,
} as const;
export type DeleteCollectSubmissionStatusCode400 = ClosedEnum<
  typeof DeleteCollectSubmissionStatusCode400
>;

export const DeleteCollectSubmissionStatusCode400$zodSchema = z.literal(400);

export const DeleteCollectSubmissionBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type DeleteCollectSubmissionBadRequestType = ClosedEnum<
  typeof DeleteCollectSubmissionBadRequestType
>;

export const DeleteCollectSubmissionBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const CodeInvalidInput = {
  InvalidInput: "invalid_input",
} as const;
export type CodeInvalidInput = ClosedEnum<typeof CodeInvalidInput>;

export const CodeInvalidInput$zodSchema = z.enum([
  "invalid_input",
]);

export type DeleteCollectSubmissionRequest = {
  token: string;
  submissionId: string;
};

export const DeleteCollectSubmissionRequest$zodSchema: z.ZodType<
  DeleteCollectSubmissionRequest
> = z.object({
  submissionId: z.string(),
  token: z.string(),
});

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type DeleteCollectSubmissionNotFoundResponseBody = {
  status_code: DeleteCollectSubmissionNotFoundStatusCode;
  type: DeleteCollectSubmissionNotFoundType;
  code: DeleteCollectSubmissionNotFoundCode;
  message: string;
};

export const DeleteCollectSubmissionNotFoundResponseBody$zodSchema: z.ZodType<
  DeleteCollectSubmissionNotFoundResponseBody
> = z.object({
  code: DeleteCollectSubmissionNotFoundCode$zodSchema,
  message: z.string(),
  status_code: DeleteCollectSubmissionNotFoundStatusCode$zodSchema,
  type: DeleteCollectSubmissionNotFoundType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

/**
 * Cannot delete a non-pending submission
 */
export type DeleteCollectSubmissionBadRequestResponseBody = {
  status_code: DeleteCollectSubmissionStatusCode400;
  type: DeleteCollectSubmissionBadRequestType;
  code: CodeInvalidInput;
  message: string;
};

export const DeleteCollectSubmissionBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteCollectSubmissionBadRequestResponseBody
> = z.object({
  code: CodeInvalidInput$zodSchema,
  message: z.string(),
  status_code: DeleteCollectSubmissionStatusCode400$zodSchema,
  type: DeleteCollectSubmissionBadRequestType$zodSchema,
}).describe("Cannot delete a non-pending submission");

export type DeleteCollectSubmissionResponseResponse =
  | DeleteCollectSubmissionBadRequestResponseBody
  | DeleteCollectSubmissionNotFoundResponseBody
  | BadRequest
  | RateLimit
  | InternalError
  | DeleteCollectSubmissionResponse;

export const DeleteCollectSubmissionResponseResponse$zodSchema: z.ZodType<
  DeleteCollectSubmissionResponseResponse
> = z.union([
  z.lazy(() => DeleteCollectSubmissionBadRequestResponseBody$zodSchema),
  z.lazy(() => DeleteCollectSubmissionNotFoundResponseBody$zodSchema),
  BadRequest$zodSchema,
  RateLimit$zodSchema,
  InternalError$zodSchema,
  DeleteCollectSubmissionResponse$zodSchema,
]);
