/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { DeleteResponse, DeleteResponse$zodSchema } from "./deleteresponse.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const DeleteAccountantUserStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type DeleteAccountantUserStatusCode = ClosedEnum<
  typeof DeleteAccountantUserStatusCode
>;

export const DeleteAccountantUserStatusCode$zodSchema = z.literal(403);

export const DeleteAccountantUserType = {
  AuthError: "auth_error",
} as const;
export type DeleteAccountantUserType = ClosedEnum<
  typeof DeleteAccountantUserType
>;

export const DeleteAccountantUserType$zodSchema = z.enum([
  "auth_error",
]);

export const DeleteAccountantUserCode = {
  MissingScope: "missing_scope",
} as const;
export type DeleteAccountantUserCode = ClosedEnum<
  typeof DeleteAccountantUserCode
>;

export const DeleteAccountantUserCode$zodSchema = z.enum([
  "missing_scope",
]);

export type DeleteAccountantUserRequest = { id: string };

export const DeleteAccountantUserRequest$zodSchema: z.ZodType<
  DeleteAccountantUserRequest
> = z.object({
  id: z.string(),
});

/**
 * Missing scope
 */
export type DeleteAccountantUserResponseBody = {
  status_code: DeleteAccountantUserStatusCode;
  type: DeleteAccountantUserType;
  code: DeleteAccountantUserCode;
  message: string;
};

export const DeleteAccountantUserResponseBody$zodSchema: z.ZodType<
  DeleteAccountantUserResponseBody
> = z.object({
  code: DeleteAccountantUserCode$zodSchema,
  message: z.string(),
  status_code: DeleteAccountantUserStatusCode$zodSchema,
  type: DeleteAccountantUserType$zodSchema,
}).describe("Missing scope");

export type DeleteAccountantUserResponse =
  | AuthError
  | DeleteAccountantUserResponseBody
  | NotFound
  | Conflict
  | RateLimit
  | DeleteResponse;

export const DeleteAccountantUserResponse$zodSchema: z.ZodType<
  DeleteAccountantUserResponse
> = z.union([
  AuthError$zodSchema,
  z.lazy(() => DeleteAccountantUserResponseBody$zodSchema),
  NotFound$zodSchema,
  Conflict$zodSchema,
  RateLimit$zodSchema,
  DeleteResponse$zodSchema,
]);
