/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { DeleteResponse, DeleteResponse$zodSchema } from "./deleteresponse.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const DeleteUserForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type DeleteUserForbiddenStatusCode = ClosedEnum<
  typeof DeleteUserForbiddenStatusCode
>;

export const DeleteUserForbiddenStatusCode$zodSchema = z.literal(403);

export const DeleteUserForbiddenType = {
  AuthError: "auth_error",
} as const;
export type DeleteUserForbiddenType = ClosedEnum<
  typeof DeleteUserForbiddenType
>;

export const DeleteUserForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const DeleteUserForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type DeleteUserForbiddenCode = ClosedEnum<
  typeof DeleteUserForbiddenCode
>;

export const DeleteUserForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export const DeleteUserStatusCode400 = {
  FourHundred: 400,
} as const;
export type DeleteUserStatusCode400 = ClosedEnum<
  typeof DeleteUserStatusCode400
>;

export const DeleteUserStatusCode400$zodSchema = z.literal(400);

export const DeleteUserBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type DeleteUserBadRequestType = ClosedEnum<
  typeof DeleteUserBadRequestType
>;

export const DeleteUserBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const DeleteUserCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type DeleteUserCodeMissingClientID = ClosedEnum<
  typeof DeleteUserCodeMissingClientID
>;

export const DeleteUserCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type DeleteUserRequest = { id: string; xClientId: string };

export const DeleteUserRequest$zodSchema: z.ZodType<DeleteUserRequest> = z
  .object({
    id: z.string(),
    xClientId: z.string(),
  });

export type DeleteUserPath2 = string | number;

export const DeleteUserPath2$zodSchema: z.ZodType<DeleteUserPath2> = z.union([
  z.string(),
  z.number(),
]);

export type DeleteUserIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const DeleteUserIssue2$zodSchema: z.ZodType<DeleteUserIssue2> = z.object(
  {
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  },
);

export type DeleteUserError2 = {
  issues: Array<DeleteUserIssue2>;
  name: string;
};

export const DeleteUserError2$zodSchema: z.ZodType<DeleteUserError2> = z.object(
  {
    issues: z.array(z.lazy(() => DeleteUserIssue2$zodSchema)),
    name: z.string(),
  },
);

export type DeleteUserResponseBody2 = {
  success: boolean;
  error: DeleteUserError2;
};

export const DeleteUserResponseBody2$zodSchema: z.ZodType<
  DeleteUserResponseBody2
> = z.object({
  error: z.lazy(() => DeleteUserError2$zodSchema),
  success: z.boolean(),
});

export type DeleteUserPath1 = string | number;

export const DeleteUserPath1$zodSchema: z.ZodType<DeleteUserPath1> = z.union([
  z.string(),
  z.number(),
]);

export type DeleteUserIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const DeleteUserIssue1$zodSchema: z.ZodType<DeleteUserIssue1> = z.object(
  {
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  },
);

export type DeleteUserError1 = {
  issues: Array<DeleteUserIssue1>;
  name: string;
};

export const DeleteUserError1$zodSchema: z.ZodType<DeleteUserError1> = z.object(
  {
    issues: z.array(z.lazy(() => DeleteUserIssue1$zodSchema)),
    name: z.string(),
  },
);

export type DeleteUserResponseBody1 = {
  success: boolean;
  error: DeleteUserError1;
};

export const DeleteUserResponseBody1$zodSchema: z.ZodType<
  DeleteUserResponseBody1
> = z.object({
  error: z.lazy(() => DeleteUserError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type DeleteUserResponseBody =
  | DeleteUserResponseBody1
  | DeleteUserResponseBody2;

export const DeleteUserResponseBody$zodSchema: z.ZodType<
  DeleteUserResponseBody
> = z.union([
  z.lazy(() => DeleteUserResponseBody1$zodSchema),
  z.lazy(() => DeleteUserResponseBody2$zodSchema),
]).describe("The validation error(s)");

/**
 * Missing scope
 */
export type DeleteUserForbiddenResponseBody = {
  status_code: DeleteUserForbiddenStatusCode;
  type: DeleteUserForbiddenType;
  code: DeleteUserForbiddenCode;
  message: string;
};

export const DeleteUserForbiddenResponseBody$zodSchema: z.ZodType<
  DeleteUserForbiddenResponseBody
> = z.object({
  code: DeleteUserForbiddenCode$zodSchema,
  message: z.string(),
  status_code: DeleteUserForbiddenStatusCode$zodSchema,
  type: DeleteUserForbiddenType$zodSchema,
}).describe("Missing scope");

/**
 * Missing client ID
 */
export type DeleteUserBadRequestResponseBody = {
  status_code: DeleteUserStatusCode400;
  type: DeleteUserBadRequestType;
  code: DeleteUserCodeMissingClientID;
  message: string;
};

export const DeleteUserBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteUserBadRequestResponseBody
> = z.object({
  code: DeleteUserCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: DeleteUserStatusCode400$zodSchema,
  type: DeleteUserBadRequestType$zodSchema,
}).describe("Missing client ID");

export type DeleteUserResponse =
  | DeleteUserBadRequestResponseBody
  | AuthError
  | DeleteUserForbiddenResponseBody
  | NotFound
  | RateLimit
  | DeleteResponse
  | DeleteUserResponseBody1
  | DeleteUserResponseBody2;

export const DeleteUserResponse$zodSchema: z.ZodType<DeleteUserResponse> = z
  .union([
    z.lazy(() => DeleteUserBadRequestResponseBody$zodSchema),
    AuthError$zodSchema,
    z.lazy(() => DeleteUserForbiddenResponseBody$zodSchema),
    NotFound$zodSchema,
    RateLimit$zodSchema,
    DeleteResponse$zodSchema,
    z.union([
      z.lazy(() => DeleteUserResponseBody1$zodSchema),
      z.lazy(() => DeleteUserResponseBody2$zodSchema),
    ]),
  ]);
