/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { DeleteResponse, DeleteResponse$zodSchema } from "./deleteresponse.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type DeleteAccountantUserRequest = { id: string };

export const DeleteAccountantUserRequest$zodSchema: z.ZodType<
  DeleteAccountantUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export const DeleteAccountantUserStatusCode$zodSchema = z.literal(403);

export type DeleteAccountantUserStatusCode = z.infer<
  typeof DeleteAccountantUserStatusCode$zodSchema
>;

export const DeleteAccountantUserType$zodSchema = z.enum([
  "auth_error",
]);

export type DeleteAccountantUserType = z.infer<
  typeof DeleteAccountantUserType$zodSchema
>;

export const DeleteAccountantUserCode$zodSchema = z.enum([
  "missing_scope",
]);

export type DeleteAccountantUserCode = z.infer<
  typeof DeleteAccountantUserCode$zodSchema
>;

/**
 * Missing scope
 */
export type DeleteAccountantUserResponseBody = {
  status_code: DeleteAccountantUserStatusCode;
  type: DeleteAccountantUserType;
  code: DeleteAccountantUserCode;
  message: string;
};

export const DeleteAccountantUserResponseBody$zodSchema: z.ZodType<
  DeleteAccountantUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: DeleteAccountantUserCode$zodSchema,
  message: z.string(),
  status_code: DeleteAccountantUserStatusCode$zodSchema,
  type: DeleteAccountantUserType$zodSchema,
}).describe("Missing scope");

export type DeleteAccountantUserResponse =
  | AuthError
  | DeleteAccountantUserResponseBody
  | NotFound
  | Conflict
  | RateLimit
  | DeleteResponse;

export const DeleteAccountantUserResponse$zodSchema: z.ZodType<
  DeleteAccountantUserResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  AuthError$zodSchema,
  z.lazy(() => DeleteAccountantUserResponseBody$zodSchema),
  NotFound$zodSchema,
  Conflict$zodSchema,
  RateLimit$zodSchema,
  DeleteResponse$zodSchema,
]);
