/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { DeleteResponse, DeleteResponse$zodSchema } from "./deleteresponse.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type DeleteUserRequest = { id: string; xClientId: string };

export const DeleteUserRequest$zodSchema: z.ZodType<
  DeleteUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  xClientId: z.string(),
});

export type DeleteUserPath2 = string | number;

export const DeleteUserPath2$zodSchema: z.ZodType<
  DeleteUserPath2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type DeleteUserIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const DeleteUserIssue2$zodSchema: z.ZodType<
  DeleteUserIssue2,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type DeleteUserError2 = {
  issues: Array<DeleteUserIssue2>;
  name: string;
};

export const DeleteUserError2$zodSchema: z.ZodType<
  DeleteUserError2,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => DeleteUserIssue2$zodSchema)),
  name: z.string(),
});

export type DeleteUserResponseBody2 = {
  success: boolean;
  error: DeleteUserError2;
};

export const DeleteUserResponseBody2$zodSchema: z.ZodType<
  DeleteUserResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => DeleteUserError2$zodSchema),
  success: z.boolean(),
});

export type DeleteUserPath1 = string | number;

export const DeleteUserPath1$zodSchema: z.ZodType<
  DeleteUserPath1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type DeleteUserIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const DeleteUserIssue1$zodSchema: z.ZodType<
  DeleteUserIssue1,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type DeleteUserError1 = {
  issues: Array<DeleteUserIssue1>;
  name: string;
};

export const DeleteUserError1$zodSchema: z.ZodType<
  DeleteUserError1,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => DeleteUserIssue1$zodSchema)),
  name: z.string(),
});

export type DeleteUserResponseBody1 = {
  success: boolean;
  error: DeleteUserError1;
};

export const DeleteUserResponseBody1$zodSchema: z.ZodType<
  DeleteUserResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => DeleteUserError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type DeleteUserResponseBody =
  | DeleteUserResponseBody1
  | DeleteUserResponseBody2;

export const DeleteUserResponseBody$zodSchema: z.ZodType<
  DeleteUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteUserResponseBody1$zodSchema),
  z.lazy(() => DeleteUserResponseBody2$zodSchema),
]).describe("The validation error(s)");

export const DeleteUserForbiddenStatusCode$zodSchema = z.literal(403);

export type DeleteUserForbiddenStatusCode = z.infer<
  typeof DeleteUserForbiddenStatusCode$zodSchema
>;

export const DeleteUserForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type DeleteUserForbiddenType = z.infer<
  typeof DeleteUserForbiddenType$zodSchema
>;

export const DeleteUserForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type DeleteUserForbiddenCode = z.infer<
  typeof DeleteUserForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type DeleteUserForbiddenResponseBody = {
  status_code: DeleteUserForbiddenStatusCode;
  type: DeleteUserForbiddenType;
  code: DeleteUserForbiddenCode;
  message: string;
};

export const DeleteUserForbiddenResponseBody$zodSchema: z.ZodType<
  DeleteUserForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: DeleteUserForbiddenCode$zodSchema,
  message: z.string(),
  status_code: DeleteUserForbiddenStatusCode$zodSchema,
  type: DeleteUserForbiddenType$zodSchema,
}).describe("Missing scope");

export const DeleteUserStatusCode400$zodSchema = z.literal(400);

export type DeleteUserStatusCode400 = z.infer<
  typeof DeleteUserStatusCode400$zodSchema
>;

export const DeleteUserBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type DeleteUserBadRequestType = z.infer<
  typeof DeleteUserBadRequestType$zodSchema
>;

export const DeleteUserCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type DeleteUserCodeMissingClientID = z.infer<
  typeof DeleteUserCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type DeleteUserBadRequestResponseBody = {
  status_code: DeleteUserStatusCode400;
  type: DeleteUserBadRequestType;
  code: DeleteUserCodeMissingClientID;
  message: string;
};

export const DeleteUserBadRequestResponseBody$zodSchema: z.ZodType<
  DeleteUserBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: DeleteUserCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: DeleteUserStatusCode400$zodSchema,
  type: DeleteUserBadRequestType$zodSchema,
}).describe("Missing client ID");

export type DeleteUserResponse =
  | DeleteUserBadRequestResponseBody
  | AuthError
  | DeleteUserForbiddenResponseBody
  | NotFound
  | RateLimit
  | DeleteResponse
  | DeleteUserResponseBody1
  | DeleteUserResponseBody2;

export const DeleteUserResponse$zodSchema: z.ZodType<
  DeleteUserResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteUserBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => DeleteUserForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  RateLimit$zodSchema,
  DeleteResponse$zodSchema,
  z.union([
    z.lazy(() => DeleteUserResponseBody1$zodSchema),
    z.lazy(() => DeleteUserResponseBody2$zodSchema),
  ]),
]);
