/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FileCreateFile = { fileName: string; content: Uint8Array | string };

export const FileCreateFile$zodSchema: z.ZodType<
  FileCreateFile,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string().base64(),
  fileName: z.string(),
});

export type FileCreate = {
  workspaceId: string;
  file: FileCreateFile | Blob;
  labelIds?: Array<string> | undefined;
  name?: string | undefined;
  folderId?: string | undefined;
  taskId?: string | undefined;
};

export const FileCreate$zodSchema: z.ZodType<
  FileCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  file: z.lazy(() => FileCreateFile$zodSchema),
  folderId: z.string().optional(),
  labelIds: z.array(z.string()).optional(),
  name: z.string().optional(),
  taskId: z.string().optional(),
  workspaceId: z.string(),
});
