/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FileT = {
  id: string;
  documentDate: string | null;
  createdAt: string;
  updatedAt: string;
  name: string;
  mimetype: string;
  size: number;
  workspaceId: string;
  createdById: string | null;
  taskId: string | null;
  folderId: string | null;
  labelIds: Array<string> | null;
};

export const FileT$zodSchema: z.ZodType<FileT> = z.object({
  createdAt: z.iso.datetime({ offset: true }).describe(
    "The date and time of the creation for the file. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  createdById: z.string().nullable().describe("The ID of the creator"),
  documentDate: z.iso.datetime({ offset: true }).nullable().describe(
    "The date of the document (not the upload date)",
  ),
  folderId: z.string().nullable().describe(
    "The ID of the folder this file was uploaded to.",
  ),
  id: z.string().describe("The ID of the file"),
  labelIds: z.array(z.string()).nullable().describe(
    "The IDs of the assigned labels",
  ),
  mimetype: z.string().describe("The mime type of the file"),
  name: z.string().describe("The name of the file"),
  size: z.number().describe("The size of the file in bytes"),
  taskId: z.string().nullable().describe(
    "The ID of the task this file was uploaded to.",
  ),
  updatedAt: z.iso.datetime({ offset: true }).describe(
    "The date and time of the last update for the file. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  workspaceId: z.string().describe("The ID of the workspace"),
});
