/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FileUpdate = {
  name?: string | undefined;
  documentDate?: string | undefined;
  folderId?: string | undefined;
};

export const FileUpdate$zodSchema: z.ZodType<
  FileUpdate,
  z.ZodTypeDef,
  unknown
> = z.object({
  documentDate: z.string().optional(),
  folderId: z.string().optional(),
  name: z.string().optional(),
});
