/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FileT = {
  id: string;
  documentDate: string | null;
  createdAt: string;
  updatedAt: string;
  name: string;
  mimetype: string;
  size: number;
  workspaceId: string;
  createdById: string | null;
  taskId: string | null;
  folderId: string | null;
  labelIds: Array<string> | null;
};

export const FileT$zodSchema: z.ZodType<FileT, z.ZodTypeDef, unknown> = z
  .object({
    createdAt: z.string().datetime({ offset: true }),
    createdById: z.string().nullable(),
    documentDate: z.string().datetime({ offset: true }).nullable(),
    folderId: z.string().nullable(),
    id: z.string(),
    labelIds: z.array(z.string()).nullable(),
    mimetype: z.string(),
    name: z.string(),
    size: z.number(),
    taskId: z.string().nullable(),
    updatedAt: z.string().datetime({ offset: true }),
    workspaceId: z.string(),
  });
