/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AccountantUser, AccountantUser$zodSchema } from "./accountantuser.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const GetAccountantUserStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type GetAccountantUserStatusCode = ClosedEnum<
  typeof GetAccountantUserStatusCode
>;

export const GetAccountantUserStatusCode$zodSchema = z.literal(403);

export const GetAccountantUserType = {
  AuthError: "auth_error",
} as const;
export type GetAccountantUserType = ClosedEnum<typeof GetAccountantUserType>;

export const GetAccountantUserType$zodSchema = z.enum([
  "auth_error",
]);

export const GetAccountantUserCode = {
  MissingScope: "missing_scope",
} as const;
export type GetAccountantUserCode = ClosedEnum<typeof GetAccountantUserCode>;

export const GetAccountantUserCode$zodSchema = z.enum([
  "missing_scope",
]);

export type GetAccountantUserRequest = { id: string };

export const GetAccountantUserRequest$zodSchema: z.ZodType<
  GetAccountantUserRequest
> = z.object({
  id: z.string(),
});

export type GetAccountantUserPath = string | number;

export const GetAccountantUserPath$zodSchema: z.ZodType<GetAccountantUserPath> =
  z.union([
    z.string(),
    z.number(),
  ]);

export type GetAccountantUserIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const GetAccountantUserIssue$zodSchema: z.ZodType<
  GetAccountantUserIssue
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type GetAccountantUserError = {
  issues: Array<GetAccountantUserIssue>;
  name: string;
};

export const GetAccountantUserError$zodSchema: z.ZodType<
  GetAccountantUserError
> = z.object({
  issues: z.array(z.lazy(() => GetAccountantUserIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type GetAccountantUserUnprocessableEntityResponseBody = {
  success: boolean;
  error: GetAccountantUserError;
};

export const GetAccountantUserUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<GetAccountantUserUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() => GetAccountantUserError$zodSchema),
    success: z.boolean(),
  }).describe("The validation error(s)");

/**
 * Missing scope
 */
export type GetAccountantUserForbiddenResponseBody = {
  status_code: GetAccountantUserStatusCode;
  type: GetAccountantUserType;
  code: GetAccountantUserCode;
  message: string;
};

export const GetAccountantUserForbiddenResponseBody$zodSchema: z.ZodType<
  GetAccountantUserForbiddenResponseBody
> = z.object({
  code: GetAccountantUserCode$zodSchema,
  message: z.string(),
  status_code: GetAccountantUserStatusCode$zodSchema,
  type: GetAccountantUserType$zodSchema,
}).describe("Missing scope");

export type GetAccountantUserResponse =
  | AccountantUser
  | AuthError
  | GetAccountantUserForbiddenResponseBody
  | NotFound
  | RateLimit
  | InternalError
  | GetAccountantUserUnprocessableEntityResponseBody;

export const GetAccountantUserResponse$zodSchema: z.ZodType<
  GetAccountantUserResponse
> = z.union([
  AccountantUser$zodSchema,
  AuthError$zodSchema,
  z.lazy(() => GetAccountantUserForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  RateLimit$zodSchema,
  InternalError$zodSchema,
  z.lazy(() => GetAccountantUserUnprocessableEntityResponseBody$zodSchema),
]);
