/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  CollectSessionByToken,
  CollectSessionByToken$zodSchema,
} from "./collectsessionbytoken.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type GetcollectSessionByTokenRequest = { token: string };

export const GetcollectSessionByTokenRequest$zodSchema: z.ZodType<
  GetcollectSessionByTokenRequest
> = z.object({
  token: z.string(),
});

export type GetcollectSessionByTokenPath = string | number;

export const GetcollectSessionByTokenPath$zodSchema: z.ZodType<
  GetcollectSessionByTokenPath
> = z.union([
  z.string(),
  z.number(),
]);

export type GetcollectSessionByTokenIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const GetcollectSessionByTokenIssue$zodSchema: z.ZodType<
  GetcollectSessionByTokenIssue
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type GetcollectSessionByTokenError = {
  issues: Array<GetcollectSessionByTokenIssue>;
  name: string;
};

export const GetcollectSessionByTokenError$zodSchema: z.ZodType<
  GetcollectSessionByTokenError
> = z.object({
  issues: z.array(z.lazy(() => GetcollectSessionByTokenIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type GetcollectSessionByTokenUnprocessableEntityResponseBody = {
  success: boolean;
  error: GetcollectSessionByTokenError;
};

export const GetcollectSessionByTokenUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<GetcollectSessionByTokenUnprocessableEntityResponseBody> = z.object(
    {
      error: z.lazy(() => GetcollectSessionByTokenError$zodSchema),
      success: z.boolean(),
    },
  ).describe("The validation error(s)");

export const GetcollectSessionByTokenStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type GetcollectSessionByTokenStatusCode = ClosedEnum<
  typeof GetcollectSessionByTokenStatusCode
>;

export const GetcollectSessionByTokenStatusCode$zodSchema = z.literal(404);

export const GetcollectSessionByTokenType = {
  NotFound: "not_found",
} as const;
export type GetcollectSessionByTokenType = ClosedEnum<
  typeof GetcollectSessionByTokenType
>;

export const GetcollectSessionByTokenType$zodSchema = z.enum([
  "not_found",
]);

export const GetcollectSessionByTokenCode = {
  CollectTokenNotFound: "collect_token_not_found",
} as const;
export type GetcollectSessionByTokenCode = ClosedEnum<
  typeof GetcollectSessionByTokenCode
>;

export const GetcollectSessionByTokenCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type GetcollectSessionByTokenNotFoundResponseBody = {
  status_code: GetcollectSessionByTokenStatusCode;
  type: GetcollectSessionByTokenType;
  code: GetcollectSessionByTokenCode;
  message: string;
};

export const GetcollectSessionByTokenNotFoundResponseBody$zodSchema: z.ZodType<
  GetcollectSessionByTokenNotFoundResponseBody
> = z.object({
  code: GetcollectSessionByTokenCode$zodSchema,
  message: z.string(),
  status_code: GetcollectSessionByTokenStatusCode$zodSchema,
  type: GetcollectSessionByTokenType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

export type GetcollectSessionByTokenResponse =
  | CollectSessionByToken
  | GetcollectSessionByTokenNotFoundResponseBody
  | BadRequest
  | RateLimit
  | GetcollectSessionByTokenUnprocessableEntityResponseBody;

export const GetcollectSessionByTokenResponse$zodSchema: z.ZodType<
  GetcollectSessionByTokenResponse
> = z.union([
  CollectSessionByToken$zodSchema,
  z.lazy(() => GetcollectSessionByTokenNotFoundResponseBody$zodSchema),
  BadRequest$zodSchema,
  RateLimit$zodSchema,
  z.lazy(() =>
    GetcollectSessionByTokenUnprocessableEntityResponseBody$zodSchema
  ),
]);
