/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Task, Task$zodSchema } from "./task.js";

export type GetTaskRequest = { id: string };

export const GetTaskRequest$zodSchema: z.ZodType<
  GetTaskRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

export type GetTaskPath = string | number;

export const GetTaskPath$zodSchema: z.ZodType<
  GetTaskPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type GetTaskIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const GetTaskIssue$zodSchema: z.ZodType<
  GetTaskIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type GetTaskError = { issues: Array<GetTaskIssue>; name: string };

export const GetTaskError$zodSchema: z.ZodType<
  GetTaskError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => GetTaskIssue$zodSchema)),
  name: z.string(),
});

/**
 * Invalid id error
 */
export type GetTaskUnprocessableEntityResponseBody = {
  success: boolean;
  error: GetTaskError;
};

export const GetTaskUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  GetTaskUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => GetTaskError$zodSchema),
  success: z.boolean(),
}).describe("Invalid id error");

/**
 * Task not found
 */
export type GetTaskNotFoundResponseBody = { message: string };

export const GetTaskNotFoundResponseBody$zodSchema: z.ZodType<
  GetTaskNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("Task not found");

export type GetTaskResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  Task?: Task | undefined;
  fourHundredAndFourApplicationJsonObject?:
    | GetTaskNotFoundResponseBody
    | undefined;
  fourHundredAndTwentyTwoApplicationJsonObject?:
    | GetTaskUnprocessableEntityResponseBody
    | undefined;
};

export const GetTaskResponse$zodSchema: z.ZodType<
  GetTaskResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  Task: Task$zodSchema.optional(),
  fourHundredAndFourApplicationJsonObject: z.lazy(() =>
    GetTaskNotFoundResponseBody$zodSchema
  ).optional(),
  fourHundredAndTwentyTwoApplicationJsonObject: z.lazy(() =>
    GetTaskUnprocessableEntityResponseBody$zodSchema
  ).optional(),
});
