/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { ClientUser, ClientUser$zodSchema } from "./clientuser.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type GetUserRequest = { id: string; xClientId: string };

export const GetUserRequest$zodSchema: z.ZodType<
  GetUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  xClientId: z.string(),
});

export type GetUserPath2 = string | number;

export const GetUserPath2$zodSchema: z.ZodType<
  GetUserPath2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type GetUserIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const GetUserIssue2$zodSchema: z.ZodType<
  GetUserIssue2,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type GetUserError2 = { issues: Array<GetUserIssue2>; name: string };

export const GetUserError2$zodSchema: z.ZodType<
  GetUserError2,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => GetUserIssue2$zodSchema)),
  name: z.string(),
});

export type GetUserResponseBody2 = { success: boolean; error: GetUserError2 };

export const GetUserResponseBody2$zodSchema: z.ZodType<
  GetUserResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => GetUserError2$zodSchema),
  success: z.boolean(),
});

export type GetUserPath1 = string | number;

export const GetUserPath1$zodSchema: z.ZodType<
  GetUserPath1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type GetUserIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const GetUserIssue1$zodSchema: z.ZodType<
  GetUserIssue1,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type GetUserError1 = { issues: Array<GetUserIssue1>; name: string };

export const GetUserError1$zodSchema: z.ZodType<
  GetUserError1,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => GetUserIssue1$zodSchema)),
  name: z.string(),
});

export type GetUserResponseBody1 = { success: boolean; error: GetUserError1 };

export const GetUserResponseBody1$zodSchema: z.ZodType<
  GetUserResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => GetUserError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type GetUserResponseBody = GetUserResponseBody1 | GetUserResponseBody2;

export const GetUserResponseBody$zodSchema: z.ZodType<
  GetUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetUserResponseBody1$zodSchema),
  z.lazy(() => GetUserResponseBody2$zodSchema),
]).describe("The validation error(s)");

export const GetUserForbiddenStatusCode$zodSchema = z.literal(403);

export type GetUserForbiddenStatusCode = z.infer<
  typeof GetUserForbiddenStatusCode$zodSchema
>;

export const GetUserForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type GetUserForbiddenType = z.infer<
  typeof GetUserForbiddenType$zodSchema
>;

export const GetUserForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type GetUserForbiddenCode = z.infer<
  typeof GetUserForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type GetUserForbiddenResponseBody = {
  status_code: GetUserForbiddenStatusCode;
  type: GetUserForbiddenType;
  code: GetUserForbiddenCode;
  message: string;
};

export const GetUserForbiddenResponseBody$zodSchema: z.ZodType<
  GetUserForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: GetUserForbiddenCode$zodSchema,
  message: z.string(),
  status_code: GetUserForbiddenStatusCode$zodSchema,
  type: GetUserForbiddenType$zodSchema,
}).describe("Missing scope");

export const GetUserStatusCode400$zodSchema = z.literal(400);

export type GetUserStatusCode400 = z.infer<
  typeof GetUserStatusCode400$zodSchema
>;

export const GetUserBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type GetUserBadRequestType = z.infer<
  typeof GetUserBadRequestType$zodSchema
>;

export const GetUserCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type GetUserCodeMissingClientID = z.infer<
  typeof GetUserCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type GetUserBadRequestResponseBody = {
  status_code: GetUserStatusCode400;
  type: GetUserBadRequestType;
  code: GetUserCodeMissingClientID;
  message: string;
};

export const GetUserBadRequestResponseBody$zodSchema: z.ZodType<
  GetUserBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: GetUserCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: GetUserStatusCode400$zodSchema,
  type: GetUserBadRequestType$zodSchema,
}).describe("Missing client ID");

export type GetUserResponse =
  | ClientUser
  | GetUserBadRequestResponseBody
  | AuthError
  | GetUserForbiddenResponseBody
  | NotFound
  | RateLimit
  | GetUserResponseBody1
  | GetUserResponseBody2;

export const GetUserResponse$zodSchema: z.ZodType<
  GetUserResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ClientUser$zodSchema,
  z.lazy(() => GetUserBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => GetUserForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  RateLimit$zodSchema,
  z.union([
    z.lazy(() => GetUserResponseBody1$zodSchema),
    z.lazy(() => GetUserResponseBody2$zodSchema),
  ]),
]);
