/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Steuerboard API Index
 */
export type GetV1ResponseBody = { message: string };

export const GetV1ResponseBody$zodSchema: z.ZodType<
  GetV1ResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("Steuerboard API Index");

export type GetV1Response = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: GetV1ResponseBody | undefined;
};

export const GetV1Response$zodSchema: z.ZodType<
  GetV1Response,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => GetV1ResponseBody$zodSchema).optional(),
});
