/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Workspace, Workspace$zodSchema } from "./workspace.js";

export type GetWorkspaceRequest = { id: string; xClientId: string };

export const GetWorkspaceRequest$zodSchema: z.ZodType<
  GetWorkspaceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  xClientId: z.string(),
});

export type GetWorkspacePath = string | number;

export const GetWorkspacePath$zodSchema: z.ZodType<
  GetWorkspacePath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type GetWorkspaceIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const GetWorkspaceIssue$zodSchema: z.ZodType<
  GetWorkspaceIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type GetWorkspaceError = {
  issues: Array<GetWorkspaceIssue>;
  name: string;
};

export const GetWorkspaceError$zodSchema: z.ZodType<
  GetWorkspaceError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => GetWorkspaceIssue$zodSchema)),
  name: z.string(),
});

/**
 * Invalid id error
 */
export type GetWorkspaceUnprocessableEntityResponseBody = {
  success: boolean;
  error: GetWorkspaceError;
};

export const GetWorkspaceUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  GetWorkspaceUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => GetWorkspaceError$zodSchema),
  success: z.boolean(),
}).describe("Invalid id error");

export const GetWorkspaceForbiddenStatusCode$zodSchema = z.literal(403);

export type GetWorkspaceForbiddenStatusCode = z.infer<
  typeof GetWorkspaceForbiddenStatusCode$zodSchema
>;

export const GetWorkspaceForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type GetWorkspaceForbiddenType = z.infer<
  typeof GetWorkspaceForbiddenType$zodSchema
>;

export const GetWorkspaceForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type GetWorkspaceForbiddenCode = z.infer<
  typeof GetWorkspaceForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type GetWorkspaceForbiddenResponseBody = {
  status_code: GetWorkspaceForbiddenStatusCode;
  type: GetWorkspaceForbiddenType;
  code: GetWorkspaceForbiddenCode;
  message: string;
};

export const GetWorkspaceForbiddenResponseBody$zodSchema: z.ZodType<
  GetWorkspaceForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: GetWorkspaceForbiddenCode$zodSchema,
  message: z.string(),
  status_code: GetWorkspaceForbiddenStatusCode$zodSchema,
  type: GetWorkspaceForbiddenType$zodSchema,
}).describe("Missing scope");

export const GetWorkspaceStatusCode400$zodSchema = z.literal(400);

export type GetWorkspaceStatusCode400 = z.infer<
  typeof GetWorkspaceStatusCode400$zodSchema
>;

export const GetWorkspaceBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type GetWorkspaceBadRequestType = z.infer<
  typeof GetWorkspaceBadRequestType$zodSchema
>;

export const GetWorkspaceCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type GetWorkspaceCodeMissingClientID = z.infer<
  typeof GetWorkspaceCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type GetWorkspaceBadRequestResponseBody = {
  status_code: GetWorkspaceStatusCode400;
  type: GetWorkspaceBadRequestType;
  code: GetWorkspaceCodeMissingClientID;
  message: string;
};

export const GetWorkspaceBadRequestResponseBody$zodSchema: z.ZodType<
  GetWorkspaceBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: GetWorkspaceCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: GetWorkspaceStatusCode400$zodSchema,
  type: GetWorkspaceBadRequestType$zodSchema,
}).describe("Missing client ID");

export type GetWorkspaceResponse =
  | Workspace
  | GetWorkspaceBadRequestResponseBody
  | AuthError
  | GetWorkspaceForbiddenResponseBody
  | NotFound
  | RateLimit
  | GetWorkspaceUnprocessableEntityResponseBody;

export const GetWorkspaceResponse$zodSchema: z.ZodType<
  GetWorkspaceResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  Workspace$zodSchema,
  z.lazy(() => GetWorkspaceBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => GetWorkspaceForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  RateLimit$zodSchema,
  z.lazy(() => GetWorkspaceUnprocessableEntityResponseBody$zodSchema),
]);
