/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * Health Check Response
 */
export type HealthResponseBody = { status: string; timestamp: string };

export const HealthResponseBody$zodSchema: z.ZodType<
  HealthResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: z.string(),
  timestamp: z.string(),
}).describe("Health Check Response");

export type HealthResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: HealthResponseBody | undefined;
  rate_limit?: RateLimit | undefined;
};

export const HealthResponse$zodSchema: z.ZodType<
  HealthResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => HealthResponseBody$zodSchema).optional(),
  rate_limit: RateLimit$zodSchema.optional(),
});
