/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * Steuerboard API Index
 */
export type IndexResponseBody = { message: string };

export const IndexResponseBody$zodSchema: z.ZodType<
  IndexResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("Steuerboard API Index");

export type IndexResponse = RateLimit | IndexResponseBody;

export const IndexResponse$zodSchema: z.ZodType<
  IndexResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  RateLimit$zodSchema,
  z.lazy(() => IndexResponseBody$zodSchema),
]);
