/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * Steuerboard API Index
 */
export type IndexResponseBody = { message: string };

export const IndexResponseBody$zodSchema: z.ZodType<
  IndexResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
}).describe("Steuerboard API Index");

export type IndexResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: IndexResponseBody | undefined;
  rate_limit?: RateLimit | undefined;
};

export const IndexResponse$zodSchema: z.ZodType<
  IndexResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  object: z.lazy(() => IndexResponseBody$zodSchema).optional(),
  rate_limit: RateLimit$zodSchema.optional(),
});
