/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InviteAccountantUser = { email: string; roleId: string };

export const InviteAccountantUser$zodSchema: z.ZodType<
  InviteAccountantUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string(),
  roleId: z.string(),
});
