/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { ClientUser, ClientUser$zodSchema } from "./clientuser.js";
import {
  ClientUserInvite,
  ClientUserInvite$zodSchema,
} from "./clientuserinvite.js";
import { Conflict, Conflict$zodSchema } from "./conflict.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type InviteUserRequest = {
  xClientId: string;
  ClientUserInvite: ClientUserInvite;
};

export const InviteUserRequest$zodSchema: z.ZodType<
  InviteUserRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ClientUserInvite: ClientUserInvite$zodSchema,
  xClientId: z.string(),
});

export type InviteUserPath = string | number;

export const InviteUserPath$zodSchema: z.ZodType<
  InviteUserPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type InviteUserIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const InviteUserIssue$zodSchema: z.ZodType<
  InviteUserIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type InviteUserError = { issues: Array<InviteUserIssue>; name: string };

export const InviteUserError$zodSchema: z.ZodType<
  InviteUserError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => InviteUserIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type InviteUserUnprocessableEntityResponseBody = {
  success: boolean;
  error: InviteUserError;
};

export const InviteUserUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  InviteUserUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => InviteUserError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const InviteUserForbiddenStatusCode$zodSchema = z.literal(403);

export type InviteUserForbiddenStatusCode = z.infer<
  typeof InviteUserForbiddenStatusCode$zodSchema
>;

export const InviteUserForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type InviteUserForbiddenType = z.infer<
  typeof InviteUserForbiddenType$zodSchema
>;

export const InviteUserForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type InviteUserForbiddenCode = z.infer<
  typeof InviteUserForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type InviteUserForbiddenResponseBody = {
  status_code: InviteUserForbiddenStatusCode;
  type: InviteUserForbiddenType;
  code: InviteUserForbiddenCode;
  message: string;
};

export const InviteUserForbiddenResponseBody$zodSchema: z.ZodType<
  InviteUserForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: InviteUserForbiddenCode$zodSchema,
  message: z.string(),
  status_code: InviteUserForbiddenStatusCode$zodSchema,
  type: InviteUserForbiddenType$zodSchema,
}).describe("Missing scope");

export const InviteUserStatusCode400$zodSchema = z.literal(400);

export type InviteUserStatusCode400 = z.infer<
  typeof InviteUserStatusCode400$zodSchema
>;

export const InviteUserBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type InviteUserBadRequestType = z.infer<
  typeof InviteUserBadRequestType$zodSchema
>;

export const InviteUserCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type InviteUserCodeMissingClientID = z.infer<
  typeof InviteUserCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type InviteUserBadRequestResponseBody = {
  status_code: InviteUserStatusCode400;
  type: InviteUserBadRequestType;
  code: InviteUserCodeMissingClientID;
  message: string;
};

export const InviteUserBadRequestResponseBody$zodSchema: z.ZodType<
  InviteUserBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: InviteUserCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: InviteUserStatusCode400$zodSchema,
  type: InviteUserBadRequestType$zodSchema,
}).describe("Missing client ID");

export type InviteUserResponse =
  | ClientUser
  | InviteUserBadRequestResponseBody
  | AuthError
  | InviteUserForbiddenResponseBody
  | NotFound
  | Conflict
  | RateLimit
  | InviteUserUnprocessableEntityResponseBody;

export const InviteUserResponse$zodSchema: z.ZodType<
  InviteUserResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  ClientUser$zodSchema,
  z.lazy(() => InviteUserBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => InviteUserForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  Conflict$zodSchema,
  RateLimit$zodSchema,
  z.lazy(() => InviteUserUnprocessableEntityResponseBody$zodSchema),
]);
