/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { PaginatedTasks, PaginatedTasks$zodSchema } from "./paginatedtasks.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * The sort field of the results
 */
export const ListTasksSort$zodSchema = z.enum([
  "createdAt",
  "updatedAt",
  "dueDate",
  "status",
  "title",
]).describe("The sort field of the results");

export type ListTasksSort = z.infer<typeof ListTasksSort$zodSchema>;

/**
 * The order of the results based on the sort field
 */
export const ListTasksOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("The order of the results based on the sort field");

export type ListTasksOrder = z.infer<typeof ListTasksOrder$zodSchema>;

export type ListTasksRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  workspaceId?: string | undefined;
  parentId?: string | undefined;
  sort?: ListTasksSort | undefined;
  order?: ListTasksOrder | undefined;
  xClientId: string;
};

export const ListTasksRequest$zodSchema: z.ZodType<
  ListTasksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  limit: z.number().default(20),
  order: ListTasksOrder$zodSchema.default("desc"),
  parentId: z.string().optional(),
  sort: ListTasksSort$zodSchema.default("createdAt"),
  workspaceId: z.string().optional(),
  xClientId: z.string(),
});

export type ListTasksPath = string | number;

export const ListTasksPath$zodSchema: z.ZodType<
  ListTasksPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type ListTasksIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListTasksIssue$zodSchema: z.ZodType<
  ListTasksIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type ListTasksError = { issues: Array<ListTasksIssue>; name: string };

export const ListTasksError$zodSchema: z.ZodType<
  ListTasksError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => ListTasksIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type ListTasksUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListTasksError;
};

export const ListTasksUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  ListTasksUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => ListTasksError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const ListTasksForbiddenStatusCode$zodSchema = z.literal(403);

export type ListTasksForbiddenStatusCode = z.infer<
  typeof ListTasksForbiddenStatusCode$zodSchema
>;

export const ListTasksForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type ListTasksForbiddenType = z.infer<
  typeof ListTasksForbiddenType$zodSchema
>;

export const ListTasksForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type ListTasksForbiddenCode = z.infer<
  typeof ListTasksForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type ListTasksForbiddenResponseBody = {
  status_code: ListTasksForbiddenStatusCode;
  type: ListTasksForbiddenType;
  code: ListTasksForbiddenCode;
  message: string;
};

export const ListTasksForbiddenResponseBody$zodSchema: z.ZodType<
  ListTasksForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListTasksForbiddenCode$zodSchema,
  message: z.string(),
  status_code: ListTasksForbiddenStatusCode$zodSchema,
  type: ListTasksForbiddenType$zodSchema,
}).describe("Missing scope");

export const ListTasksStatusCode400$zodSchema = z.literal(400);

export type ListTasksStatusCode400 = z.infer<
  typeof ListTasksStatusCode400$zodSchema
>;

export const ListTasksBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type ListTasksBadRequestType = z.infer<
  typeof ListTasksBadRequestType$zodSchema
>;

export const ListTasksCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type ListTasksCodeMissingClientID = z.infer<
  typeof ListTasksCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type ListTasksBadRequestResponseBody = {
  status_code: ListTasksStatusCode400;
  type: ListTasksBadRequestType;
  code: ListTasksCodeMissingClientID;
  message: string;
};

export const ListTasksBadRequestResponseBody$zodSchema: z.ZodType<
  ListTasksBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListTasksCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: ListTasksStatusCode400$zodSchema,
  type: ListTasksBadRequestType$zodSchema,
}).describe("Missing client ID");

export type ListTasksResponse =
  | ListTasksBadRequestResponseBody
  | AuthError
  | ListTasksForbiddenResponseBody
  | RateLimit
  | PaginatedTasks
  | ListTasksUnprocessableEntityResponseBody;

export const ListTasksResponse$zodSchema: z.ZodType<
  ListTasksResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListTasksBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => ListTasksForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  PaginatedTasks$zodSchema,
  z.lazy(() => ListTasksUnprocessableEntityResponseBody$zodSchema),
]);
