/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import {
  PaginatedClients,
  PaginatedClients$zodSchema,
} from "./paginatedclients.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * Include archived clients
 */
export const Archived = {
  True: "true",
  False: "false",
} as const;
/**
 * Include archived clients
 */
export type Archived = ClosedEnum<typeof Archived>;

export const Archived$zodSchema = z.enum([
  "true",
  "false",
]).describe("Include archived clients");

/**
 * The type of the client. 'natural_person' for individuals, 'legal_person' for companies like UG, GmbH, AG, Ltd., Inc., etc. and 'individual_enterprise' for sole proprietorships.
 */
export const ListClientsClientType = {
  NaturalPerson: "natural_person",
  IndividualEnterprise: "individual_enterprise",
  LegalPerson: "legal_person",
} as const;
/**
 * The type of the client. 'natural_person' for individuals, 'legal_person' for companies like UG, GmbH, AG, Ltd., Inc., etc. and 'individual_enterprise' for sole proprietorships.
 */
export type ListClientsClientType = ClosedEnum<typeof ListClientsClientType>;

export const ListClientsClientType$zodSchema = z.enum([
  "natural_person",
  "individual_enterprise",
  "legal_person",
]).describe(
  "The type of the client. 'natural_person' for individuals, 'legal_person' for companies like UG, GmbH, AG, Ltd., Inc., etc. and 'individual_enterprise' for sole proprietorships.",
);

/**
 * The sort field of the results
 */
export const ListClientsSort = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  ArchivedAt: "archivedAt",
  Name: "name",
  CustomId: "customId",
} as const;
/**
 * The sort field of the results
 */
export type ListClientsSort = ClosedEnum<typeof ListClientsSort>;

export const ListClientsSort$zodSchema = z.enum([
  "createdAt",
  "updatedAt",
  "archivedAt",
  "name",
  "customId",
]).describe("The sort field of the results");

/**
 * The order of the results based on the sort field
 */
export const ListClientsOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order of the results based on the sort field
 */
export type ListClientsOrder = ClosedEnum<typeof ListClientsOrder>;

export const ListClientsOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("The order of the results based on the sort field");

export const ListClientsStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type ListClientsStatusCode = ClosedEnum<typeof ListClientsStatusCode>;

export const ListClientsStatusCode$zodSchema = z.literal(403);

export const ListClientsType = {
  AuthError: "auth_error",
} as const;
export type ListClientsType = ClosedEnum<typeof ListClientsType>;

export const ListClientsType$zodSchema = z.enum([
  "auth_error",
]);

export const ListClientsCode = {
  MissingScope: "missing_scope",
} as const;
export type ListClientsCode = ClosedEnum<typeof ListClientsCode>;

export const ListClientsCode$zodSchema = z.enum([
  "missing_scope",
]);

export type ListClientsRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  customId?: string | undefined;
  slug?: string | undefined;
  archived?: Archived | undefined;
  type?: ListClientsClientType | undefined;
  sort?: ListClientsSort | undefined;
  order?: ListClientsOrder | undefined;
};

export const ListClientsRequest$zodSchema: z.ZodType<ListClientsRequest> = z
  .object({
    archived: Archived$zodSchema.default("false").describe(
      "Include archived clients",
    ),
    cursor: z.string().optional(),
    customId: z.string().optional(),
    limit: z.number().default(20),
    order: ListClientsOrder$zodSchema.default("desc").describe(
      "The order of the results based on the sort field",
    ),
    slug: z.string().optional(),
    sort: ListClientsSort$zodSchema.default("createdAt").describe(
      "The sort field of the results",
    ),
    type: ListClientsClientType$zodSchema.optional().describe(
      "The type of the client. 'natural_person' for individuals, 'legal_person' for companies like UG, GmbH, AG, Ltd., Inc., etc. and 'individual_enterprise' for sole proprietorships.",
    ),
  });

export type ListClientsPath = string | number;

export const ListClientsPath$zodSchema: z.ZodType<ListClientsPath> = z.union([
  z.string(),
  z.number(),
]);

export type ListClientsIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListClientsIssue$zodSchema: z.ZodType<ListClientsIssue> = z.object(
  {
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  },
);

export type ListClientsError = {
  issues: Array<ListClientsIssue>;
  name: string;
};

export const ListClientsError$zodSchema: z.ZodType<ListClientsError> = z.object(
  {
    issues: z.array(z.lazy(() => ListClientsIssue$zodSchema)),
    name: z.string(),
  },
);

/**
 * The validation error(s)
 */
export type ListClientsUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListClientsError;
};

export const ListClientsUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  ListClientsUnprocessableEntityResponseBody
> = z.object({
  error: z.lazy(() => ListClientsError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

/**
 * Missing scope
 */
export type ListClientsForbiddenResponseBody = {
  status_code: ListClientsStatusCode;
  type: ListClientsType;
  code: ListClientsCode;
  message: string;
};

export const ListClientsForbiddenResponseBody$zodSchema: z.ZodType<
  ListClientsForbiddenResponseBody
> = z.object({
  code: ListClientsCode$zodSchema,
  message: z.string(),
  status_code: ListClientsStatusCode$zodSchema,
  type: ListClientsType$zodSchema,
}).describe("Missing scope");

export type ListClientsResponse =
  | AuthError
  | ListClientsForbiddenResponseBody
  | RateLimit
  | PaginatedClients
  | ListClientsUnprocessableEntityResponseBody;

export const ListClientsResponse$zodSchema: z.ZodType<ListClientsResponse> = z
  .union([
    AuthError$zodSchema,
    z.lazy(() => ListClientsForbiddenResponseBody$zodSchema),
    RateLimit$zodSchema,
    PaginatedClients$zodSchema,
    z.lazy(() => ListClientsUnprocessableEntityResponseBody$zodSchema),
  ]);
