/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import {
  PaginatedWorkspaces,
  PaginatedWorkspaces$zodSchema,
} from "./paginatedworkspaces.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const ListWorkspacesForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type ListWorkspacesForbiddenStatusCode = ClosedEnum<
  typeof ListWorkspacesForbiddenStatusCode
>;

export const ListWorkspacesForbiddenStatusCode$zodSchema = z.literal(403);

export const ListWorkspacesForbiddenType = {
  AuthError: "auth_error",
} as const;
export type ListWorkspacesForbiddenType = ClosedEnum<
  typeof ListWorkspacesForbiddenType
>;

export const ListWorkspacesForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const ListWorkspacesForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type ListWorkspacesForbiddenCode = ClosedEnum<
  typeof ListWorkspacesForbiddenCode
>;

export const ListWorkspacesForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export const ListWorkspacesStatusCode400 = {
  FourHundred: 400,
} as const;
export type ListWorkspacesStatusCode400 = ClosedEnum<
  typeof ListWorkspacesStatusCode400
>;

export const ListWorkspacesStatusCode400$zodSchema = z.literal(400);

export const ListWorkspacesBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type ListWorkspacesBadRequestType = ClosedEnum<
  typeof ListWorkspacesBadRequestType
>;

export const ListWorkspacesBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const ListWorkspacesCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type ListWorkspacesCodeMissingClientID = ClosedEnum<
  typeof ListWorkspacesCodeMissingClientID
>;

export const ListWorkspacesCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type ListWorkspacesRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  xClientId: string;
};

export const ListWorkspacesRequest$zodSchema: z.ZodType<ListWorkspacesRequest> =
  z.object({
    cursor: z.string().optional(),
    limit: z.number().default(20),
    xClientId: z.string(),
  });

export type ListWorkspacesPath = string | number;

export const ListWorkspacesPath$zodSchema: z.ZodType<ListWorkspacesPath> = z
  .union([
    z.string(),
    z.number(),
  ]);

export type ListWorkspacesIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListWorkspacesIssue$zodSchema: z.ZodType<ListWorkspacesIssue> = z
  .object({
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  });

export type ListWorkspacesError = {
  issues: Array<ListWorkspacesIssue>;
  name: string;
};

export const ListWorkspacesError$zodSchema: z.ZodType<ListWorkspacesError> = z
  .object({
    issues: z.array(z.lazy(() => ListWorkspacesIssue$zodSchema)),
    name: z.string(),
  });

/**
 * The validation error(s)
 */
export type ListWorkspacesUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListWorkspacesError;
};

export const ListWorkspacesUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  ListWorkspacesUnprocessableEntityResponseBody
> = z.object({
  error: z.lazy(() => ListWorkspacesError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

/**
 * Missing scope
 */
export type ListWorkspacesForbiddenResponseBody = {
  status_code: ListWorkspacesForbiddenStatusCode;
  type: ListWorkspacesForbiddenType;
  code: ListWorkspacesForbiddenCode;
  message: string;
};

export const ListWorkspacesForbiddenResponseBody$zodSchema: z.ZodType<
  ListWorkspacesForbiddenResponseBody
> = z.object({
  code: ListWorkspacesForbiddenCode$zodSchema,
  message: z.string(),
  status_code: ListWorkspacesForbiddenStatusCode$zodSchema,
  type: ListWorkspacesForbiddenType$zodSchema,
}).describe("Missing scope");

/**
 * Missing client ID
 */
export type ListWorkspacesBadRequestResponseBody = {
  status_code: ListWorkspacesStatusCode400;
  type: ListWorkspacesBadRequestType;
  code: ListWorkspacesCodeMissingClientID;
  message: string;
};

export const ListWorkspacesBadRequestResponseBody$zodSchema: z.ZodType<
  ListWorkspacesBadRequestResponseBody
> = z.object({
  code: ListWorkspacesCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: ListWorkspacesStatusCode400$zodSchema,
  type: ListWorkspacesBadRequestType$zodSchema,
}).describe("Missing client ID");

export type ListWorkspacesResponse =
  | ListWorkspacesBadRequestResponseBody
  | AuthError
  | ListWorkspacesForbiddenResponseBody
  | RateLimit
  | PaginatedWorkspaces
  | ListWorkspacesUnprocessableEntityResponseBody;

export const ListWorkspacesResponse$zodSchema: z.ZodType<
  ListWorkspacesResponse
> = z.union([
  z.lazy(() => ListWorkspacesBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => ListWorkspacesForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  PaginatedWorkspaces$zodSchema,
  z.lazy(() => ListWorkspacesUnprocessableEntityResponseBody$zodSchema),
]);
