/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AccountantUser, AccountantUser$zodSchema } from "./accountantuser.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * The sort field of the results
 */
export const ListAccountantUsersSort = {
  CreatedAt: "createdAt",
  UpdatedAt: "updatedAt",
  Email: "email",
  FirstName: "firstName",
  LastName: "lastName",
} as const;
/**
 * The sort field of the results
 */
export type ListAccountantUsersSort = ClosedEnum<
  typeof ListAccountantUsersSort
>;

export const ListAccountantUsersSort$zodSchema = z.enum([
  "createdAt",
  "updatedAt",
  "email",
  "firstName",
  "lastName",
]).describe("The sort field of the results");

/**
 * The order of the results based on the sort field
 */
export const ListAccountantUsersOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * The order of the results based on the sort field
 */
export type ListAccountantUsersOrder = ClosedEnum<
  typeof ListAccountantUsersOrder
>;

export const ListAccountantUsersOrder$zodSchema = z.enum([
  "asc",
  "desc",
]).describe("The order of the results based on the sort field");

export type ListAccountantUsersRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  sort?: ListAccountantUsersSort | undefined;
  order?: ListAccountantUsersOrder | undefined;
};

export const ListAccountantUsersRequest$zodSchema: z.ZodType<
  ListAccountantUsersRequest
> = z.object({
  cursor: z.string().optional(),
  limit: z.number().default(20),
  order: ListAccountantUsersOrder$zodSchema.default("desc").describe(
    "The order of the results based on the sort field",
  ),
  sort: ListAccountantUsersSort$zodSchema.default("createdAt").describe(
    "The sort field of the results",
  ),
});

export type ListAccountantUsersPath = string | number;

export const ListAccountantUsersPath$zodSchema: z.ZodType<
  ListAccountantUsersPath
> = z.union([
  z.string(),
  z.number(),
]);

export type ListAccountantUsersIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListAccountantUsersIssue$zodSchema: z.ZodType<
  ListAccountantUsersIssue
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type ListAccountantUsersError = {
  issues: Array<ListAccountantUsersIssue>;
  name: string;
};

export const ListAccountantUsersError$zodSchema: z.ZodType<
  ListAccountantUsersError
> = z.object({
  issues: z.array(z.lazy(() => ListAccountantUsersIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type ListAccountantUsersUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListAccountantUsersError;
};

export const ListAccountantUsersUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<ListAccountantUsersUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() => ListAccountantUsersError$zodSchema),
    success: z.boolean(),
  }).describe("The validation error(s)");

export const ListAccountantUsersStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type ListAccountantUsersStatusCode = ClosedEnum<
  typeof ListAccountantUsersStatusCode
>;

export const ListAccountantUsersStatusCode$zodSchema = z.literal(403);

export const ListAccountantUsersType = {
  AuthError: "auth_error",
} as const;
export type ListAccountantUsersType = ClosedEnum<
  typeof ListAccountantUsersType
>;

export const ListAccountantUsersType$zodSchema = z.enum([
  "auth_error",
]);

export const ListAccountantUsersCode = {
  MissingScope: "missing_scope",
} as const;
export type ListAccountantUsersCode = ClosedEnum<
  typeof ListAccountantUsersCode
>;

export const ListAccountantUsersCode$zodSchema = z.enum([
  "missing_scope",
]);

/**
 * Missing scope
 */
export type ListAccountantUsersForbiddenResponseBody = {
  status_code: ListAccountantUsersStatusCode;
  type: ListAccountantUsersType;
  code: ListAccountantUsersCode;
  message: string;
};

export const ListAccountantUsersForbiddenResponseBody$zodSchema: z.ZodType<
  ListAccountantUsersForbiddenResponseBody
> = z.object({
  code: ListAccountantUsersCode$zodSchema,
  message: z.string(),
  status_code: ListAccountantUsersStatusCode$zodSchema,
  type: ListAccountantUsersType$zodSchema,
}).describe("Missing scope");

/**
 * Accountant users
 */
export type ListAccountantUsersResponseBody = {
  data: Array<AccountantUser>;
  pagination: Pagination;
};

export const ListAccountantUsersResponseBody$zodSchema: z.ZodType<
  ListAccountantUsersResponseBody
> = z.object({
  data: z.array(AccountantUser$zodSchema),
  pagination: Pagination$zodSchema,
}).describe("Accountant users");

export type ListAccountantUsersResponse =
  | AuthError
  | ListAccountantUsersForbiddenResponseBody
  | RateLimit
  | ListAccountantUsersResponseBody
  | ListAccountantUsersUnprocessableEntityResponseBody;

export const ListAccountantUsersResponse$zodSchema: z.ZodType<
  ListAccountantUsersResponse
> = z.union([
  AuthError$zodSchema,
  z.lazy(() => ListAccountantUsersForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => ListAccountantUsersResponseBody$zodSchema),
  z.lazy(() => ListAccountantUsersUnprocessableEntityResponseBody$zodSchema),
]);
