/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { PaginatedUsers, PaginatedUsers$zodSchema } from "./paginatedusers.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type ListUsersRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  xClientId: string;
};

export const ListUsersRequest$zodSchema: z.ZodType<ListUsersRequest> = z.object(
  {
    cursor: z.string().optional(),
    limit: z.number().default(20),
    xClientId: z.string(),
  },
);

export type ListUsersPath = string | number;

export const ListUsersPath$zodSchema: z.ZodType<ListUsersPath> = z.union([
  z.string(),
  z.number(),
]);

export type ListUsersIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListUsersIssue$zodSchema: z.ZodType<ListUsersIssue> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type ListUsersError = { issues: Array<ListUsersIssue>; name: string };

export const ListUsersError$zodSchema: z.ZodType<ListUsersError> = z.object({
  issues: z.array(z.lazy(() => ListUsersIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type ListUsersUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListUsersError;
};

export const ListUsersUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  ListUsersUnprocessableEntityResponseBody
> = z.object({
  error: z.lazy(() => ListUsersError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const ListUsersForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type ListUsersForbiddenStatusCode = ClosedEnum<
  typeof ListUsersForbiddenStatusCode
>;

export const ListUsersForbiddenStatusCode$zodSchema = z.literal(403);

export const ListUsersForbiddenType = {
  AuthError: "auth_error",
} as const;
export type ListUsersForbiddenType = ClosedEnum<typeof ListUsersForbiddenType>;

export const ListUsersForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const ListUsersForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type ListUsersForbiddenCode = ClosedEnum<typeof ListUsersForbiddenCode>;

export const ListUsersForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

/**
 * Missing scope
 */
export type ListUsersForbiddenResponseBody = {
  status_code: ListUsersForbiddenStatusCode;
  type: ListUsersForbiddenType;
  code: ListUsersForbiddenCode;
  message: string;
};

export const ListUsersForbiddenResponseBody$zodSchema: z.ZodType<
  ListUsersForbiddenResponseBody
> = z.object({
  code: ListUsersForbiddenCode$zodSchema,
  message: z.string(),
  status_code: ListUsersForbiddenStatusCode$zodSchema,
  type: ListUsersForbiddenType$zodSchema,
}).describe("Missing scope");

export const ListUsersStatusCode400 = {
  FourHundred: 400,
} as const;
export type ListUsersStatusCode400 = ClosedEnum<typeof ListUsersStatusCode400>;

export const ListUsersStatusCode400$zodSchema = z.literal(400);

export const ListUsersBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type ListUsersBadRequestType = ClosedEnum<
  typeof ListUsersBadRequestType
>;

export const ListUsersBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const ListUsersCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type ListUsersCodeMissingClientID = ClosedEnum<
  typeof ListUsersCodeMissingClientID
>;

export const ListUsersCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

/**
 * Missing client ID
 */
export type ListUsersBadRequestResponseBody = {
  status_code: ListUsersStatusCode400;
  type: ListUsersBadRequestType;
  code: ListUsersCodeMissingClientID;
  message: string;
};

export const ListUsersBadRequestResponseBody$zodSchema: z.ZodType<
  ListUsersBadRequestResponseBody
> = z.object({
  code: ListUsersCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: ListUsersStatusCode400$zodSchema,
  type: ListUsersBadRequestType$zodSchema,
}).describe("Missing client ID");

export type ListUsersResponse =
  | ListUsersBadRequestResponseBody
  | AuthError
  | ListUsersForbiddenResponseBody
  | RateLimit
  | PaginatedUsers
  | ListUsersUnprocessableEntityResponseBody;

export const ListUsersResponse$zodSchema: z.ZodType<ListUsersResponse> = z
  .union([
    z.lazy(() => ListUsersBadRequestResponseBody$zodSchema),
    AuthError$zodSchema,
    z.lazy(() => ListUsersForbiddenResponseBody$zodSchema),
    RateLimit$zodSchema,
    PaginatedUsers$zodSchema,
    z.lazy(() => ListUsersUnprocessableEntityResponseBody$zodSchema),
  ]);
