/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { PaginatedFiles, PaginatedFiles$zodSchema } from "./paginatedfiles.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type ListFilesRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  workspaceId?: string | undefined;
  xClientId: string;
};

export const ListFilesRequest$zodSchema: z.ZodType<
  ListFilesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  limit: z.number().default(20),
  workspaceId: z.string().optional(),
  xClientId: z.string(),
});

export type ListFilesPath = string | number;

export const ListFilesPath$zodSchema: z.ZodType<
  ListFilesPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type ListFilesIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListFilesIssue$zodSchema: z.ZodType<
  ListFilesIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type ListFilesError = { issues: Array<ListFilesIssue>; name: string };

export const ListFilesError$zodSchema: z.ZodType<
  ListFilesError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => ListFilesIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type ListFilesUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListFilesError;
};

export const ListFilesUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  ListFilesUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => ListFilesError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const ListFilesForbiddenStatusCode$zodSchema = z.literal(403);

export type ListFilesForbiddenStatusCode = z.infer<
  typeof ListFilesForbiddenStatusCode$zodSchema
>;

export const ListFilesForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type ListFilesForbiddenType = z.infer<
  typeof ListFilesForbiddenType$zodSchema
>;

export const ListFilesForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type ListFilesForbiddenCode = z.infer<
  typeof ListFilesForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type ListFilesForbiddenResponseBody = {
  status_code: ListFilesForbiddenStatusCode;
  type: ListFilesForbiddenType;
  code: ListFilesForbiddenCode;
  message: string;
};

export const ListFilesForbiddenResponseBody$zodSchema: z.ZodType<
  ListFilesForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListFilesForbiddenCode$zodSchema,
  message: z.string(),
  status_code: ListFilesForbiddenStatusCode$zodSchema,
  type: ListFilesForbiddenType$zodSchema,
}).describe("Missing scope");

export const ListFilesStatusCode400$zodSchema = z.literal(400);

export type ListFilesStatusCode400 = z.infer<
  typeof ListFilesStatusCode400$zodSchema
>;

export const ListFilesBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type ListFilesBadRequestType = z.infer<
  typeof ListFilesBadRequestType$zodSchema
>;

export const ListFilesCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type ListFilesCodeMissingClientID = z.infer<
  typeof ListFilesCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type ListFilesBadRequestResponseBody = {
  status_code: ListFilesStatusCode400;
  type: ListFilesBadRequestType;
  code: ListFilesCodeMissingClientID;
  message: string;
};

export const ListFilesBadRequestResponseBody$zodSchema: z.ZodType<
  ListFilesBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListFilesCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: ListFilesStatusCode400$zodSchema,
  type: ListFilesBadRequestType$zodSchema,
}).describe("Missing client ID");

export type ListFilesResponse =
  | ListFilesBadRequestResponseBody
  | AuthError
  | ListFilesForbiddenResponseBody
  | RateLimit
  | PaginatedFiles
  | ListFilesUnprocessableEntityResponseBody;

export const ListFilesResponse$zodSchema: z.ZodType<
  ListFilesResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListFilesBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => ListFilesForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  PaginatedFiles$zodSchema,
  z.lazy(() => ListFilesUnprocessableEntityResponseBody$zodSchema),
]);
