/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { PaginatedUsers, PaginatedUsers$zodSchema } from "./paginatedusers.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type ListUsersRequest = {
  limit?: number | undefined;
  cursor?: string | undefined;
  xClientId: string;
};

export const ListUsersRequest$zodSchema: z.ZodType<
  ListUsersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  limit: z.number().default(20),
  xClientId: z.string(),
});

export type ListUsersPath = string | number;

export const ListUsersPath$zodSchema: z.ZodType<
  ListUsersPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type ListUsersIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListUsersIssue$zodSchema: z.ZodType<
  ListUsersIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type ListUsersError = { issues: Array<ListUsersIssue>; name: string };

export const ListUsersError$zodSchema: z.ZodType<
  ListUsersError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => ListUsersIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type ListUsersUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListUsersError;
};

export const ListUsersUnprocessableEntityResponseBody$zodSchema: z.ZodType<
  ListUsersUnprocessableEntityResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => ListUsersError$zodSchema),
  success: z.boolean(),
}).describe("The validation error(s)");

export const ListUsersForbiddenStatusCode$zodSchema = z.literal(403);

export type ListUsersForbiddenStatusCode = z.infer<
  typeof ListUsersForbiddenStatusCode$zodSchema
>;

export const ListUsersForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type ListUsersForbiddenType = z.infer<
  typeof ListUsersForbiddenType$zodSchema
>;

export const ListUsersForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type ListUsersForbiddenCode = z.infer<
  typeof ListUsersForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type ListUsersForbiddenResponseBody = {
  status_code: ListUsersForbiddenStatusCode;
  type: ListUsersForbiddenType;
  code: ListUsersForbiddenCode;
  message: string;
};

export const ListUsersForbiddenResponseBody$zodSchema: z.ZodType<
  ListUsersForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListUsersForbiddenCode$zodSchema,
  message: z.string(),
  status_code: ListUsersForbiddenStatusCode$zodSchema,
  type: ListUsersForbiddenType$zodSchema,
}).describe("Missing scope");

export const ListUsersStatusCode400$zodSchema = z.literal(400);

export type ListUsersStatusCode400 = z.infer<
  typeof ListUsersStatusCode400$zodSchema
>;

export const ListUsersBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type ListUsersBadRequestType = z.infer<
  typeof ListUsersBadRequestType$zodSchema
>;

export const ListUsersCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type ListUsersCodeMissingClientID = z.infer<
  typeof ListUsersCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type ListUsersBadRequestResponseBody = {
  status_code: ListUsersStatusCode400;
  type: ListUsersBadRequestType;
  code: ListUsersCodeMissingClientID;
  message: string;
};

export const ListUsersBadRequestResponseBody$zodSchema: z.ZodType<
  ListUsersBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListUsersCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: ListUsersStatusCode400$zodSchema,
  type: ListUsersBadRequestType$zodSchema,
}).describe("Missing client ID");

export type ListUsersResponse =
  | ListUsersBadRequestResponseBody
  | AuthError
  | ListUsersForbiddenResponseBody
  | RateLimit
  | PaginatedUsers
  | ListUsersUnprocessableEntityResponseBody;

export const ListUsersResponse$zodSchema: z.ZodType<
  ListUsersResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListUsersBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => ListUsersForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  PaginatedUsers$zodSchema,
  z.lazy(() => ListUsersUnprocessableEntityResponseBody$zodSchema),
]);
