/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import {
  WorkspaceMember,
  WorkspaceMember$zodSchema,
} from "./workspacemember.js";

export type ListWorkspaceMembersRequest = { id: string; xClientId: string };

export const ListWorkspaceMembersRequest$zodSchema: z.ZodType<
  ListWorkspaceMembersRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  xClientId: z.string(),
});

export type ListWorkspaceMembersPath = string | number;

export const ListWorkspaceMembersPath$zodSchema: z.ZodType<
  ListWorkspaceMembersPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type ListWorkspaceMembersIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const ListWorkspaceMembersIssue$zodSchema: z.ZodType<
  ListWorkspaceMembersIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type ListWorkspaceMembersError = {
  issues: Array<ListWorkspaceMembersIssue>;
  name: string;
};

export const ListWorkspaceMembersError$zodSchema: z.ZodType<
  ListWorkspaceMembersError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => ListWorkspaceMembersIssue$zodSchema)),
  name: z.string(),
});

/**
 * The validation error(s)
 */
export type ListWorkspaceMembersUnprocessableEntityResponseBody = {
  success: boolean;
  error: ListWorkspaceMembersError;
};

export const ListWorkspaceMembersUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<
    ListWorkspaceMembersUnprocessableEntityResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.lazy(() => ListWorkspaceMembersError$zodSchema),
    success: z.boolean(),
  }).describe("The validation error(s)");

export const ListWorkspaceMembersForbiddenStatusCode$zodSchema = z.literal(403);

export type ListWorkspaceMembersForbiddenStatusCode = z.infer<
  typeof ListWorkspaceMembersForbiddenStatusCode$zodSchema
>;

export const ListWorkspaceMembersForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type ListWorkspaceMembersForbiddenType = z.infer<
  typeof ListWorkspaceMembersForbiddenType$zodSchema
>;

export const ListWorkspaceMembersForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type ListWorkspaceMembersForbiddenCode = z.infer<
  typeof ListWorkspaceMembersForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type ListWorkspaceMembersForbiddenResponseBody = {
  status_code: ListWorkspaceMembersForbiddenStatusCode;
  type: ListWorkspaceMembersForbiddenType;
  code: ListWorkspaceMembersForbiddenCode;
  message: string;
};

export const ListWorkspaceMembersForbiddenResponseBody$zodSchema: z.ZodType<
  ListWorkspaceMembersForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListWorkspaceMembersForbiddenCode$zodSchema,
  message: z.string(),
  status_code: ListWorkspaceMembersForbiddenStatusCode$zodSchema,
  type: ListWorkspaceMembersForbiddenType$zodSchema,
}).describe("Missing scope");

export const ListWorkspaceMembersStatusCode400$zodSchema = z.literal(400);

export type ListWorkspaceMembersStatusCode400 = z.infer<
  typeof ListWorkspaceMembersStatusCode400$zodSchema
>;

export const ListWorkspaceMembersBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type ListWorkspaceMembersBadRequestType = z.infer<
  typeof ListWorkspaceMembersBadRequestType$zodSchema
>;

export const ListWorkspaceMembersCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type ListWorkspaceMembersCodeMissingClientID = z.infer<
  typeof ListWorkspaceMembersCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type ListWorkspaceMembersBadRequestResponseBody = {
  status_code: ListWorkspaceMembersStatusCode400;
  type: ListWorkspaceMembersBadRequestType;
  code: ListWorkspaceMembersCodeMissingClientID;
  message: string;
};

export const ListWorkspaceMembersBadRequestResponseBody$zodSchema: z.ZodType<
  ListWorkspaceMembersBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: ListWorkspaceMembersCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: ListWorkspaceMembersStatusCode400$zodSchema,
  type: ListWorkspaceMembersBadRequestType$zodSchema,
}).describe("Missing client ID");

export type ListWorkspaceMembersResponse =
  | ListWorkspaceMembersBadRequestResponseBody
  | AuthError
  | ListWorkspaceMembersForbiddenResponseBody
  | RateLimit
  | ListWorkspaceMembersUnprocessableEntityResponseBody
  | Array<WorkspaceMember>;

export const ListWorkspaceMembersResponse$zodSchema: z.ZodType<
  ListWorkspaceMembersResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ListWorkspaceMembersBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => ListWorkspaceMembersForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.lazy(() => ListWorkspaceMembersUnprocessableEntityResponseBody$zodSchema),
  z.array(WorkspaceMember$zodSchema).describe("Workspace members"),
]);
