/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const MeStatusCode$zodSchema = z.literal(403);

export type MeStatusCode = z.infer<typeof MeStatusCode$zodSchema>;

export const MeType$zodSchema = z.enum([
  "auth_error",
]);

export type MeType = z.infer<typeof MeType$zodSchema>;

export const MeCode$zodSchema = z.enum([
  "missing_scope",
]);

export type MeCode = z.infer<typeof MeCode$zodSchema>;

/**
 * Missing scope
 */
export type MeForbiddenResponseBody = {
  status_code: MeStatusCode;
  type: MeType;
  code: MeCode;
  message: string;
};

export const MeForbiddenResponseBody$zodSchema: z.ZodType<
  MeForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: MeCode$zodSchema,
  message: z.string(),
  status_code: MeStatusCode$zodSchema,
  type: MeType$zodSchema,
}).describe("Missing scope");

/**
 * Me
 */
export type MeResponseBody = {
  type: string;
  accountantId: string;
  clientId: string | null;
  apiKeyId: string;
  rateLimitMax: number;
  rateLimitTimeWindow: number;
  permissions: Array<string>;
};

export const MeResponseBody$zodSchema: z.ZodType<
  MeResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  accountantId: z.string(),
  apiKeyId: z.string(),
  clientId: z.string().nullable(),
  permissions: z.array(z.string()),
  rateLimitMax: z.number(),
  rateLimitTimeWindow: z.number(),
  type: z.string(),
}).describe("Me");

export type MeResponse =
  | MeResponseBody
  | AuthError
  | MeForbiddenResponseBody
  | RateLimit;

export const MeResponse$zodSchema: z.ZodType<
  MeResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => MeResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => MeForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
]);
