/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const NotFoundStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type NotFoundStatusCode = ClosedEnum<typeof NotFoundStatusCode>;

export const NotFoundStatusCode$zodSchema = z.literal(404);

export const NotFoundType = {
  NotFound: "not_found",
} as const;
export type NotFoundType = ClosedEnum<typeof NotFoundType>;

export const NotFoundType$zodSchema = z.enum([
  "not_found",
]);

export const NotFoundCode = {
  NotFound: "not_found",
} as const;
export type NotFoundCode = ClosedEnum<typeof NotFoundCode>;

export const NotFoundCode$zodSchema = z.enum([
  "not_found",
]);

export type NotFound = {
  status_code: NotFoundStatusCode;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

export const NotFound$zodSchema: z.ZodType<NotFound> = z.object({
  code: NotFoundCode$zodSchema,
  message: z.string(),
  status_code: NotFoundStatusCode$zodSchema,
  type: NotFoundType$zodSchema,
});
