/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const NotFoundType$zodSchema = z.enum([
  "not_found",
]);

export type NotFoundType = z.infer<typeof NotFoundType$zodSchema>;

export const NotFoundCode$zodSchema = z.enum([
  "not_found",
]);

export type NotFoundCode = z.infer<typeof NotFoundCode$zodSchema>;

export type NotFound = {
  status_code: number;
  type: NotFoundType;
  code: NotFoundCode;
  message: string;
};

export const NotFound$zodSchema: z.ZodType<NotFound, z.ZodTypeDef, unknown> = z
  .object({
    code: NotFoundCode$zodSchema,
    message: z.string(),
    status_code: z.number(),
    type: NotFoundType$zodSchema,
  });
