/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Client, Client$zodSchema } from "./client.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

export type PaginatedClients = { data: Array<Client>; pagination: Pagination };

export const PaginatedClients$zodSchema: z.ZodType<
  PaginatedClients,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Client$zodSchema),
  pagination: Pagination$zodSchema,
});
