/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { Task, Task$zodSchema } from "./task.js";

export type PaginatedTasks = { data: Array<Task>; pagination: Pagination };

export const PaginatedTasks$zodSchema: z.ZodType<
  PaginatedTasks,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Task$zodSchema),
  pagination: Pagination$zodSchema,
});
