/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Pagination = {
  nextCursor?: string | undefined;
  previousCursor?: string | undefined;
  limit: number;
  total: number;
};

export const Pagination$zodSchema: z.ZodType<Pagination> = z.object({
  limit: z.int().describe("The number of items to return"),
  nextCursor: z.string().optional().describe(
    "The cursor to return the next page of items",
  ),
  previousCursor: z.string().optional().describe(
    "The cursor to return the previous page of items",
  ),
  total: z.int().describe("The total number of items"),
});
