/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Pagination = {
  nextCursor?: string | undefined;
  previousCursor?: string | undefined;
  limit: number;
  total: number;
};

export const Pagination$zodSchema: z.ZodType<
  Pagination,
  z.ZodTypeDef,
  unknown
> = z.object({
  limit: z.number().int(),
  nextCursor: z.string().optional(),
  previousCursor: z.string().optional(),
  total: z.number().int(),
});
