/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Pagination, Pagination$zodSchema } from "./pagination.js";
import { Workspace, Workspace$zodSchema } from "./workspace.js";

export type PaginatedWorkspaces = {
  data: Array<Workspace>;
  pagination: Pagination;
};

export const PaginatedWorkspaces$zodSchema: z.ZodType<
  PaginatedWorkspaces,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(Workspace$zodSchema),
  pagination: Pagination$zodSchema,
});
