/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClientUser, ClientUser$zodSchema } from "./clientuser.js";
import { Pagination, Pagination$zodSchema } from "./pagination.js";

export type PaginatedUsers = {
  data: Array<ClientUser>;
  pagination: Pagination;
};

export const PaginatedUsers$zodSchema: z.ZodType<
  PaginatedUsers,
  z.ZodTypeDef,
  unknown
> = z.object({
  data: z.array(ClientUser$zodSchema),
  pagination: Pagination$zodSchema,
});
