/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

/**
 * Pong
 */
export type PingResponseBody = { ping: string };

export const PingResponseBody$zodSchema: z.ZodType<PingResponseBody> = z.object(
  {
    ping: z.string(),
  },
).describe("Pong");

export type PingResponse = RateLimit | InternalError | PingResponseBody;

export const PingResponse$zodSchema: z.ZodType<PingResponse> = z.union([
  RateLimit$zodSchema,
  InternalError$zodSchema,
  z.lazy(() => PingResponseBody$zodSchema),
]);
