/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import {
  PingSessionResponse,
  PingSessionResponse$zodSchema,
} from "./pingsessionresponse.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const PingCollectSessionStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type PingCollectSessionStatusCode = ClosedEnum<
  typeof PingCollectSessionStatusCode
>;

export const PingCollectSessionStatusCode$zodSchema = z.literal(404);

export const PingCollectSessionType = {
  NotFound: "not_found",
} as const;
export type PingCollectSessionType = ClosedEnum<typeof PingCollectSessionType>;

export const PingCollectSessionType$zodSchema = z.enum([
  "not_found",
]);

export const PingCollectSessionCode = {
  CollectTokenNotFound: "collect_token_not_found",
} as const;
export type PingCollectSessionCode = ClosedEnum<typeof PingCollectSessionCode>;

export const PingCollectSessionCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

export type PingCollectSessionRequest = { token: string };

export const PingCollectSessionRequest$zodSchema: z.ZodType<
  PingCollectSessionRequest
> = z.object({
  token: z.string(),
});

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type PingCollectSessionResponseBody = {
  status_code: PingCollectSessionStatusCode;
  type: PingCollectSessionType;
  code: PingCollectSessionCode;
  message: string;
};

export const PingCollectSessionResponseBody$zodSchema: z.ZodType<
  PingCollectSessionResponseBody
> = z.object({
  code: PingCollectSessionCode$zodSchema,
  message: z.string(),
  status_code: PingCollectSessionStatusCode$zodSchema,
  type: PingCollectSessionType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

export type PingCollectSessionResponse =
  | PingCollectSessionResponseBody
  | BadRequest
  | RateLimit
  | InternalError
  | PingSessionResponse;

export const PingCollectSessionResponse$zodSchema: z.ZodType<
  PingCollectSessionResponse
> = z.union([
  z.lazy(() => PingCollectSessionResponseBody$zodSchema),
  BadRequest$zodSchema,
  RateLimit$zodSchema,
  InternalError$zodSchema,
  PingSessionResponse$zodSchema,
]);
