/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const RateLimitType$zodSchema = z.enum([
  "rate_limit",
]);

export type RateLimitType = z.infer<typeof RateLimitType$zodSchema>;

export const RateLimitCode$zodSchema = z.enum([
  "too_many_requests",
]);

export type RateLimitCode = z.infer<typeof RateLimitCode$zodSchema>;

export type RateLimit = {
  status_code: number;
  type: RateLimitType;
  code: RateLimitCode;
  message: string;
};

export const RateLimit$zodSchema: z.ZodType<RateLimit, z.ZodTypeDef, unknown> =
  z.object({
    code: RateLimitCode$zodSchema,
    message: z.string(),
    status_code: z.number(),
    type: RateLimitType$zodSchema,
  });
