/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { DeleteResponse, DeleteResponse$zodSchema } from "./deleteresponse.js";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import {
  WorkspaceMemberRemove,
  WorkspaceMemberRemove$zodSchema,
} from "./workspacememberremove.js";

export const RemoveWorkspaceMemberForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type RemoveWorkspaceMemberForbiddenStatusCode = ClosedEnum<
  typeof RemoveWorkspaceMemberForbiddenStatusCode
>;

export const RemoveWorkspaceMemberForbiddenStatusCode$zodSchema = z.literal(
  403,
);

export const RemoveWorkspaceMemberForbiddenType = {
  AuthError: "auth_error",
} as const;
export type RemoveWorkspaceMemberForbiddenType = ClosedEnum<
  typeof RemoveWorkspaceMemberForbiddenType
>;

export const RemoveWorkspaceMemberForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const RemoveWorkspaceMemberForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type RemoveWorkspaceMemberForbiddenCode = ClosedEnum<
  typeof RemoveWorkspaceMemberForbiddenCode
>;

export const RemoveWorkspaceMemberForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export const RemoveWorkspaceMemberStatusCode400 = {
  FourHundred: 400,
} as const;
export type RemoveWorkspaceMemberStatusCode400 = ClosedEnum<
  typeof RemoveWorkspaceMemberStatusCode400
>;

export const RemoveWorkspaceMemberStatusCode400$zodSchema = z.literal(400);

export const RemoveWorkspaceMemberBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type RemoveWorkspaceMemberBadRequestType = ClosedEnum<
  typeof RemoveWorkspaceMemberBadRequestType
>;

export const RemoveWorkspaceMemberBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const RemoveWorkspaceMemberCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type RemoveWorkspaceMemberCodeMissingClientID = ClosedEnum<
  typeof RemoveWorkspaceMemberCodeMissingClientID
>;

export const RemoveWorkspaceMemberCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type RemoveWorkspaceMemberRequest = {
  id: string;
  xClientId: string;
  WorkspaceMemberRemove: WorkspaceMemberRemove;
};

export const RemoveWorkspaceMemberRequest$zodSchema: z.ZodType<
  RemoveWorkspaceMemberRequest
> = z.object({
  WorkspaceMemberRemove: WorkspaceMemberRemove$zodSchema.describe(
    "Workspace member remove",
  ),
  id: z.string(),
  xClientId: z.string(),
});

export type RemoveWorkspaceMemberPath = string | number;

export const RemoveWorkspaceMemberPath$zodSchema: z.ZodType<
  RemoveWorkspaceMemberPath
> = z.union([
  z.string(),
  z.number(),
]);

export type RemoveWorkspaceMemberIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const RemoveWorkspaceMemberIssue$zodSchema: z.ZodType<
  RemoveWorkspaceMemberIssue
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type RemoveWorkspaceMemberError = {
  issues: Array<RemoveWorkspaceMemberIssue>;
  name: string;
};

export const RemoveWorkspaceMemberError$zodSchema: z.ZodType<
  RemoveWorkspaceMemberError
> = z.object({
  issues: z.array(z.lazy(() => RemoveWorkspaceMemberIssue$zodSchema)),
  name: z.string(),
});

/**
 * Invalid id error
 */
export type RemoveWorkspaceMemberUnprocessableEntityResponseBody = {
  success: boolean;
  error: RemoveWorkspaceMemberError;
};

export const RemoveWorkspaceMemberUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<RemoveWorkspaceMemberUnprocessableEntityResponseBody> = z.object({
    error: z.lazy(() => RemoveWorkspaceMemberError$zodSchema),
    success: z.boolean(),
  }).describe("Invalid id error");

/**
 * Missing scope
 */
export type RemoveWorkspaceMemberForbiddenResponseBody = {
  status_code: RemoveWorkspaceMemberForbiddenStatusCode;
  type: RemoveWorkspaceMemberForbiddenType;
  code: RemoveWorkspaceMemberForbiddenCode;
  message: string;
};

export const RemoveWorkspaceMemberForbiddenResponseBody$zodSchema: z.ZodType<
  RemoveWorkspaceMemberForbiddenResponseBody
> = z.object({
  code: RemoveWorkspaceMemberForbiddenCode$zodSchema,
  message: z.string(),
  status_code: RemoveWorkspaceMemberForbiddenStatusCode$zodSchema,
  type: RemoveWorkspaceMemberForbiddenType$zodSchema,
}).describe("Missing scope");

/**
 * Missing client ID
 */
export type RemoveWorkspaceMemberBadRequestResponseBody = {
  status_code: RemoveWorkspaceMemberStatusCode400;
  type: RemoveWorkspaceMemberBadRequestType;
  code: RemoveWorkspaceMemberCodeMissingClientID;
  message: string;
};

export const RemoveWorkspaceMemberBadRequestResponseBody$zodSchema: z.ZodType<
  RemoveWorkspaceMemberBadRequestResponseBody
> = z.object({
  code: RemoveWorkspaceMemberCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: RemoveWorkspaceMemberStatusCode400$zodSchema,
  type: RemoveWorkspaceMemberBadRequestType$zodSchema,
}).describe("Missing client ID");

export type RemoveWorkspaceMemberResponse =
  | RemoveWorkspaceMemberBadRequestResponseBody
  | AuthError
  | RemoveWorkspaceMemberForbiddenResponseBody
  | RateLimit
  | InternalError
  | DeleteResponse
  | RemoveWorkspaceMemberUnprocessableEntityResponseBody;

export const RemoveWorkspaceMemberResponse$zodSchema: z.ZodType<
  RemoveWorkspaceMemberResponse
> = z.union([
  z.lazy(() => RemoveWorkspaceMemberBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => RemoveWorkspaceMemberForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  InternalError$zodSchema,
  DeleteResponse$zodSchema,
  z.lazy(() => RemoveWorkspaceMemberUnprocessableEntityResponseBody$zodSchema),
]);
