/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { DeleteResponse, DeleteResponse$zodSchema } from "./deleteresponse.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import {
  WorkspaceMemberRemove,
  WorkspaceMemberRemove$zodSchema,
} from "./workspacememberremove.js";

export type RemoveWorkspaceMemberRequest = {
  id: string;
  xClientId: string;
  WorkspaceMemberRemove: WorkspaceMemberRemove;
};

export const RemoveWorkspaceMemberRequest$zodSchema: z.ZodType<
  RemoveWorkspaceMemberRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  WorkspaceMemberRemove: WorkspaceMemberRemove$zodSchema,
  id: z.string(),
  xClientId: z.string(),
});

export type RemoveWorkspaceMemberPath = string | number;

export const RemoveWorkspaceMemberPath$zodSchema: z.ZodType<
  RemoveWorkspaceMemberPath,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type RemoveWorkspaceMemberIssue = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const RemoveWorkspaceMemberIssue$zodSchema: z.ZodType<
  RemoveWorkspaceMemberIssue,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type RemoveWorkspaceMemberError = {
  issues: Array<RemoveWorkspaceMemberIssue>;
  name: string;
};

export const RemoveWorkspaceMemberError$zodSchema: z.ZodType<
  RemoveWorkspaceMemberError,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => RemoveWorkspaceMemberIssue$zodSchema)),
  name: z.string(),
});

/**
 * Invalid id error
 */
export type RemoveWorkspaceMemberUnprocessableEntityResponseBody = {
  success: boolean;
  error: RemoveWorkspaceMemberError;
};

export const RemoveWorkspaceMemberUnprocessableEntityResponseBody$zodSchema:
  z.ZodType<
    RemoveWorkspaceMemberUnprocessableEntityResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    error: z.lazy(() => RemoveWorkspaceMemberError$zodSchema),
    success: z.boolean(),
  }).describe("Invalid id error");

export const RemoveWorkspaceMemberForbiddenStatusCode$zodSchema = z.literal(
  403,
);

export type RemoveWorkspaceMemberForbiddenStatusCode = z.infer<
  typeof RemoveWorkspaceMemberForbiddenStatusCode$zodSchema
>;

export const RemoveWorkspaceMemberForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export type RemoveWorkspaceMemberForbiddenType = z.infer<
  typeof RemoveWorkspaceMemberForbiddenType$zodSchema
>;

export const RemoveWorkspaceMemberForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export type RemoveWorkspaceMemberForbiddenCode = z.infer<
  typeof RemoveWorkspaceMemberForbiddenCode$zodSchema
>;

/**
 * Missing scope
 */
export type RemoveWorkspaceMemberForbiddenResponseBody = {
  status_code: RemoveWorkspaceMemberForbiddenStatusCode;
  type: RemoveWorkspaceMemberForbiddenType;
  code: RemoveWorkspaceMemberForbiddenCode;
  message: string;
};

export const RemoveWorkspaceMemberForbiddenResponseBody$zodSchema: z.ZodType<
  RemoveWorkspaceMemberForbiddenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: RemoveWorkspaceMemberForbiddenCode$zodSchema,
  message: z.string(),
  status_code: RemoveWorkspaceMemberForbiddenStatusCode$zodSchema,
  type: RemoveWorkspaceMemberForbiddenType$zodSchema,
}).describe("Missing scope");

export const RemoveWorkspaceMemberStatusCode400$zodSchema = z.literal(400);

export type RemoveWorkspaceMemberStatusCode400 = z.infer<
  typeof RemoveWorkspaceMemberStatusCode400$zodSchema
>;

export const RemoveWorkspaceMemberBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export type RemoveWorkspaceMemberBadRequestType = z.infer<
  typeof RemoveWorkspaceMemberBadRequestType$zodSchema
>;

export const RemoveWorkspaceMemberCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type RemoveWorkspaceMemberCodeMissingClientID = z.infer<
  typeof RemoveWorkspaceMemberCodeMissingClientID$zodSchema
>;

/**
 * Missing client ID
 */
export type RemoveWorkspaceMemberBadRequestResponseBody = {
  status_code: RemoveWorkspaceMemberStatusCode400;
  type: RemoveWorkspaceMemberBadRequestType;
  code: RemoveWorkspaceMemberCodeMissingClientID;
  message: string;
};

export const RemoveWorkspaceMemberBadRequestResponseBody$zodSchema: z.ZodType<
  RemoveWorkspaceMemberBadRequestResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: RemoveWorkspaceMemberCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: RemoveWorkspaceMemberStatusCode400$zodSchema,
  type: RemoveWorkspaceMemberBadRequestType$zodSchema,
}).describe("Missing client ID");

export type RemoveWorkspaceMemberResponse =
  | RemoveWorkspaceMemberBadRequestResponseBody
  | AuthError
  | RemoveWorkspaceMemberForbiddenResponseBody
  | RateLimit
  | DeleteResponse
  | RemoveWorkspaceMemberUnprocessableEntityResponseBody;

export const RemoveWorkspaceMemberResponse$zodSchema: z.ZodType<
  RemoveWorkspaceMemberResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RemoveWorkspaceMemberBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => RemoveWorkspaceMemberForbiddenResponseBody$zodSchema),
  RateLimit$zodSchema,
  DeleteResponse$zodSchema,
  z.lazy(() => RemoveWorkspaceMemberUnprocessableEntityResponseBody$zodSchema),
]);
