/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import {
  RequestLinkBody,
  RequestLinkBody$zodSchema,
} from "./requestlinkbody.js";
import {
  RequestLinkResponse,
  RequestLinkResponse$zodSchema,
} from "./requestlinkresponse.js";

export type RequestLinkCollectTokenRequest = {
  token: string;
  RequestLinkBody?: RequestLinkBody | undefined;
};

export const RequestLinkCollectTokenRequest$zodSchema: z.ZodType<
  RequestLinkCollectTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestLinkBody: RequestLinkBody$zodSchema.optional(),
  token: z.string(),
});

export type RequestLinkCollectTokenPath2 = string | number;

export const RequestLinkCollectTokenPath2$zodSchema: z.ZodType<
  RequestLinkCollectTokenPath2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type RequestLinkCollectTokenIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const RequestLinkCollectTokenIssue2$zodSchema: z.ZodType<
  RequestLinkCollectTokenIssue2,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type RequestLinkCollectTokenError2 = {
  issues: Array<RequestLinkCollectTokenIssue2>;
  name: string;
};

export const RequestLinkCollectTokenError2$zodSchema: z.ZodType<
  RequestLinkCollectTokenError2,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => RequestLinkCollectTokenIssue2$zodSchema)),
  name: z.string(),
});

export type RequestLinkCollectTokenResponseBody2 = {
  success: boolean;
  error: RequestLinkCollectTokenError2;
};

export const RequestLinkCollectTokenResponseBody2$zodSchema: z.ZodType<
  RequestLinkCollectTokenResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => RequestLinkCollectTokenError2$zodSchema),
  success: z.boolean(),
});

export type RequestLinkCollectTokenPath1 = string | number;

export const RequestLinkCollectTokenPath1$zodSchema: z.ZodType<
  RequestLinkCollectTokenPath1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type RequestLinkCollectTokenIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const RequestLinkCollectTokenIssue1$zodSchema: z.ZodType<
  RequestLinkCollectTokenIssue1,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type RequestLinkCollectTokenError1 = {
  issues: Array<RequestLinkCollectTokenIssue1>;
  name: string;
};

export const RequestLinkCollectTokenError1$zodSchema: z.ZodType<
  RequestLinkCollectTokenError1,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => RequestLinkCollectTokenIssue1$zodSchema)),
  name: z.string(),
});

export type RequestLinkCollectTokenResponseBody1 = {
  success: boolean;
  error: RequestLinkCollectTokenError1;
};

export const RequestLinkCollectTokenResponseBody1$zodSchema: z.ZodType<
  RequestLinkCollectTokenResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => RequestLinkCollectTokenError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type RequestLinkCollectTokenResponseBody =
  | RequestLinkCollectTokenResponseBody1
  | RequestLinkCollectTokenResponseBody2;

export const RequestLinkCollectTokenResponseBody$zodSchema: z.ZodType<
  RequestLinkCollectTokenResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => RequestLinkCollectTokenResponseBody1$zodSchema),
  z.lazy(() => RequestLinkCollectTokenResponseBody2$zodSchema),
]).describe("The validation error(s)");

export type RequestLinkCollectTokenResponse =
  | RateLimit
  | RequestLinkResponse
  | RequestLinkCollectTokenResponseBody1
  | RequestLinkCollectTokenResponseBody2;

export const RequestLinkCollectTokenResponse$zodSchema: z.ZodType<
  RequestLinkCollectTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  RateLimit$zodSchema,
  RequestLinkResponse$zodSchema,
  z.union([
    z.lazy(() => RequestLinkCollectTokenResponseBody1$zodSchema),
    z.lazy(() => RequestLinkCollectTokenResponseBody2$zodSchema),
  ]),
]);
