/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RequestLinkResponse = { success: boolean };

export const RequestLinkResponse$zodSchema: z.ZodType<RequestLinkResponse> = z
  .object({
    success: z.boolean(),
  });
