/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RequestLinkResponse = {
  success: boolean;
  maskedEmail: string | null;
};

export const RequestLinkResponse$zodSchema: z.ZodType<RequestLinkResponse> = z
  .object({
    maskedEmail: z.string().nullable().describe(
      "Masked address the new link was sent to, if one was sent",
    ),
    success: z.boolean(),
  });
