/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = { bearerAuth?: string | undefined };

export const Security$zodSchema: z.ZodType<Security> = z.object({
  bearerAuth: z.string().describe("Bearer token authentication").optional(),
});
