/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  CollectFileSubmission,
  CollectFileSubmission$zodSchema,
} from "./collectfilesubmission.js";
import {
  CollectFileSubmitForm,
  CollectFileSubmitForm$zodSchema,
} from "./collectfilesubmitform.js";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export const SubmitCollectFileRequestEntityTooLargeStatusCode = {
  FourHundredAndThirteen: 413,
} as const;
export type SubmitCollectFileRequestEntityTooLargeStatusCode = ClosedEnum<
  typeof SubmitCollectFileRequestEntityTooLargeStatusCode
>;

export const SubmitCollectFileRequestEntityTooLargeStatusCode$zodSchema = z
  .literal(413);

export const SubmitCollectFileRequestEntityTooLargeType = {
  BadRequest: "bad_request",
} as const;
export type SubmitCollectFileRequestEntityTooLargeType = ClosedEnum<
  typeof SubmitCollectFileRequestEntityTooLargeType
>;

export const SubmitCollectFileRequestEntityTooLargeType$zodSchema = z.enum([
  "bad_request",
]);

export const SubmitCollectFileRequestEntityTooLargeCode = {
  PayloadTooLarge: "payload_too_large",
} as const;
export type SubmitCollectFileRequestEntityTooLargeCode = ClosedEnum<
  typeof SubmitCollectFileRequestEntityTooLargeCode
>;

export const SubmitCollectFileRequestEntityTooLargeCode$zodSchema = z.enum([
  "payload_too_large",
]);

export const SubmitCollectFileNotFoundStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type SubmitCollectFileNotFoundStatusCode = ClosedEnum<
  typeof SubmitCollectFileNotFoundStatusCode
>;

export const SubmitCollectFileNotFoundStatusCode$zodSchema = z.literal(404);

export const SubmitCollectFileNotFoundType = {
  NotFound: "not_found",
} as const;
export type SubmitCollectFileNotFoundType = ClosedEnum<
  typeof SubmitCollectFileNotFoundType
>;

export const SubmitCollectFileNotFoundType$zodSchema = z.enum([
  "not_found",
]);

export const SubmitCollectFileNotFoundCode = {
  CollectTokenNotFound: "collect_token_not_found",
} as const;
export type SubmitCollectFileNotFoundCode = ClosedEnum<
  typeof SubmitCollectFileNotFoundCode
>;

export const SubmitCollectFileNotFoundCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

export type SubmitCollectFileRequest = {
  token: string;
  CollectFileSubmitForm: CollectFileSubmitForm;
};

export const SubmitCollectFileRequest$zodSchema: z.ZodType<
  SubmitCollectFileRequest
> = z.object({
  CollectFileSubmitForm: CollectFileSubmitForm$zodSchema.describe(
    "The file to submit",
  ),
  token: z.string(),
});

export type SubmitCollectFilePath2 = string | number;

export const SubmitCollectFilePath2$zodSchema: z.ZodType<
  SubmitCollectFilePath2
> = z.union([
  z.string(),
  z.number(),
]);

export type SubmitCollectFileIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const SubmitCollectFileIssue2$zodSchema: z.ZodType<
  SubmitCollectFileIssue2
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type SubmitCollectFileError2 = {
  issues: Array<SubmitCollectFileIssue2>;
  name: string;
};

export const SubmitCollectFileError2$zodSchema: z.ZodType<
  SubmitCollectFileError2
> = z.object({
  issues: z.array(z.lazy(() => SubmitCollectFileIssue2$zodSchema)),
  name: z.string(),
});

export type SubmitCollectFileResponseBody2 = {
  success: boolean;
  error: SubmitCollectFileError2;
};

export const SubmitCollectFileResponseBody2$zodSchema: z.ZodType<
  SubmitCollectFileResponseBody2
> = z.object({
  error: z.lazy(() => SubmitCollectFileError2$zodSchema),
  success: z.boolean(),
});

export type SubmitCollectFilePath1 = string | number;

export const SubmitCollectFilePath1$zodSchema: z.ZodType<
  SubmitCollectFilePath1
> = z.union([
  z.string(),
  z.number(),
]);

export type SubmitCollectFileIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const SubmitCollectFileIssue1$zodSchema: z.ZodType<
  SubmitCollectFileIssue1
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type SubmitCollectFileError1 = {
  issues: Array<SubmitCollectFileIssue1>;
  name: string;
};

export const SubmitCollectFileError1$zodSchema: z.ZodType<
  SubmitCollectFileError1
> = z.object({
  issues: z.array(z.lazy(() => SubmitCollectFileIssue1$zodSchema)),
  name: z.string(),
});

export type SubmitCollectFileResponseBody1 = {
  success: boolean;
  error: SubmitCollectFileError1;
};

export const SubmitCollectFileResponseBody1$zodSchema: z.ZodType<
  SubmitCollectFileResponseBody1
> = z.object({
  error: z.lazy(() => SubmitCollectFileError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type SubmitCollectFileResponseBody =
  | SubmitCollectFileResponseBody1
  | SubmitCollectFileResponseBody2;

export const SubmitCollectFileResponseBody$zodSchema: z.ZodType<
  SubmitCollectFileResponseBody
> = z.union([
  z.lazy(() => SubmitCollectFileResponseBody1$zodSchema),
  z.lazy(() => SubmitCollectFileResponseBody2$zodSchema),
]).describe("The validation error(s)");

/**
 * Payload too large
 */
export type SubmitCollectFileRequestEntityTooLargeResponseBody = {
  status_code: SubmitCollectFileRequestEntityTooLargeStatusCode;
  type: SubmitCollectFileRequestEntityTooLargeType;
  code: SubmitCollectFileRequestEntityTooLargeCode;
  message: string;
};

export const SubmitCollectFileRequestEntityTooLargeResponseBody$zodSchema:
  z.ZodType<SubmitCollectFileRequestEntityTooLargeResponseBody> = z.object({
    code: SubmitCollectFileRequestEntityTooLargeCode$zodSchema,
    message: z.string(),
    status_code: SubmitCollectFileRequestEntityTooLargeStatusCode$zodSchema,
    type: SubmitCollectFileRequestEntityTooLargeType$zodSchema,
  }).describe("Payload too large");

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type SubmitCollectFileNotFoundResponseBody = {
  status_code: SubmitCollectFileNotFoundStatusCode;
  type: SubmitCollectFileNotFoundType;
  code: SubmitCollectFileNotFoundCode;
  message: string;
};

export const SubmitCollectFileNotFoundResponseBody$zodSchema: z.ZodType<
  SubmitCollectFileNotFoundResponseBody
> = z.object({
  code: SubmitCollectFileNotFoundCode$zodSchema,
  message: z.string(),
  status_code: SubmitCollectFileNotFoundStatusCode$zodSchema,
  type: SubmitCollectFileNotFoundType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

export type SubmitCollectFileResponse =
  | CollectFileSubmission
  | SubmitCollectFileNotFoundResponseBody
  | BadRequest
  | SubmitCollectFileRequestEntityTooLargeResponseBody
  | RateLimit
  | InternalError
  | SubmitCollectFileResponseBody1
  | SubmitCollectFileResponseBody2;

export const SubmitCollectFileResponse$zodSchema: z.ZodType<
  SubmitCollectFileResponse
> = z.union([
  CollectFileSubmission$zodSchema,
  z.lazy(() => SubmitCollectFileNotFoundResponseBody$zodSchema),
  BadRequest$zodSchema,
  z.lazy(() => SubmitCollectFileRequestEntityTooLargeResponseBody$zodSchema),
  RateLimit$zodSchema,
  InternalError$zodSchema,
  z.union([
    z.lazy(() => SubmitCollectFileResponseBody1$zodSchema),
    z.lazy(() => SubmitCollectFileResponseBody2$zodSchema),
  ]),
]);
