/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  CollectFormDataSubmission,
  CollectFormDataSubmission$zodSchema,
} from "./collectformdatasubmission.js";
import {
  CollectFormDataSubmit,
  CollectFormDataSubmit$zodSchema,
} from "./collectformdatasubmit.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type SubmitCollectFormDataRequest = {
  token: string;
  CollectFormDataSubmit?: CollectFormDataSubmit | undefined;
};

export const SubmitCollectFormDataRequest$zodSchema: z.ZodType<
  SubmitCollectFormDataRequest
> = z.object({
  CollectFormDataSubmit: CollectFormDataSubmit$zodSchema.optional().describe(
    "The form data to submit",
  ),
  token: z.string(),
});

export type SubmitCollectFormDataPath2 = string | number;

export const SubmitCollectFormDataPath2$zodSchema: z.ZodType<
  SubmitCollectFormDataPath2
> = z.union([
  z.string(),
  z.number(),
]);

export type SubmitCollectFormDataIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const SubmitCollectFormDataIssue2$zodSchema: z.ZodType<
  SubmitCollectFormDataIssue2
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type SubmitCollectFormDataError2 = {
  issues: Array<SubmitCollectFormDataIssue2>;
  name: string;
};

export const SubmitCollectFormDataError2$zodSchema: z.ZodType<
  SubmitCollectFormDataError2
> = z.object({
  issues: z.array(z.lazy(() => SubmitCollectFormDataIssue2$zodSchema)),
  name: z.string(),
});

export type SubmitCollectFormDataResponseBody2 = {
  success: boolean;
  error: SubmitCollectFormDataError2;
};

export const SubmitCollectFormDataResponseBody2$zodSchema: z.ZodType<
  SubmitCollectFormDataResponseBody2
> = z.object({
  error: z.lazy(() => SubmitCollectFormDataError2$zodSchema),
  success: z.boolean(),
});

export type SubmitCollectFormDataPath1 = string | number;

export const SubmitCollectFormDataPath1$zodSchema: z.ZodType<
  SubmitCollectFormDataPath1
> = z.union([
  z.string(),
  z.number(),
]);

export type SubmitCollectFormDataIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const SubmitCollectFormDataIssue1$zodSchema: z.ZodType<
  SubmitCollectFormDataIssue1
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type SubmitCollectFormDataError1 = {
  issues: Array<SubmitCollectFormDataIssue1>;
  name: string;
};

export const SubmitCollectFormDataError1$zodSchema: z.ZodType<
  SubmitCollectFormDataError1
> = z.object({
  issues: z.array(z.lazy(() => SubmitCollectFormDataIssue1$zodSchema)),
  name: z.string(),
});

export type SubmitCollectFormDataResponseBody1 = {
  success: boolean;
  error: SubmitCollectFormDataError1;
};

export const SubmitCollectFormDataResponseBody1$zodSchema: z.ZodType<
  SubmitCollectFormDataResponseBody1
> = z.object({
  error: z.lazy(() => SubmitCollectFormDataError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type SubmitCollectFormDataResponseBody =
  | SubmitCollectFormDataResponseBody1
  | SubmitCollectFormDataResponseBody2;

export const SubmitCollectFormDataResponseBody$zodSchema: z.ZodType<
  SubmitCollectFormDataResponseBody
> = z.union([
  z.lazy(() => SubmitCollectFormDataResponseBody1$zodSchema),
  z.lazy(() => SubmitCollectFormDataResponseBody2$zodSchema),
]).describe("The validation error(s)");

export const SubmitCollectFormDataStatusCode = {
  FourHundredAndFour: 404,
} as const;
export type SubmitCollectFormDataStatusCode = ClosedEnum<
  typeof SubmitCollectFormDataStatusCode
>;

export const SubmitCollectFormDataStatusCode$zodSchema = z.literal(404);

export const SubmitCollectFormDataType = {
  NotFound: "not_found",
} as const;
export type SubmitCollectFormDataType = ClosedEnum<
  typeof SubmitCollectFormDataType
>;

export const SubmitCollectFormDataType$zodSchema = z.enum([
  "not_found",
]);

export const SubmitCollectFormDataCode = {
  CollectTokenNotFound: "collect_token_not_found",
} as const;
export type SubmitCollectFormDataCode = ClosedEnum<
  typeof SubmitCollectFormDataCode
>;

export const SubmitCollectFormDataCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type SubmitCollectFormDataNotFoundResponseBody = {
  status_code: SubmitCollectFormDataStatusCode;
  type: SubmitCollectFormDataType;
  code: SubmitCollectFormDataCode;
  message: string;
};

export const SubmitCollectFormDataNotFoundResponseBody$zodSchema: z.ZodType<
  SubmitCollectFormDataNotFoundResponseBody
> = z.object({
  code: SubmitCollectFormDataCode$zodSchema,
  message: z.string(),
  status_code: SubmitCollectFormDataStatusCode$zodSchema,
  type: SubmitCollectFormDataType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

export type SubmitCollectFormDataResponse =
  | CollectFormDataSubmission
  | SubmitCollectFormDataNotFoundResponseBody
  | BadRequest
  | RateLimit
  | SubmitCollectFormDataResponseBody1
  | SubmitCollectFormDataResponseBody2;

export const SubmitCollectFormDataResponse$zodSchema: z.ZodType<
  SubmitCollectFormDataResponse
> = z.union([
  CollectFormDataSubmission$zodSchema,
  z.lazy(() => SubmitCollectFormDataNotFoundResponseBody$zodSchema),
  BadRequest$zodSchema,
  RateLimit$zodSchema,
  z.union([
    z.lazy(() => SubmitCollectFormDataResponseBody1$zodSchema),
    z.lazy(() => SubmitCollectFormDataResponseBody2$zodSchema),
  ]),
]);
