/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BadRequest, BadRequest$zodSchema } from "./badrequest.js";
import {
  CollectFileSubmission,
  CollectFileSubmission$zodSchema,
} from "./collectfilesubmission.js";
import {
  CollectFileSubmitForm,
  CollectFileSubmitForm$zodSchema,
} from "./collectfilesubmitform.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";

export type SubmitCollectFileRequest = {
  token: string;
  CollectFileSubmitForm: CollectFileSubmitForm;
};

export const SubmitCollectFileRequest$zodSchema: z.ZodType<
  SubmitCollectFileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  CollectFileSubmitForm: CollectFileSubmitForm$zodSchema,
  token: z.string(),
});

export type SubmitCollectFilePath2 = string | number;

export const SubmitCollectFilePath2$zodSchema: z.ZodType<
  SubmitCollectFilePath2,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type SubmitCollectFileIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const SubmitCollectFileIssue2$zodSchema: z.ZodType<
  SubmitCollectFileIssue2,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type SubmitCollectFileError2 = {
  issues: Array<SubmitCollectFileIssue2>;
  name: string;
};

export const SubmitCollectFileError2$zodSchema: z.ZodType<
  SubmitCollectFileError2,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => SubmitCollectFileIssue2$zodSchema)),
  name: z.string(),
});

export type SubmitCollectFileResponseBody2 = {
  success: boolean;
  error: SubmitCollectFileError2;
};

export const SubmitCollectFileResponseBody2$zodSchema: z.ZodType<
  SubmitCollectFileResponseBody2,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => SubmitCollectFileError2$zodSchema),
  success: z.boolean(),
});

export type SubmitCollectFilePath1 = string | number;

export const SubmitCollectFilePath1$zodSchema: z.ZodType<
  SubmitCollectFilePath1,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.string(),
  z.number(),
]);

export type SubmitCollectFileIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const SubmitCollectFileIssue1$zodSchema: z.ZodType<
  SubmitCollectFileIssue1,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.string(),
  message: z.string().optional(),
  path: z.array(z.union([
    z.string(),
    z.number(),
  ])),
});

export type SubmitCollectFileError1 = {
  issues: Array<SubmitCollectFileIssue1>;
  name: string;
};

export const SubmitCollectFileError1$zodSchema: z.ZodType<
  SubmitCollectFileError1,
  z.ZodTypeDef,
  unknown
> = z.object({
  issues: z.array(z.lazy(() => SubmitCollectFileIssue1$zodSchema)),
  name: z.string(),
});

export type SubmitCollectFileResponseBody1 = {
  success: boolean;
  error: SubmitCollectFileError1;
};

export const SubmitCollectFileResponseBody1$zodSchema: z.ZodType<
  SubmitCollectFileResponseBody1,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.lazy(() => SubmitCollectFileError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type SubmitCollectFileResponseBody =
  | SubmitCollectFileResponseBody1
  | SubmitCollectFileResponseBody2;

export const SubmitCollectFileResponseBody$zodSchema: z.ZodType<
  SubmitCollectFileResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => SubmitCollectFileResponseBody1$zodSchema),
  z.lazy(() => SubmitCollectFileResponseBody2$zodSchema),
]).describe("The validation error(s)");

export const SubmitCollectFileRequestEntityTooLargeStatusCode$zodSchema = z
  .literal(413);

export type SubmitCollectFileRequestEntityTooLargeStatusCode = z.infer<
  typeof SubmitCollectFileRequestEntityTooLargeStatusCode$zodSchema
>;

export const SubmitCollectFileRequestEntityTooLargeType$zodSchema = z.enum([
  "bad_request",
]);

export type SubmitCollectFileRequestEntityTooLargeType = z.infer<
  typeof SubmitCollectFileRequestEntityTooLargeType$zodSchema
>;

export const SubmitCollectFileRequestEntityTooLargeCode$zodSchema = z.enum([
  "payload_too_large",
]);

export type SubmitCollectFileRequestEntityTooLargeCode = z.infer<
  typeof SubmitCollectFileRequestEntityTooLargeCode$zodSchema
>;

/**
 * Payload too large
 */
export type SubmitCollectFileRequestEntityTooLargeResponseBody = {
  status_code: SubmitCollectFileRequestEntityTooLargeStatusCode;
  type: SubmitCollectFileRequestEntityTooLargeType;
  code: SubmitCollectFileRequestEntityTooLargeCode;
  message: string;
};

export const SubmitCollectFileRequestEntityTooLargeResponseBody$zodSchema:
  z.ZodType<
    SubmitCollectFileRequestEntityTooLargeResponseBody,
    z.ZodTypeDef,
    unknown
  > = z.object({
    code: SubmitCollectFileRequestEntityTooLargeCode$zodSchema,
    message: z.string(),
    status_code: SubmitCollectFileRequestEntityTooLargeStatusCode$zodSchema,
    type: SubmitCollectFileRequestEntityTooLargeType$zodSchema,
  }).describe("Payload too large");

export const SubmitCollectFileNotFoundStatusCode$zodSchema = z.literal(404);

export type SubmitCollectFileNotFoundStatusCode = z.infer<
  typeof SubmitCollectFileNotFoundStatusCode$zodSchema
>;

export const SubmitCollectFileNotFoundType$zodSchema = z.enum([
  "not_found",
]);

export type SubmitCollectFileNotFoundType = z.infer<
  typeof SubmitCollectFileNotFoundType$zodSchema
>;

export const SubmitCollectFileNotFoundCode$zodSchema = z.enum([
  "collect_token_not_found",
]);

export type SubmitCollectFileNotFoundCode = z.infer<
  typeof SubmitCollectFileNotFoundCode$zodSchema
>;

/**
 * Collect session not found. The token may be invalid or revoked.
 */
export type SubmitCollectFileNotFoundResponseBody = {
  status_code: SubmitCollectFileNotFoundStatusCode;
  type: SubmitCollectFileNotFoundType;
  code: SubmitCollectFileNotFoundCode;
  message: string;
};

export const SubmitCollectFileNotFoundResponseBody$zodSchema: z.ZodType<
  SubmitCollectFileNotFoundResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: SubmitCollectFileNotFoundCode$zodSchema,
  message: z.string(),
  status_code: SubmitCollectFileNotFoundStatusCode$zodSchema,
  type: SubmitCollectFileNotFoundType$zodSchema,
}).describe("Collect session not found. The token may be invalid or revoked.");

export type SubmitCollectFileResponse =
  | CollectFileSubmission
  | SubmitCollectFileNotFoundResponseBody
  | BadRequest
  | SubmitCollectFileRequestEntityTooLargeResponseBody
  | RateLimit
  | SubmitCollectFileResponseBody1
  | SubmitCollectFileResponseBody2;

export const SubmitCollectFileResponse$zodSchema: z.ZodType<
  SubmitCollectFileResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  CollectFileSubmission$zodSchema,
  z.lazy(() => SubmitCollectFileNotFoundResponseBody$zodSchema),
  BadRequest$zodSchema,
  z.lazy(() => SubmitCollectFileRequestEntityTooLargeResponseBody$zodSchema),
  RateLimit$zodSchema,
  z.union([
    z.lazy(() => SubmitCollectFileResponseBody1$zodSchema),
    z.lazy(() => SubmitCollectFileResponseBody2$zodSchema),
  ]),
]);
