/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * The status of the task
 */
export const TaskStatus = {
  InProgress: "IN_PROGRESS",
  Accepted: "ACCEPTED",
  Open: "OPEN",
  InReview: "IN_REVIEW",
  Declined: "DECLINED",
} as const;
/**
 * The status of the task
 */
export type TaskStatus = ClosedEnum<typeof TaskStatus>;

export const TaskStatus$zodSchema = z.enum([
  "IN_PROGRESS",
  "ACCEPTED",
  "OPEN",
  "IN_REVIEW",
  "DECLINED",
]).describe("The status of the task");

/**
 * The type of the actor
 */
export const ActorType = {
  User: "USER",
  System: "SYSTEM",
  Ai: "AI",
  Api: "API",
} as const;
/**
 * The type of the actor
 */
export type ActorType = ClosedEnum<typeof ActorType>;

export const ActorType$zodSchema = z.enum([
  "USER",
  "SYSTEM",
  "AI",
  "API",
]).describe("The type of the actor");

export type Task = {
  id: string;
  title: string;
  text: string | null;
  status: TaskStatus;
  dueDate: string | null;
  workspaceId: string;
  createdById: string | null;
  actorType: ActorType;
  parentId: string | null;
  destinationFolderId: string | null;
  createdAt: string;
  updatedAt: string;
};

export const Task$zodSchema: z.ZodType<Task> = z.object({
  actorType: ActorType$zodSchema.describe("The type of the actor"),
  createdAt: z.iso.datetime({ offset: true }).describe(
    "The date and time of the creation for the task. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  createdById: z.string().nullable().describe("The ID of the creator"),
  destinationFolderId: z.string().nullable().describe(
    "The ID of the destination folder where assigned files will be stored",
  ),
  dueDate: z.iso.datetime({ offset: true }).nullable().describe(
    "The due date of a task. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  id: z.string().describe("The ID of the task"),
  parentId: z.string().nullable().describe("The ID of the parent task"),
  status: TaskStatus$zodSchema.describe("The status of the task"),
  text: z.string().nullable().describe("The text of the task"),
  title: z.string().describe("The title of the task"),
  updatedAt: z.iso.datetime({ offset: true }).describe(
    "The date and time of the last update for the task. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  workspaceId: z.string().describe("The ID of the workspace"),
});
