/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TaskCreate = {
  title: string;
  text?: string | undefined;
  dueDate?: string | undefined;
  workspaceId: string;
  parentId?: string | undefined;
};

export const TaskCreate$zodSchema: z.ZodType<TaskCreate> = z.object({
  dueDate: z.iso.datetime({ offset: true }).optional().describe(
    "The due date of a task. ISO-8601 format (YYYY-MM-DDTHH:MM:SSZ).",
  ),
  parentId: z.string().optional().describe("The ID of the parent task"),
  text: z.string().optional().describe("The text of the task"),
  title: z.string().describe("The title of the task"),
  workspaceId: z.string().describe("The ID of the workspace"),
});
