/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Task, Task$zodSchema } from "./task.js";
import { TaskUpdate, TaskUpdate$zodSchema } from "./taskupdate.js";

export type UpdateTaskRequest = {
  id: string;
  xClientId: string;
  TaskUpdate: TaskUpdate;
};

export const UpdateTaskRequest$zodSchema: z.ZodType<UpdateTaskRequest> = z
  .object({
    TaskUpdate: TaskUpdate$zodSchema.describe("Task update"),
    id: z.string(),
    xClientId: z.string(),
  });

export type UpdateTaskPath2 = string | number;

export const UpdateTaskPath2$zodSchema: z.ZodType<UpdateTaskPath2> = z.union([
  z.string(),
  z.number(),
]);

export type UpdateTaskIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const UpdateTaskIssue2$zodSchema: z.ZodType<UpdateTaskIssue2> = z.object(
  {
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  },
);

export type UpdateTaskError2 = {
  issues: Array<UpdateTaskIssue2>;
  name: string;
};

export const UpdateTaskError2$zodSchema: z.ZodType<UpdateTaskError2> = z.object(
  {
    issues: z.array(z.lazy(() => UpdateTaskIssue2$zodSchema)),
    name: z.string(),
  },
);

export type UpdateTaskResponseBody2 = {
  success: boolean;
  error: UpdateTaskError2;
};

export const UpdateTaskResponseBody2$zodSchema: z.ZodType<
  UpdateTaskResponseBody2
> = z.object({
  error: z.lazy(() => UpdateTaskError2$zodSchema),
  success: z.boolean(),
});

export type UpdateTaskPath1 = string | number;

export const UpdateTaskPath1$zodSchema: z.ZodType<UpdateTaskPath1> = z.union([
  z.string(),
  z.number(),
]);

export type UpdateTaskIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const UpdateTaskIssue1$zodSchema: z.ZodType<UpdateTaskIssue1> = z.object(
  {
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  },
);

export type UpdateTaskError1 = {
  issues: Array<UpdateTaskIssue1>;
  name: string;
};

export const UpdateTaskError1$zodSchema: z.ZodType<UpdateTaskError1> = z.object(
  {
    issues: z.array(z.lazy(() => UpdateTaskIssue1$zodSchema)),
    name: z.string(),
  },
);

export type UpdateTaskResponseBody1 = {
  success: boolean;
  error: UpdateTaskError1;
};

export const UpdateTaskResponseBody1$zodSchema: z.ZodType<
  UpdateTaskResponseBody1
> = z.object({
  error: z.lazy(() => UpdateTaskError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type UpdateTaskResponseBody =
  | UpdateTaskResponseBody1
  | UpdateTaskResponseBody2;

export const UpdateTaskResponseBody$zodSchema: z.ZodType<
  UpdateTaskResponseBody
> = z.union([
  z.lazy(() => UpdateTaskResponseBody1$zodSchema),
  z.lazy(() => UpdateTaskResponseBody2$zodSchema),
]).describe("The validation error(s)");

export const UpdateTaskForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type UpdateTaskForbiddenStatusCode = ClosedEnum<
  typeof UpdateTaskForbiddenStatusCode
>;

export const UpdateTaskForbiddenStatusCode$zodSchema = z.literal(403);

export const UpdateTaskForbiddenType = {
  AuthError: "auth_error",
} as const;
export type UpdateTaskForbiddenType = ClosedEnum<
  typeof UpdateTaskForbiddenType
>;

export const UpdateTaskForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const UpdateTaskForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type UpdateTaskForbiddenCode = ClosedEnum<
  typeof UpdateTaskForbiddenCode
>;

export const UpdateTaskForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

/**
 * Missing scope
 */
export type UpdateTaskForbiddenResponseBody = {
  status_code: UpdateTaskForbiddenStatusCode;
  type: UpdateTaskForbiddenType;
  code: UpdateTaskForbiddenCode;
  message: string;
};

export const UpdateTaskForbiddenResponseBody$zodSchema: z.ZodType<
  UpdateTaskForbiddenResponseBody
> = z.object({
  code: UpdateTaskForbiddenCode$zodSchema,
  message: z.string(),
  status_code: UpdateTaskForbiddenStatusCode$zodSchema,
  type: UpdateTaskForbiddenType$zodSchema,
}).describe("Missing scope");

export const UpdateTaskStatusCode400 = {
  FourHundred: 400,
} as const;
export type UpdateTaskStatusCode400 = ClosedEnum<
  typeof UpdateTaskStatusCode400
>;

export const UpdateTaskStatusCode400$zodSchema = z.literal(400);

export const UpdateTaskBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type UpdateTaskBadRequestType = ClosedEnum<
  typeof UpdateTaskBadRequestType
>;

export const UpdateTaskBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const UpdateTaskCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type UpdateTaskCodeMissingClientID = ClosedEnum<
  typeof UpdateTaskCodeMissingClientID
>;

export const UpdateTaskCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

/**
 * Missing client ID
 */
export type UpdateTaskBadRequestResponseBody = {
  status_code: UpdateTaskStatusCode400;
  type: UpdateTaskBadRequestType;
  code: UpdateTaskCodeMissingClientID;
  message: string;
};

export const UpdateTaskBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateTaskBadRequestResponseBody
> = z.object({
  code: UpdateTaskCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: UpdateTaskStatusCode400$zodSchema,
  type: UpdateTaskBadRequestType$zodSchema,
}).describe("Missing client ID");

export type UpdateTaskResponse =
  | Task
  | UpdateTaskBadRequestResponseBody
  | AuthError
  | UpdateTaskForbiddenResponseBody
  | NotFound
  | RateLimit
  | UpdateTaskResponseBody1
  | UpdateTaskResponseBody2;

export const UpdateTaskResponse$zodSchema: z.ZodType<UpdateTaskResponse> = z
  .union([
    Task$zodSchema,
    z.lazy(() => UpdateTaskBadRequestResponseBody$zodSchema),
    AuthError$zodSchema,
    z.lazy(() => UpdateTaskForbiddenResponseBody$zodSchema),
    NotFound$zodSchema,
    RateLimit$zodSchema,
    z.union([
      z.lazy(() => UpdateTaskResponseBody1$zodSchema),
      z.lazy(() => UpdateTaskResponseBody2$zodSchema),
    ]),
  ]);
