/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { AuthError, AuthError$zodSchema } from "./autherror.js";
import { InternalError, InternalError$zodSchema } from "./internalerror.js";
import { NotFound, NotFound$zodSchema } from "./notfound.js";
import { RateLimit, RateLimit$zodSchema } from "./ratelimit.js";
import { Workspace, Workspace$zodSchema } from "./workspace.js";
import {
  WorkspaceUpdate,
  WorkspaceUpdate$zodSchema,
} from "./workspaceupdate.js";

export const UpdateWorkspaceForbiddenStatusCode = {
  FourHundredAndThree: 403,
} as const;
export type UpdateWorkspaceForbiddenStatusCode = ClosedEnum<
  typeof UpdateWorkspaceForbiddenStatusCode
>;

export const UpdateWorkspaceForbiddenStatusCode$zodSchema = z.literal(403);

export const UpdateWorkspaceForbiddenType = {
  AuthError: "auth_error",
} as const;
export type UpdateWorkspaceForbiddenType = ClosedEnum<
  typeof UpdateWorkspaceForbiddenType
>;

export const UpdateWorkspaceForbiddenType$zodSchema = z.enum([
  "auth_error",
]);

export const UpdateWorkspaceForbiddenCode = {
  MissingScope: "missing_scope",
} as const;
export type UpdateWorkspaceForbiddenCode = ClosedEnum<
  typeof UpdateWorkspaceForbiddenCode
>;

export const UpdateWorkspaceForbiddenCode$zodSchema = z.enum([
  "missing_scope",
]);

export const UpdateWorkspaceStatusCode400 = {
  FourHundred: 400,
} as const;
export type UpdateWorkspaceStatusCode400 = ClosedEnum<
  typeof UpdateWorkspaceStatusCode400
>;

export const UpdateWorkspaceStatusCode400$zodSchema = z.literal(400);

export const UpdateWorkspaceBadRequestType = {
  BadRequest: "bad_request",
} as const;
export type UpdateWorkspaceBadRequestType = ClosedEnum<
  typeof UpdateWorkspaceBadRequestType
>;

export const UpdateWorkspaceBadRequestType$zodSchema = z.enum([
  "bad_request",
]);

export const UpdateWorkspaceCodeMissingClientID = {
  MissingClientId: "missing_client_id",
} as const;
export type UpdateWorkspaceCodeMissingClientID = ClosedEnum<
  typeof UpdateWorkspaceCodeMissingClientID
>;

export const UpdateWorkspaceCodeMissingClientID$zodSchema = z.enum([
  "missing_client_id",
]);

export type UpdateWorkspaceRequest = {
  id: string;
  xClientId: string;
  WorkspaceUpdate: WorkspaceUpdate;
};

export const UpdateWorkspaceRequest$zodSchema: z.ZodType<
  UpdateWorkspaceRequest
> = z.object({
  WorkspaceUpdate: WorkspaceUpdate$zodSchema.describe("Workspace update"),
  id: z.string(),
  xClientId: z.string(),
});

export type UpdateWorkspacePath2 = string | number;

export const UpdateWorkspacePath2$zodSchema: z.ZodType<UpdateWorkspacePath2> = z
  .union([
    z.string(),
    z.number(),
  ]);

export type UpdateWorkspaceIssue2 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const UpdateWorkspaceIssue2$zodSchema: z.ZodType<UpdateWorkspaceIssue2> =
  z.object({
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  });

export type UpdateWorkspaceError2 = {
  issues: Array<UpdateWorkspaceIssue2>;
  name: string;
};

export const UpdateWorkspaceError2$zodSchema: z.ZodType<UpdateWorkspaceError2> =
  z.object({
    issues: z.array(z.lazy(() => UpdateWorkspaceIssue2$zodSchema)),
    name: z.string(),
  });

export type UpdateWorkspaceResponseBody2 = {
  success: boolean;
  error: UpdateWorkspaceError2;
};

export const UpdateWorkspaceResponseBody2$zodSchema: z.ZodType<
  UpdateWorkspaceResponseBody2
> = z.object({
  error: z.lazy(() => UpdateWorkspaceError2$zodSchema),
  success: z.boolean(),
});

export type UpdateWorkspacePath1 = string | number;

export const UpdateWorkspacePath1$zodSchema: z.ZodType<UpdateWorkspacePath1> = z
  .union([
    z.string(),
    z.number(),
  ]);

export type UpdateWorkspaceIssue1 = {
  code: string;
  path: Array<string | number>;
  message?: string | undefined;
};

export const UpdateWorkspaceIssue1$zodSchema: z.ZodType<UpdateWorkspaceIssue1> =
  z.object({
    code: z.string(),
    message: z.string().optional(),
    path: z.array(z.union([
      z.string(),
      z.number(),
    ])),
  });

export type UpdateWorkspaceError1 = {
  issues: Array<UpdateWorkspaceIssue1>;
  name: string;
};

export const UpdateWorkspaceError1$zodSchema: z.ZodType<UpdateWorkspaceError1> =
  z.object({
    issues: z.array(z.lazy(() => UpdateWorkspaceIssue1$zodSchema)),
    name: z.string(),
  });

export type UpdateWorkspaceResponseBody1 = {
  success: boolean;
  error: UpdateWorkspaceError1;
};

export const UpdateWorkspaceResponseBody1$zodSchema: z.ZodType<
  UpdateWorkspaceResponseBody1
> = z.object({
  error: z.lazy(() => UpdateWorkspaceError1$zodSchema),
  success: z.boolean(),
});

/**
 * The validation error(s)
 */
export type UpdateWorkspaceResponseBody =
  | UpdateWorkspaceResponseBody1
  | UpdateWorkspaceResponseBody2;

export const UpdateWorkspaceResponseBody$zodSchema: z.ZodType<
  UpdateWorkspaceResponseBody
> = z.union([
  z.lazy(() => UpdateWorkspaceResponseBody1$zodSchema),
  z.lazy(() => UpdateWorkspaceResponseBody2$zodSchema),
]).describe("The validation error(s)");

/**
 * Missing scope
 */
export type UpdateWorkspaceForbiddenResponseBody = {
  status_code: UpdateWorkspaceForbiddenStatusCode;
  type: UpdateWorkspaceForbiddenType;
  code: UpdateWorkspaceForbiddenCode;
  message: string;
};

export const UpdateWorkspaceForbiddenResponseBody$zodSchema: z.ZodType<
  UpdateWorkspaceForbiddenResponseBody
> = z.object({
  code: UpdateWorkspaceForbiddenCode$zodSchema,
  message: z.string(),
  status_code: UpdateWorkspaceForbiddenStatusCode$zodSchema,
  type: UpdateWorkspaceForbiddenType$zodSchema,
}).describe("Missing scope");

/**
 * Missing client ID
 */
export type UpdateWorkspaceBadRequestResponseBody = {
  status_code: UpdateWorkspaceStatusCode400;
  type: UpdateWorkspaceBadRequestType;
  code: UpdateWorkspaceCodeMissingClientID;
  message: string;
};

export const UpdateWorkspaceBadRequestResponseBody$zodSchema: z.ZodType<
  UpdateWorkspaceBadRequestResponseBody
> = z.object({
  code: UpdateWorkspaceCodeMissingClientID$zodSchema,
  message: z.string(),
  status_code: UpdateWorkspaceStatusCode400$zodSchema,
  type: UpdateWorkspaceBadRequestType$zodSchema,
}).describe("Missing client ID");

export type UpdateWorkspaceResponse =
  | Workspace
  | UpdateWorkspaceBadRequestResponseBody
  | AuthError
  | UpdateWorkspaceForbiddenResponseBody
  | NotFound
  | RateLimit
  | InternalError
  | UpdateWorkspaceResponseBody1
  | UpdateWorkspaceResponseBody2;

export const UpdateWorkspaceResponse$zodSchema: z.ZodType<
  UpdateWorkspaceResponse
> = z.union([
  Workspace$zodSchema,
  z.lazy(() => UpdateWorkspaceBadRequestResponseBody$zodSchema),
  AuthError$zodSchema,
  z.lazy(() => UpdateWorkspaceForbiddenResponseBody$zodSchema),
  NotFound$zodSchema,
  RateLimit$zodSchema,
  InternalError$zodSchema,
  z.union([
    z.lazy(() => UpdateWorkspaceResponseBody1$zodSchema),
    z.lazy(() => UpdateWorkspaceResponseBody2$zodSchema),
  ]),
]);
