/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WorkspaceMemberRemove = { userId: string };

export const WorkspaceMemberRemove$zodSchema: z.ZodType<WorkspaceMemberRemove> =
  z.object({
    userId: z.string().describe(
      "Identifier of the user that should be removed from the workspace.",
    ),
  });
