/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WorkspaceUpdate = { name: string };

export const WorkspaceUpdate$zodSchema: z.ZodType<WorkspaceUpdate> = z.object({
  name: z.string().describe("The new name of the workspace"),
});
