/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Workspace = {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
  archivedAt: string | null;
  clientId: string;
};

export const Workspace$zodSchema: z.ZodType<Workspace, z.ZodTypeDef, unknown> =
  z.object({
    archivedAt: z.string().nullable(),
    clientId: z.string(),
    createdAt: z.string(),
    id: z.string(),
    name: z.string(),
    updatedAt: z.string(),
  });
