/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WorkspaceCreate = { name: string };

export const WorkspaceCreate$zodSchema: z.ZodType<
  WorkspaceCreate,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});
