/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WorkspaceMemberCreate = { userId: string };

export const WorkspaceMemberCreate$zodSchema: z.ZodType<WorkspaceMemberCreate> =
  z.object({
    userId: z.string().describe(
      "Identifier of the user that should be added to the workspace.",
    ),
  });
